#### Notebook to feature engineer fraction of time ozone was above 75th percentile

In [1]:
## conda environment Weather_Prediction

import os
import numpy as np
import pandas as pd
import geopandas as gpd
import xarray as xr
pd.set_option('display.max_columns', None)
pd.set_option('display.precision', 15)

In [2]:
PATH_1=os.path.join('..','..','..','..','Weather_Data','CAMS','2019','2019_multi_level_26_variables.nc')
ml_26_variables = xr.open_dataset(PATH_1) ## multilevel 26 variables
ml_26_variables = ml_26_variables.squeeze(dim="model_level") ## remove the model_level dimension
ml_26_variables=ml_26_variables.drop_vars('model_level') ## the dropped dimension becomes a column, so remove that
ml_26_variables['longitude'] = ml_26_variables['longitude']-360 ## necessary because of longitude data in multi-level case
ml_26_variables
ozone=ml_26_variables['go3'] ## get only ozone variable
ozone

<xarray.DataArray 'go3' (valid_time: 2920, latitude: 34, longitude: 78)> Size: 31MB
[7743840 values with dtype=float32]
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 23kB 2019-01-01 ... 2019-12-31T21...
  * latitude    (latitude) float64 272B 49.25 48.5 47.75 ... 26.0 25.25 24.5
  * longitude   (longitude) float64 624B -124.8 -124.1 -123.3 ... -67.85 -67.1
Attributes: (12/31)
    GRIB_paramId:                             210203
    GRIB_dataType:                            an
    GRIB_numberOfPoints:                      2652
    GRIB_typeOfLevel:                         hybrid
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_pv:                                  [0.00000000e+00 2.00000000e+01 ...
    GRIB_shortName:                           go3
    GRIB_units:                               kg kg**-1
    long_name:                                Ozone mass mixing ratio (full c...
    units:                                    kg kg**-1
    standard_name:                            mass_fraction_of_ozone_in_air

In [3]:
ozone.to_dataframe()

                                                                 go3
valid_time          latitude longitude
2019-01-01 00:00:00 49.25    -124.849999999999994  0.000000045180137
                             -124.099999999999994  0.000000045110042
                             -123.349999999999994  0.000000042956671
                             -122.599999999999994  0.000000042095884
                             -121.849999999999994  0.000000034072663
...                                                              ...
2019-12-31 21:00:00 24.50    -70.100000000000023   0.000000075228087
                             -69.350000000000023   0.000000075802639
                             -68.600000000000023   0.000000075892288
                             -67.850000000000023   0.000000074857482
                             -67.100000000000023   0.000000074604770

[7743840 rows x 1 columns]

In [4]:
PATH_2=os.path.join('..','CAMS_79_variables_2019.pkl')
get_data = pd.read_pickle(PATH_2) ## load the data with all variables
get_data.head()

,NAME,fips,u10,v10,d2m,t2m,bcaod550,duaod550,lsm,msl,omaod550,pm1,pm2p5,pm10,ssaod550,suaod550,z,sp,aod469,aod550,aod670,aod865,aod1240,tcco,tc_c2h6,tchcho,tc_h2o2,tc_oh,tc_c5h8,tc_ch4,tc_hno3,tcno2,tc_no,gtco3,tc_pan,tc_c3h8,tcso2,tcwv,co,aermr04,aermr05,aermr06,c2h6,hcho,h2o2,aermr09,aermr07,aermr10,aermr08,oh,c5h8,hno3,no2,no,go3,pan,c3h8,aermr01,aermr02,aermr03,q,aermr11,so2,t,lai_hv,lai_lv,asn,sd,tcw,aermssdus,aermssdum,aermssdul,aermssbchphil,aermssomhphil,aermssbchphob,aermssomhphob,aermsssss,aermssssm,aermssssl,aermsssu,aermssso2
263,Autauga,1001,-0.062556494261735,0.10367541901916,285.987705285449692,292.86146973386434,0.005973501429601,0.010240742840674,0.987117303122137,101788.93329327122774,0.069752871962853,0.000000009197931,0.000000012190275,0.000000016803349,0.012177469122294,0.065017457759191,1304.004138142985994,100212.510062362955068,0.197214993668553,0.163162012038903,0.127138387084991,0.090703345174486,0.054916507140069,0.000827810689106,0.000003065560667,0.000004500692172,0.000009338441708,0.000000004920689,0.000004132134411,0.010039752035825,0.000004598756802,0.000002812955128,0.000000397310783,0.006202791915853,0.00000870704824,0.00000054059275,0.000002384526379,29.112755405357685,0.000000156178482,0.000000000620056,0.00000000106988,0.000000000385474,0.000000000491417,0.000000004297943,0.000000000894872,0.00000000016543,0.000000006148393,0.00000000015256,0.000000003178888,0.00000000000002,0.000000022435618,0.000000000781902,0.000000006170992,0.00000000024465,0.000000061450637,0.000000003149079,0.000000000203343,0.000000000034176,0.000000002760026,0.000000000513464,0.010211670528681,0.000000002073802,0.000000004611242,292.691901402599569,3.908172027753293,2.626013628965302,0.879196390457121,0.000010859119121,28.144170618447834,0.000002000021465,0.000004000959208,0.000003298058701,0.000000110555606,0.000002175193927,0.000000523425542,0.000011997256955,0.000000296167898,0.000024059893533,0.000001763191341,0.000007239714678,0.000001377924571
222,Baldwin,1003,-0.255276851464477,0.15988815671509,289.78943508816451,294.555354092951404,0.006057617327651,0.014535499463316,0.54727123384458,101751.364461870951345,0.067055897673977,0.000000007864316,0.000000011783506,0.000000016339129,0.017569938120559,0.065477681569858,228.575081464678846,101474.186721733320155,0.204200970512521,0.170696640448226,0.135293325723264,0.099738989629604,0.063770827181317,0.000814975473779,0.000003014549534,0.000003491389665,0.00000996520701,0.00000000498628,0.00000155549215,0.010166253682049,0.000004645720612,0.000002516305981,0.00000037924329,0.006086576587663,0.000007487993577,0.00000050576197,0.000001837319344,32.465088105253194,0.000000134619293,0.000000000844971,0.000000001500901,0.000000000538067,0.000000000456922,0.000000002531587,0.000000001061344,0.000000000154697,0.000000004943902,0.000000000143606,0.000000002285184,0.000000000000034,0.000000007929048,0.00000000094991,0.000000004585001,0.000000000215983,0.000000067217631,0.000000002081925,0.000000000164366,0.000000000091338,0.000000007517635,0.000000004182532,0.012618727974566,0.000000001850148,0.000000002508631,294.569787633864735,3.128184727924549,1.972863845858773,0.879990479602732,0.000000002358193,31.29806131442362,0.000002803948851,0.000005752363897,0.000004834905653,0.000000111114137,0.000001878364732,0.000000532235322,0.000011697302436,0.00000041094407,0.000033510488317,0.000004353517098,0.000007440475362,0.000000825708835
166,Barbour,1005,-0.116895177634382,0.089956387921338,286.748193596632348,293.332601806931677,0.00611161000587,0.011265957772765,0.989715883024227,101784.43702304144972,0.06889314001743,0.000000009777966,0.000000013018878,0.000000017903918,0.013702910814057,0.060181571405516,1083.187754297686979,100474.939012025090051,0.192894506822148,0.160155233842519,0.125585681232068,0.090731633185358,0.056131131462031,0.000821682590846,0.000003040712629,0.000004336480234,0.000009576039429,0.000000004926026,0.000003599595399,0.010065672968104,0.000004535319661,0.000002606348753,0.00000038281942,0.00615297178575,0.000008312622582,0.000000523583439,0.000001793048249,30.058801771830957,0.000000160094739,0.000000000668122,0.000000001158102,0.000000000398008,0.000000000517197,0.000000004146742,0.000000000910759,0.000000000195186,0.000000006607148,0.000000000248092,0.000000003639146,0.000000000000022,0.000000020600796,0.000000000744311,0.000000005470591,0.000000000211966,0.000000060839463,0.00000000294144,0.000000000200795,0.000000000041234,0.000000003336558,0.000000000756385,0.010709815754467,0.000000001659515,0.000000001805114,293.319276045381628,3.921413991073412,2.464368781799652,0.879836357669212,0.00000074684575,29.0169465294079,0.000002207672238,0.000004456076165,0.000003468067039,0.0000001267285,0.00000217281383,0.000000522153558,0.000011871442746,0.00000033018685,0.000026865965853,0.00000231618753,0.00000683085319,0.00000084111542
2526,Bibb,1007,0.027039894437365,0.175137719877435,285.643919006891963,292.324421598429694,0.005840445254154,0.009715561173115,0.986683805118335,101790.399040301417699,0.069709700578201,0.000000008961731,0.000000011829219,0.000000016315541,0.011158070917026,0.06687152923186,1346.488672921144143,100160.995594272826565,0.197707049152966,0.163295238343712,0.126850695892364,0.089924493499171,0.053816648202945,0.00083235201764,0.000003086367452,0.000004475178959,0.000009167566748,0.000000004921449,0.000004064971763,0.010035037008698,0.000004686673096,0.000003087907474,0.000000418492822,0.006243891796316,0.000008887678503,0.000000552824924,0.000002552969426,28.536325421057562,0.00000015555,0.0000000005986,0.000000001021965,0.000000000363867,0.000000000483909,0.000000004224021,0.000000000869404,0.000000000149183,0.000000005949004,0.000000000110968,0.000000003011569,0.000000000000021,0.000000022519049,0.000000000825252,0.000000007784787,0.000000000440936,0.000000059841033,0.0000000031373,0.000000000212683,0.000000000030067,0.000000002424945,0.000000000396796,0.010014829519255,0.000000002230204,0.000000005342109,292.134208051558062,3.702625045599368,2.749445286265227,0.878335937443335,0.000034326274582,27.59162458343917,0.000001890474654,0.000003763586288,0.000003239544696,0.000000101368446,0.000002183705459,0.000000518457794,0.000011946348375,0.000000274630706,0.000022291740541,0.000001463502981,0.000007341025316,0.000001558234526
894,Blount,1009,0.129527288518958,0.306885745590022,284.969538117344541,291.528657990189117,0.005687567485019,0.008567611547676,0.979337014648202,101803.284919597630505,0.06811727906516,0.000000008729524,0.000000011361496,0.000000015713196,0.009815969169743,0.06656763003339,1976.716820818198357,99414.276046666098409,0.192584904865837,0.158756069758442,0.122877727623783,0.086429913947082,0.051002902922805,0.000830627169562,0.000003088191777,0.000004273013555,0.000008795826253,0.000000004926998,0.000003197399194,0.009958212471089,0.000004706941429,0.000003284817294,0.000000435322304,0.006299157596523,0.000009108634559,0.000000564502124,0.000002750789069,27.304054936427434,0.000000157434844,0.00000000052413,0.000000000889014,0.000000000321742,0.000000000493069,0.000000003789212,0.000000000839752,0.000000000143744,0.00000000578898,0.0000000001004,0.000000002921561,0.000000000000024,0.000000018417728,0.000000000868581,0.000000008862368,0.00000000060115,0.000000059639589,0.000000002985289,0.000000000243055,0.000000000025416,0.000000002049326,0.000000000291228,0.009723913093423,0.00000000235737,0.000000006104972,291.196649782189638,3.298900771651483,2.785372735309721,0.877180601348601,0.000233161471019,26.403566688785045,0.000001659965782,0.000003292588216,0.000002953709718,0.000000095670253,0.000002149610866,0.000000508115763,0.00001158366353,0.000000242973763,0.000019705427258,0.000001149999032,0.000007133344206,0.000001805207582

In [5]:
percentile_75 = get_data['go3'].quantile(0.75) ## calculate 75th percentile
print(percentile_75)
threshold=percentile_75

5.876412169603302e-08

In [6]:
SHAPE_PATH=os.path.join('..','..','..','..','Shapefiles','county_shapefiles','2019_county_shapefile','cb_2019_us_county_500k.shp')
county_gdf = gpd.read_file(SHAPE_PATH)
county_gdf

,STATEFP,COUNTYFP,COUNTYNS,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,48,081,01383826,0500000US48081,48081,Coke,06,2361153195,42331832,"POLYGON ((-100.82497 31.74941, -100.82415 31.8..."
1,48,273,01383922,0500000US48273,48273,Kleberg,06,2282572445,541041659,"MULTIPOLYGON (((-97.31780 27.49456, -97.31590 ..."
2,48,203,01383887,0500000US48203,48203,Harrison,06,2331138836,40651525,"POLYGON ((-94.70215 32.45618, -94.70197 32.467..."
3,48,223,01383897,0500000US48223,48223,Hopkins,06,1987629163,65639829,"POLYGON ((-95.86333 33.04989, -95.86302 33.065..."
4,48,033,01383802,0500000US48033,48033,Borden,06,2324366073,22297606,"POLYGON ((-101.69128 32.96184, -101.55743 32.9..."
...,...,...,...,...,...,...,...,...,...,...
3228,20,119,00485024,0500000US20119,20119,Meade,06,2533222397,3258258,"POLYGON ((-100.65264 37.41669, -100.65264 37.4..."
3229,38,049,01035305,0500000US38049,38049,McHenry,06,4853487956,97323497,"POLYGON ((-101.05991 48.38598, -101.05988 48.4..."
3230,72,119,01804540,0500000US72119,72119,Río Grande,13,157008568,74876349,"POLYGON ((-65.87666 18.36314, -65.87598 18.364..."
3231,46,021,01266974,0500000US46021,46021,Campbell,06,1900214169,96243697,"POLYGON ((-100.49935 45.94363, -100.46284 45.9..."
3232,27,081,00659486,0500000US27081,27081,Lincoln,06,1390257746,30175154,"POLYGON ((-96.45277 44.19689, -96.45267 44.254..."

In [7]:
geometry_column=county_gdf['geometry']
lat_lon=geometry_column.get_coordinates(index_parts=True)
lat_lon

                           x                   y
0    0  -100.824968999999996  31.749413999999998
     1  -100.824151000000001  31.812061000000000
     2  -100.823909999999998  31.814214999999997
     3  -100.824312000000006  31.816344999999998
     4  -100.823738000000006  31.850076999999999
...                      ...                 ...
3232 89  -96.322918999999999  44.197381999999998
     90  -96.331584999999990  44.197348999999996
     91  -96.450322999999997  44.196978000000001
     92  -96.452774299617687  44.196779980888003
     93  -96.452773999999991  44.196894999999998

[1040851 rows x 2 columns]

In [8]:
def single_county(var):
    
    ''' Function to interpolate the values in a single county by taking a 100 or less latitude and longitude pair.
        And then to find the fraction of time above percentile
        Args:
        --------
             var (int): The index of the county in the shapefile.

        Returns:
        --------
            pm_above_df: Dataframe consisting the values of the variables interpolated in the county.
    '''   
    
    
    longitude= lat_lon.loc[(var), 'x']  # get the longitude
    extract_val=len(longitude) ## find number of longitude that a shapfile has

    ## if number of longitude or latitude is less than 100, that many lat-lon pairs will be extracted, if not, a 100 values
    if extract_val < 100:
        extract_val=extract_val
    else:
        extract_val=100

    longitude=longitude[:extract_val]  ## extract first 100 values or values less than 100
    latitude=lat_lon.loc[(var),'y']    ## get the latitude values
    latitude=latitude[:extract_val]    ## extract first 100 values or values less than 100

    lat_list=latitude.tolist()
    lon_list=longitude.tolist()

    ## find the corresponding values of the variables in the finer grid

    year_avg_finer= ozone.interp(longitude=lon_list, latitude=lat_list)
    
## get only the 100 (or less) pair of latitude and longitude from the lat and lon list from the 100,000 (or less) rows
    get_vals=[]

    for i in range(0, extract_val):
        row=year_avg_finer.isel(latitude=[i], longitude=[i])
        row_df=row.to_dataframe()
        get_vals.append(row_df)
    
    initial_df=pd.concat(get_vals)
    summary = initial_df.groupby("valid_time").mean(["latitude", "longitude"])
    df=summary

    total_rows=len(df)

    c=0
    for i in range(0, total_rows):
        if df['go3'].values[i] > threshold:
            c=c+1

## convert number to a fraction
    frac_time=(c/total_rows)*100
    pm_above_df=pd.DataFrame({'ozone above percentile':[frac_time]})


    return pm_above_df

In [9]:
len(county_gdf)

3233

In [10]:
%%time

## get the values for all counties

df_list_below=[]

for i in range(0,len(county_gdf)): ## loop for the all list of counties
    try:
        df_list_below.append(single_county(i))
    except:
        pass

CPU times: total: 1h 8min 22s
Wall time: 1h 9min 15s

In [11]:
concatenate_df=pd.concat(df_list_below)
final_df=concatenate_df.reset_index(drop=True)
final_df

      ozone above percentile
0         39.554794520547951
1         37.842465753424662
2         40.171232876712324
3         37.876712328767127
4         43.047945205479451
...                      ...
3228      41.541095890410958
3229      26.643835616438356
3230       0.000000000000000
3231      27.328767123287673
3232      28.767123287671232

[3233 rows x 1 columns]

In [12]:
## lets first create a fips column in the original shape file

county_gdf['fips']=county_gdf['STATEFP'] + county_gdf['COUNTYFP']
county_gdf.dtypes
## convert the data type
county_gdf['fips']=county_gdf['fips'].astype(str).astype(int)
county_gdf.dtypes

county_gdf = county_gdf.drop(['STATEFP','COUNTYFP','COUNTYNS','AFFGEOID','GEOID','LSAD','ALAND','AWATER'], axis=1)
county_gdf

            NAME                                           geometry   fips
0           Coke  POLYGON ((-100.82497 31.74941, -100.82415 31.8...  48081
1        Kleberg  MULTIPOLYGON (((-97.31780 27.49456, -97.31590 ...  48273
2       Harrison  POLYGON ((-94.70215 32.45618, -94.70197 32.467...  48203
3        Hopkins  POLYGON ((-95.86333 33.04989, -95.86302 33.065...  48223
4         Borden  POLYGON ((-101.69128 32.96184, -101.55743 32.9...  48033
...          ...                                                ...    ...
3228       Meade  POLYGON ((-100.65264 37.41669, -100.65264 37.4...  20119
3229     McHenry  POLYGON ((-101.05991 48.38598, -101.05988 48.4...  38049
3230  Río Grande  POLYGON ((-65.87666 18.36314, -65.87598 18.364...  72119
3231    Campbell  POLYGON ((-100.49935 45.94363, -100.46284 45.9...  46021
3232     Lincoln  POLYGON ((-96.45277 44.19689, -96.45267 44.254...  27081

[3233 rows x 3 columns]

In [13]:
merged_df=pd.merge(county_gdf, final_df, left_index=True, right_index=True)
merged_df

,NAME,geometry,fips,ozone above percentile
0,Coke,"POLYGON ((-100.82497 31.74941, -100.82415 31.8...",48081,39.554794520547951
1,Kleberg,"MULTIPOLYGON (((-97.31780 27.49456, -97.31590 ...",48273,37.842465753424662
2,Harrison,"POLYGON ((-94.70215 32.45618, -94.70197 32.467...",48203,40.171232876712324
3,Hopkins,"POLYGON ((-95.86333 33.04989, -95.86302 33.065...",48223,37.876712328767127
4,Borden,"POLYGON ((-101.69128 32.96184, -101.55743 32.9...",48033,43.047945205479451
...,...,...,...,...
3228,Meade,"POLYGON ((-100.65264 37.41669, -100.65264 37.4...",20119,41.541095890410958
3229,McHenry,"POLYGON ((-101.05991 48.38598, -101.05988 48.4...",38049,26.643835616438356
3230,Río Grande,"POLYGON ((-65.87666 18.36314, -65.87598 18.364...",72119,0.000000000000000
3231,Campbell,"POLYGON ((-100.49935 45.94363, -100.46284 45.9...",46021,27.328767123287673
3232,Lincoln,"POLYGON ((-96.45277 44.19689, -96.45267 44.254...",27081,28.767123287671232

In [14]:
county_df=merged_df.dropna()
county_df.head()

,NAME,geometry,fips,ozone above percentile
0,Coke,"POLYGON ((-100.82497 31.74941, -100.82415 31.8...",48081,39.554794520547951
1,Kleberg,"MULTIPOLYGON (((-97.31780 27.49456, -97.31590 ...",48273,37.842465753424662
2,Harrison,"POLYGON ((-94.70215 32.45618, -94.70197 32.467...",48203,40.171232876712324
3,Hopkins,"POLYGON ((-95.86333 33.04989, -95.86302 33.065...",48223,37.876712328767127
4,Borden,"POLYGON ((-101.69128 32.96184, -101.55743 32.9...",48033,43.047945205479451

In [15]:
## convert into pandas dataframe without the geometry column
pd.options.display.float_format = '{:.15f}'.format ## see 15 decimal places of the numbers
county_var=pd.DataFrame(county_df.drop(columns='geometry')) 
county_var

            NAME   fips  ozone above percentile
0           Coke  48081      39.554794520547951
1        Kleberg  48273      37.842465753424662
2       Harrison  48203      40.171232876712324
3        Hopkins  48223      37.876712328767127
4         Borden  48033      43.047945205479451
...          ...    ...                     ...
3228       Meade  20119      41.541095890410958
3229     McHenry  38049      26.643835616438356
3230  Río Grande  72119       0.000000000000000
3231    Campbell  46021      27.328767123287673
3232     Lincoln  27081      28.767123287671232

[3233 rows x 3 columns]

In [16]:
county_var.to_pickle('ozone_above_percentile.pkl')