In [1]:
## conda environment Weather_Prediction

import os
import numpy as np
import pandas as pd
import geopandas as gpd
import xarray as xr
pd.set_option('display.max_columns', None)
pd.set_option('display.precision', 15)

In [2]:
PATH_1=os.path.join('..','..','..','Weather_Data','CAMS','2012','2012_single_level_34_variables.nc')
sl_34_variables = xr.open_dataset(PATH_1) ## single level 34 variables
pm2_5=sl_34_variables['pm2p5'] ## get only pm2.5 variable
pm2_5

<xarray.DataArray 'pm2p5' (valid_time: 2928, latitude: 34, longitude: 78)> Size: 31MB
[7765056 values with dtype=float32]
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 23kB 2012-01-01 ... 2012-12-31T21...
  * latitude    (latitude) float64 272B 49.25 48.5 47.75 ... 26.0 25.25 24.5
  * longitude   (longitude) float64 624B -124.8 -124.1 -123.3 ... -67.85 -67.1
Attributes: (12/33)
    GRIB_paramId:                             210073
    GRIB_dataType:                            an
    GRIB_numberOfPoints:                      2652
    GRIB_typeOfLevel:                         surface
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_units:                               kg m**-3
    long_name:                                Particulate matter d <= 2.5 um
    units:                                    kg m**-3
    standard_name:                            mass_concentration_of_pm2p5_amb...
    GRIB_number:                              0
    GRIB_surface:                             0.0

In [3]:
pm2_5.to_dataframe()

                                                               pm2p5
valid_time          latitude longitude
2012-01-01 00:00:00 49.25    -124.849999999999994  0.000000006181829
                             -124.099999999999994  0.000000008701807
                             -123.349999999999994  0.000000010656269
                             -122.599999999999994  0.000000008711236
                             -121.849999999999994  0.000000005066401
...                                                              ...
2012-12-31 21:00:00 24.50    -70.099999999999994   0.000000018569782
                             -69.349999999999994   0.000000018977582
                             -68.599999999999994   0.000000019458330
                             -67.849999999999994   0.000000019950926
                             -67.099999999999994   0.000000020477636

[7765056 rows x 1 columns]

In [4]:
pm_threshold=9*10**(-9) ## epa standard
pm_threshold

9.000000000000001e-09

In [5]:
SHAPE_PATH=os.path.join('..','..','..','Shapefiles','county_shapefiles','2012_county_shapefile','tl_2012_us_county.shp')
county_gdf = gpd.read_file(SHAPE_PATH)
county_gdf

,STATEFP,COUNTYFP,COUNTYNS,GEOID,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,CSAFP,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,15,001,00365280,15001,Hawaii,Hawaii County,06,H1,G4020,None,25900,None,A,10433603617,2739477738,+19.5977643,-155.5024434,"POLYGON ((-155.96346 19.08207, -155.96649 19.0..."
1,05,027,00063761,05027,Columbia,Columbia County,06,H1,G4020,None,31620,None,A,1984070931,1809509,+33.2230377,-093.2328433,"POLYGON ((-93.49052 33.01846, -93.49052 33.018..."
2,38,011,01035619,38011,Bowman,Bowman County,06,H1,G4020,None,None,None,A,3009063806,13587978,+46.1101438,-103.5059433,"POLYGON ((-104.04579 46.11943, -104.04579 46.1..."
3,36,031,00974114,36031,Essex,Essex County,06,H1,G4020,None,None,None,A,4647119053,315962259,+44.1089711,-073.7775726,"POLYGON ((-73.90969 44.42970, -73.89728 44.430..."
4,35,007,00929117,35007,Colfax,Colfax County,06,H1,G4020,None,None,None,A,9733550626,26310378,+36.6129625,-104.6401256,"POLYGON ((-104.88900 36.26114, -104.90147 36.2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3229,32,003,00863600,32003,Clark,Clark County,06,H1,G4020,332,29820,None,A,20438872004,438784795,+36.2142360,-115.0138188,"POLYGON ((-115.84599 35.96371, -115.84554 35.9..."
3230,04,017,00042808,04017,Navajo,Navajo County,06,H1,G4020,None,43320,None,A,25771507428,24078082,+35.3909336,-110.3209076,"POLYGON ((-110.75068 34.27560, -110.75068 34.2..."
3231,17,183,01785114,17183,Vermilion,Vermilion County,06,H1,G4020,None,19180,None,A,2326763515,7534496,+40.1867398,-087.7267715,"POLYGON ((-87.52801 40.38851, -87.52804 40.386..."
3232,17,181,01785113,17181,Union,Union County,06,H1,G4020,None,None,None,A,1070855764,22502294,+37.4752071,-089.2528079,"POLYGON ((-89.15367 37.60047, -89.14902 37.600..."
3233,06,071,00277300,06071,San Bernardino,San Bernardino County,06,H1,G4020,348,40140,None,A,51947670128,123843203,+34.8572198,-116.1811967,"POLYGON ((-117.63097 35.24736, -117.63117 35.2..."

In [6]:
geometry_column=county_gdf['geometry']
geometry_column

0       POLYGON ((-155.96346 19.08207, -155.96649 19.0...
1       POLYGON ((-93.49052 33.01846, -93.49052 33.018...
2       POLYGON ((-104.04579 46.11943, -104.04579 46.1...
3       POLYGON ((-73.90969 44.42970, -73.89728 44.430...
4       POLYGON ((-104.88900 36.26114, -104.90147 36.2...
                              ...
3229    POLYGON ((-115.84599 35.96371, -115.84554 35.9...
3230    POLYGON ((-110.75068 34.27560, -110.75068 34.2...
3231    POLYGON ((-87.52801 40.38851, -87.52804 40.386...
3232    POLYGON ((-89.15367 37.60047, -89.14902 37.600...
3233    POLYGON ((-117.63097 35.24736, -117.63117 35.2...
Name: geometry, Length: 3234, dtype: geometry

In [7]:
lat_lon=geometry_column.get_coordinates(index_parts=True)
lat_lon

                             x                   y
0    0    -155.963464999999985  19.082072000000000
     1    -155.966488999999996  19.088480000000001
     2    -155.968891999999983  19.093264999999999
     3    -155.972537999999986  19.101381999999997
     4    -155.974041000000000  19.107789000000000
...                        ...                 ...
3233 5787 -117.631017999999997  35.214576000000001
     5788 -117.630863000000005  35.222859999999997
     5789 -117.630941000000007  35.243497999999995
     5790 -117.630971000000002  35.247337999999999
     5791 -117.630972999999997  35.247364999999995

[7373702 rows x 2 columns]

#### Fraction of time PM2.5 was above EPA threshold

In [8]:
def single_county(var):
    
    ''' Function to interpolate the values in a single county by taking a 100 or less latitude and longitude pair.
        And then to find the fraction of time, PM2.5 was above EPA standard
        Args:
        --------
             var (int): The index of the county in the shapefile.

        Returns:
        --------
            pm_above_df: Dataframe consisting the values of the variables interpolated in the county.
    '''   
    
    
    longitude= lat_lon.loc[(var), 'x']  # get the longitude
    extract_val=len(longitude) ## find number of longitude that a shapfile has

    ## if number of longitude or latitude is less than 100, that many lat-lon pairs will be extracted, if not, a 100 values
    if extract_val < 100:
        extract_val=extract_val
    else:
        extract_val=100

    longitude=longitude[:extract_val]  ## extract first 100 values or values less than 100
    latitude=lat_lon.loc[(var),'y']    ## get the latitude values
    latitude=latitude[:extract_val]    ## extract first 100 values or values less than 100

    lat_list=latitude.tolist()
    lon_list=longitude.tolist()

    ## find the corresponding values of the variables in the finer grid

    year_avg_finer= pm2_5.interp(longitude=lon_list, latitude=lat_list)
    
## get only the 100 (or less) pair of latitude and longitude from the lat and lon list from the 100,000 (or less) rows
    get_vals=[]

    for i in range(0, extract_val):
        row=year_avg_finer.isel(latitude=[i], longitude=[i])
        row_df=row.to_dataframe()
        get_vals.append(row_df)
    
    initial_df=pd.concat(get_vals)
    summary = initial_df.groupby("valid_time").mean(["latitude", "longitude"])
    df=summary

    total_rows=len(df)

    c=0
    for i in range(0, total_rows):
        if df['pm2p5'].values[i] > pm_threshold:
            c=c+1

## convert number to a fraction
    frac_time=(c/total_rows)*100
    pm_above_df=pd.DataFrame({'PM2.5 above threshold':[frac_time]})


    return pm_above_df

In [9]:
len(county_gdf)

3234

In [10]:
%%time

## get the values for all counties

df_list_below=[]

for i in range(0,len(county_gdf)): ## loop for the all list of counties
    try:
        df_list_below.append(single_county(i))
    except:
        pass

CPU times: total: 50min 38s
Wall time: 51min 10s

In [11]:
concatenate_df=pd.concat(df_list_below)
final_df=concatenate_df.reset_index(drop=True)
final_df

      PM2.5 above threshold
0         0.000000000000000
1        66.939890710382514
2        54.781420765027320
3        52.937158469945359
4        32.103825136612024
...                     ...
3229     41.871584699453550
3230     53.039617486338798
3231     64.139344262295083
3232     61.885245901639344
3233     51.605191256830594

[3234 rows x 1 columns]

In [12]:
## lets first create a fips column in the original shape file

county_gdf['fips']=county_gdf['STATEFP'] + county_gdf['COUNTYFP']
county_gdf.dtypes
## convert the data type
county_gdf['fips']=county_gdf['fips'].astype(str).astype(int)
county_gdf.dtypes

county_gdf = county_gdf.drop(['STATEFP','COUNTYFP','COUNTYNS','GEOID','NAMELSAD','LSAD','CLASSFP','MTFCC'
                             ,'CSAFP','CBSAFP','METDIVFP','FUNCSTAT','ALAND','AWATER','INTPTLAT',
                             'INTPTLON'], axis=1)
county_gdf

                NAME                                           geometry   fips
0             Hawaii  POLYGON ((-155.96346 19.08207, -155.96649 19.0...  15001
1           Columbia  POLYGON ((-93.49052 33.01846, -93.49052 33.018...   5027
2             Bowman  POLYGON ((-104.04579 46.11943, -104.04579 46.1...  38011
3              Essex  POLYGON ((-73.90969 44.42970, -73.89728 44.430...  36031
4             Colfax  POLYGON ((-104.88900 36.26114, -104.90147 36.2...  35007
...              ...                                                ...    ...
3229           Clark  POLYGON ((-115.84599 35.96371, -115.84554 35.9...  32003
3230          Navajo  POLYGON ((-110.75068 34.27560, -110.75068 34.2...   4017
3231       Vermilion  POLYGON ((-87.52801 40.38851, -87.52804 40.386...  17183
3232           Union  POLYGON ((-89.15367 37.60047, -89.14902 37.600...  17181
3233  San Bernardino  POLYGON ((-117.63097 35.24736, -117.63117 35.2...   6071

[3234 rows x 3 columns]

In [13]:
merged_df=pd.merge(county_gdf, final_df, left_index=True, right_index=True)
merged_df

,NAME,geometry,fips,PM2.5 above threshold
0,Hawaii,"POLYGON ((-155.96346 19.08207, -155.96649 19.0...",15001,0.000000000000000
1,Columbia,"POLYGON ((-93.49052 33.01846, -93.49052 33.018...",5027,66.939890710382514
2,Bowman,"POLYGON ((-104.04579 46.11943, -104.04579 46.1...",38011,54.781420765027320
3,Essex,"POLYGON ((-73.90969 44.42970, -73.89728 44.430...",36031,52.937158469945359
4,Colfax,"POLYGON ((-104.88900 36.26114, -104.90147 36.2...",35007,32.103825136612024
...,...,...,...,...
3229,Clark,"POLYGON ((-115.84599 35.96371, -115.84554 35.9...",32003,41.871584699453550
3230,Navajo,"POLYGON ((-110.75068 34.27560, -110.75068 34.2...",4017,53.039617486338798
3231,Vermilion,"POLYGON ((-87.52801 40.38851, -87.52804 40.386...",17183,64.139344262295083
3232,Union,"POLYGON ((-89.15367 37.60047, -89.14902 37.600...",17181,61.885245901639344
3233,San Bernardino,"POLYGON ((-117.63097 35.24736, -117.63117 35.2...",6071,51.605191256830594

In [14]:
county_df=merged_df.dropna()
county_df.head()

,NAME,geometry,fips,PM2.5 above threshold
0,Hawaii,"POLYGON ((-155.96346 19.08207, -155.96649 19.0...",15001,0.000000000000000
1,Columbia,"POLYGON ((-93.49052 33.01846, -93.49052 33.018...",5027,66.939890710382514
2,Bowman,"POLYGON ((-104.04579 46.11943, -104.04579 46.1...",38011,54.781420765027320
3,Essex,"POLYGON ((-73.90969 44.42970, -73.89728 44.430...",36031,52.937158469945359
4,Colfax,"POLYGON ((-104.88900 36.26114, -104.90147 36.2...",35007,32.103825136612024

In [15]:
## convert into pandas dataframe without the geometry column
pd.options.display.float_format = '{:.15f}'.format ## see 15 decimal places of the numbers
county_var=pd.DataFrame(county_df.drop(columns='geometry')) 
county_var

                NAME   fips  PM2.5 above threshold
0             Hawaii  15001      0.000000000000000
1           Columbia   5027     66.939890710382514
2             Bowman  38011     54.781420765027320
3              Essex  36031     52.937158469945359
4             Colfax  35007     32.103825136612024
...              ...    ...                    ...
3229           Clark  32003     41.871584699453550
3230          Navajo   4017     53.039617486338798
3231       Vermilion  17183     64.139344262295083
3232           Union  17181     61.885245901639344
3233  San Bernardino   6071     51.605191256830594

[3234 rows x 3 columns]

In [16]:
county_var.to_pickle('FE_PM25_2012.pkl')