#### Notebook to feature engineer fraction of time so2 was above 90th percentile

In [1]:
## conda environment Weather_Prediction

import os
import numpy as np
import pandas as pd
import geopandas as gpd
import xarray as xr
pd.set_option('display.max_columns', None)
pd.set_option('display.precision', 15)

In [2]:
PATH_1=os.path.join('..','..','..','..','Weather_Data','CAMS','2017','2017_multi_level_26_variables.nc')
ml_26_variables = xr.open_dataset(PATH_1) ## multilevel 26 variables
ml_26_variables = ml_26_variables.squeeze(dim="model_level") ## remove the model_level dimension
ml_26_variables=ml_26_variables.drop_vars('model_level') ## the dropped dimension becomes a column, so remove that
ml_26_variables['longitude'] = ml_26_variables['longitude']-360 ## necessary because of longitude data in multi-level case
so2=ml_26_variables['so2'] ## get only so2 variable
so2

<xarray.DataArray 'so2' (valid_time: 2920, latitude: 34, longitude: 78)> Size: 31MB
[7743840 values with dtype=float32]
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 23kB 2017-01-01 ... 2017-12-31T21...
  * latitude    (latitude) float64 272B 49.25 48.5 47.75 ... 26.0 25.25 24.5
  * longitude   (longitude) float64 624B -124.8 -124.1 -123.3 ... -67.85 -67.1
Attributes: (12/31)
    GRIB_paramId:                             210122
    GRIB_dataType:                            an
    GRIB_numberOfPoints:                      2652
    GRIB_typeOfLevel:                         hybrid
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_pv:                                  [0.00000000e+00 2.00000000e+01 ...
    GRIB_shortName:                           so2
    GRIB_units:                               kg kg**-1
    long_name:                                Sulphur dioxide mass mixing ratio
    units:                                    kg kg**-1
    standard_name:                            mass_fraction_of_sulfur_dioxide...

In [3]:
so2.to_dataframe()

                                                                 so2
valid_time          latitude longitude
2017-01-01 00:00:00 49.25    -124.849999999999994  0.000000000373693
                             -124.099999999999994  0.000000000870601
                             -123.349999999999994  0.000000001687295
                             -122.599999999999994  0.000000001575395
                             -121.849999999999994  0.000000000885586
...                                                              ...
2017-12-31 21:00:00 24.50    -70.100000000000023   0.000000000144622
                             -69.350000000000023   0.000000000160190
                             -68.600000000000023   0.000000000215860
                             -67.850000000000023   0.000000000230213
                             -67.100000000000023   0.000000000196248

[7743840 rows x 1 columns]

In [4]:
PATH_2=os.path.join('..','CAMS_79_variables_2017.pkl')
get_data = pd.read_pickle(PATH_2) ## load the data with all variables
get_data.head()

,NAME,fips,u10,v10,d2m,t2m,bcaod550,duaod550,lsm,msl,omaod550,pm1,pm2p5,pm10,ssaod550,suaod550,z,sp,aod469,aod550,aod670,aod865,aod1240,tcco,tc_c2h6,tchcho,tc_h2o2,tc_oh,tc_c5h8,tc_ch4,tc_hno3,tcno2,tc_no,gtco3,tc_pan,tc_c3h8,tcso2,tcwv,co,aermr04,aermr05,aermr06,c2h6,hcho,h2o2,aermr09,aermr07,aermr10,aermr08,oh,c5h8,hno3,no2,no,go3,pan,c3h8,aermr01,aermr02,aermr03,q,aermr11,so2,t,lai_hv,lai_lv,asn,sd,tcw,aermssdus,aermssdum,aermssdul,aermssbchphil,aermssomhphil,aermssbchphob,aermssomhphob,aermsssss,aermssssm,aermssssl,aermsssu,aermssso2
3100,Autauga,1001,0.047482461196168,0.306517662944248,286.304457789768151,292.564479808157387,0.005378100150626,0.009858676207542,0.986987539115746,101793.992638121955679,0.063731158326689,0.000000009132356,0.00000001222818,0.000000016747358,0.012887633670743,0.060185437832117,1312.642868868908636,100207.067710672825342,0.183178361440993,0.152040978238518,0.119044177704993,0.085655321938392,0.052508313258929,0.000841235165761,0.000003062329524,0.000004418248827,0.000008654135633,0.000000004949976,0.000004068698952,0.010008321737522,0.000004700203413,0.000002992892257,0.000000438750055,0.006239292117153,0.000009075614886,0.000000553151162,0.000002386899836,28.314190164537631,0.000000160922508,0.000000000678028,0.000000001158045,0.000000000302278,0.000000000513967,0.000000004248838,0.000000000828586,0.000000000152375,0.000000005923059,0.000000000164584,0.000000003310654,0.000000000000022,0.000000022248273,0.000000000764713,0.00000000651476,0.000000000308108,0.000000059471519,0.000000003234351,0.000000000212,0.000000000035243,0.000000002849424,0.000000000550254,0.010531814470845,0.000000001933068,0.000000004757717,292.291829434342844,3.906738033237082,2.625992421689393,0.877079025156666,0.000053975805461,28.47695331615574,0.000001979247869,0.00000394085436,0.000002626238698,0.000000103695773,0.000002038861636,0.000000467138577,0.000010543541192,0.00000031084938,0.00002529399058,0.000002198887795,0.000006532654636,0.000001420077368
3232,Baldwin,1003,-0.255560350923212,0.245221639382475,290.005151021147014,294.617269300022372,0.005395949239215,0.014035448838276,0.537408364032015,101758.545493286059354,0.059089403305176,0.000000007303772,0.000000011274712,0.00000001558538,0.01945000002996,0.058792630239015,222.943917360523074,101488.195722701770137,0.186484860300641,0.156763244050423,0.125321374753923,0.093794928029837,0.061286476620017,0.000820003039056,0.000002981950032,0.000003401577693,0.00000933263255,0.000000005004267,0.00000149432222,0.010136964149238,0.000004725113445,0.000002631233559,0.000000409490802,0.006126012852861,0.000007520532042,0.000000507821851,0.000001796289568,31.634492509576006,0.0000001355526,0.000000000877057,0.00000000153492,0.00000000041174,0.000000000454298,0.000000002469179,0.000000000996802,0.000000000134519,0.000000004387867,0.000000000134567,0.00000000216136,0.000000000000036,0.000000007893186,0.000000000939796,0.000000004747568,0.000000000232987,0.000000065324508,0.000000002104494,0.000000000167858,0.000000000099963,0.000000008233711,0.000000004638689,0.012731438272589,0.000000001725365,0.000000002550983,294.542594191651119,3.085259427363285,1.942630401227542,0.879740740135694,0.000001898955021,31.739139232592347,0.000002816364065,0.000005666690104,0.000003557343918,0.000000099323615,0.000001673334661,0.000000473576033,0.000010105746715,0.000000453965175,0.000037109684414,0.000005291692005,0.00000660602627,0.000000820730666
0,Barbour,1005,0.036178664724363,0.235746481973365,286.535409962421625,293.249211238339171,0.005515094904196,0.011261070526987,0.989722920389318,101793.515682766490499,0.062601660344817,0.000000009555018,0.000000012891121,0.000000017614686,0.014588409157369,0.05711400878146,1082.55658972910669,100484.771224113123026,0.181205257059165,0.151080303366126,0.11918520235403,0.087008585285008,0.054573127421371,0.000832660670941,0.000003032312201,0.000004220707939,0.000008836098286,0.000000004952569,0.000003544368351,0.010035712210845,0.000004602594486,0.000002771595861,0.000000421509211,0.006191091565718,0.000008553347895,0.000000536015115,0.000001753369053,29.244039339162217,0.000000163232247,0.000000000739511,0.000000001259359,0.000000000337358,0.000000000533814,0.00000000400166,0.000000000851383,0.000000000179925,0.00000000623248,0.000000000251748,0.000000003650178,0.000000000000023,0.000000020088547,0.000000000728976,0.000000005776703,0.000000000233245,0.000000058404347,0.00000000293004,0.000000000206474,0.000000000042601,0.000000003451071,0.000000000794354,0.010769147957149,0.000000001546086,0.000000001782918,293.102264477981919,3.920961064965877,2.464257714473272,0.879691118513387,0.000008954270125,29.384629686717389,0.000002271954131,0.000004540969614,0.000002828476631,0.000000120822493,0.000002043330273,0.000000464953238,0.000010366503831,0.00000035268636,0.00002873347184,0.000002791048971,0.000006236521275,0.000000842949069
2212,Bibb,1007,0.067137232056882,0.400561772483786,286.014807020132821,292.181374016840493,0.005326465116587,0.008821275336088,0.986634175263605,101788.216331687479396,0.064396250057848,0.0000000087639,0.000000011688612,0.000000016039874,0.011884369423033,0.060600746937231,1344.218019835648192,100161.791600518714404,0.182415817809458,0.151029096983368,0.117753853325514,0.084003434817797,0.050820644267503,0.000848168933799,0.000003089432018,0.000004467559096,0.000008573702879,0.000000004951197,0.000004085288995,0.010004522150257,0.000004804763429,0.00000325767051,0.000000459016353,0.006274273412035,0.000009311421624,0.000000565184774,0.000002571871872,27.678158534652511,0.000000159696584,0.000000000629281,0.000000001077257,0.000000000274576,0.000000000505343,0.000000004169545,0.000000000810471,0.000000000137421,0.00000000569384,0.000000000120934,0.000000003089612,0.000000000000023,0.000000021756747,0.000000000818429,0.000000007921419,0.000000000547369,0.000000058610504,0.000000003244218,0.000000000219357,0.00000000003216,0.0000000025981,0.000000000456297,0.010347767588665,0.000000002045462,0.000000005425215,291.874601693981674,3.709699759891231,2.746173547165281,0.875912908863911,0.000077461775706,27.838710406199681,0.000001760711627,0.000003488173724,0.000002509601069,0.00000009499916,0.000002057523976,0.000000470200439,0.000010657492941,0.000000288374345,0.000023445421017,0.000001917956771,0.000006556031526,0.000001592905025
758,Blount,1009,0.144333206497617,0.495062890288679,285.420628381627694,291.365442179248021,0.00522969840276,0.007173249168848,0.97933975729548,101795.487595685350243,0.063863257648093,0.00000000853051,0.000000011145278,0.000000015383961,0.010340501365328,0.060431196508796,1976.136222087988017,99407.670989479622222,0.178203990848256,0.14703789818716,0.113963920439107,0.080299265281255,0.047643306323654,0.000849599972995,0.000003103830327,0.000004272960992,0.000008278147185,0.000000004954844,0.000003236278377,0.009927898850631,0.000004850583224,0.000003460320954,0.000000477212179,0.006321371197931,0.000009552904549,0.000000579844483,0.000002772431763,26.193112195555894,0.000000162276876,0.000000000512425,0.000000000878923,0.000000000232574,0.000000000515799,0.000000003762512,0.000000000777417,0.000000000131689,0.000000005586401,0.000000000108454,0.000000003012941,0.000000000000026,0.000000017866914,0.000000000872951,0.000000009074694,0.000000000752243,0.000000058452076,0.000000003142266,0.00000000025114,0.00000000002721,0.000000002198871,0.000000000344251,0.010059985854109,0.000000002183683,0.000000006198843,290.934712277538324,3.299027778233846,2.785396685680293,0.874596294761548,0.00027045298049,26.356820423200176,0.000001409964741,0.000002787021756,0.000002300435772,0.000000090980339,0.00000206938356,0.000000463851008,0.000010517484997,0.000000253191759,0.000020558556146,0.000001547696711,0.000006442512829,0.000001833096566

In [5]:
percentile_75 = get_data['so2'].quantile(0.90) ## calculate 90th percentile
print(percentile_75)
threshold=percentile_75

5.778885418383975e-09

In [6]:
SHAPE_PATH=os.path.join('..','..','..','..','Shapefiles','county_shapefiles','2017_county_shapefile','cb_2017_us_county_500k.shp')
county_gdf = gpd.read_file(SHAPE_PATH)
county_gdf

,STATEFP,COUNTYFP,COUNTYNS,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,01,005,00161528,0500000US01005,01005,Barbour,06,2292144656,50538698,"POLYGON ((-85.74803 31.61918, -85.74544 31.618..."
1,01,023,00161537,0500000US01023,01023,Choctaw,06,2365869837,19144469,"POLYGON ((-88.47323 31.89386, -88.46888 31.930..."
2,01,035,00161543,0500000US01035,01035,Conecuh,06,2201948618,6643480,"POLYGON ((-87.42720 31.26436, -87.42551 31.268..."
3,01,051,00161551,0500000US01051,01051,Elmore,06,1601762124,99965171,"POLYGON ((-86.41333 32.75059, -86.37115 32.750..."
4,01,065,00161558,0500000US01065,01065,Hale,06,1667907107,32423356,"POLYGON ((-87.87046 32.76244, -87.86818 32.765..."
...,...,...,...,...,...,...,...,...,...,...
3228,37,069,01008553,0500000US37069,37069,Franklin,06,1273631713,7304032,"POLYGON ((-78.54551 36.05670, -78.54493 36.077..."
3229,48,317,01383941,0500000US48317,48317,Martin,06,2369724595,1931832,"POLYGON ((-102.21103 32.17704, -102.21111 32.3..."
3230,54,107,01560558,0500000US54107,54107,Wood,06,948592039,27228519,"POLYGON ((-81.75582 39.18052, -81.75575 39.180..."
3231,13,269,00344156,0500000US13269,13269,Taylor,06,975612265,7802363,"MULTIPOLYGON (((-84.05331 32.52202, -84.00849 ..."
3232,01,003,00161527,0500000US01003,01003,Baldwin,06,4117605847,1133109409,"POLYGON ((-88.02858 30.22676, -88.02399 30.230..."

In [7]:
geometry_column=county_gdf['geometry']
lat_lon=geometry_column.get_coordinates(index_parts=True)
lat_lon

                           x                   y
0    0   -85.748031999999995  31.619180999999998
     1   -85.745435000000001  31.618897999999998
     2   -85.742650999999995  31.621258999999998
     3   -85.741739999999993  31.619402999999998
     4   -85.739812999999998  31.621810000000000
...                      ...                 ...
3232 799 -87.999995999999996  30.225752999999997
     800 -88.013606999999993  30.223489999999998
     801 -88.021363999999991  30.223333999999998
     802 -88.027677999999995  30.223644999999998
     803 -88.028579999999991  30.226762999999998

[1040321 rows x 2 columns]

In [8]:
def single_county(var):
    
    ''' Function to interpolate the values in a single county by taking a 100 or less latitude and longitude pair.
        And then to find the fraction of time above percentile
        Args:
        --------
             var (int): The index of the county in the shapefile.

        Returns:
        --------
            pm_above_df: Dataframe consisting the values of the variables interpolated in the county.
    '''   
    
    
    longitude= lat_lon.loc[(var), 'x']  # get the longitude
    extract_val=len(longitude) ## find number of longitude that a shapfile has

    ## if number of longitude or latitude is less than 100, that many lat-lon pairs will be extracted, if not, a 100 values
    if extract_val < 100:
        extract_val=extract_val
    else:
        extract_val=100

    longitude=longitude[:extract_val]  ## extract first 100 values or values less than 100
    latitude=lat_lon.loc[(var),'y']    ## get the latitude values
    latitude=latitude[:extract_val]    ## extract first 100 values or values less than 100

    lat_list=latitude.tolist()
    lon_list=longitude.tolist()

    ## find the corresponding values of the variables in the finer grid

    year_avg_finer= so2.interp(longitude=lon_list, latitude=lat_list)
    
## get only the 100 (or less) pair of latitude and longitude from the lat and lon list from the 100,000 (or less) rows
    get_vals=[]

    for i in range(0, extract_val):
        row=year_avg_finer.isel(latitude=[i], longitude=[i])
        row_df=row.to_dataframe()
        get_vals.append(row_df)
    
    initial_df=pd.concat(get_vals)
    summary = initial_df.groupby("valid_time").mean(["latitude", "longitude"])
    df=summary

    total_rows=len(df)

    c=0
    for i in range(0, total_rows):
        if df['so2'].values[i] > threshold:
            c=c+1

## convert number to a fraction
    frac_time=(c/total_rows)*100
    pm_above_df=pd.DataFrame({'so2 above percentile':[frac_time]})


    return pm_above_df

In [9]:
len(county_gdf)

3233

In [10]:
%%time

## get the values for all counties

df_list_below=[]

for i in range(0,len(county_gdf)): ## loop for the all list of counties
    try:
        df_list_below.append(single_county(i))
    except:
        pass

CPU times: total: 1h 18min 17s
Wall time: 1h 19min 52s

In [11]:
concatenate_df=pd.concat(df_list_below)
final_df=concatenate_df.reset_index(drop=True)
final_df

      so2 above percentile
0        2.089041095890411
1        6.301369863013699
2       11.643835616438356
3       45.171232876712331
4       13.321917808219178
...                    ...
3228    21.369863013698630
3229     0.000000000000000
3230    51.232876712328768
3231    27.568493150684930
3232     4.452054794520548

[3233 rows x 1 columns]

In [12]:
## lets first create a fips column in the original shape file

county_gdf['fips']=county_gdf['STATEFP'] + county_gdf['COUNTYFP']
county_gdf.dtypes
## convert the data type
county_gdf['fips']=county_gdf['fips'].astype(str).astype(int)
county_gdf.dtypes

county_gdf = county_gdf.drop(['STATEFP','COUNTYFP','COUNTYNS','AFFGEOID','GEOID','LSAD','ALAND','AWATER'], axis=1)
county_gdf

          NAME                                           geometry   fips
0      Barbour  POLYGON ((-85.74803 31.61918, -85.74544 31.618...   1005
1      Choctaw  POLYGON ((-88.47323 31.89386, -88.46888 31.930...   1023
2      Conecuh  POLYGON ((-87.42720 31.26436, -87.42551 31.268...   1035
3       Elmore  POLYGON ((-86.41333 32.75059, -86.37115 32.750...   1051
4         Hale  POLYGON ((-87.87046 32.76244, -87.86818 32.765...   1065
...        ...                                                ...    ...
3228  Franklin  POLYGON ((-78.54551 36.05670, -78.54493 36.077...  37069
3229    Martin  POLYGON ((-102.21103 32.17704, -102.21111 32.3...  48317
3230      Wood  POLYGON ((-81.75582 39.18052, -81.75575 39.180...  54107
3231    Taylor  MULTIPOLYGON (((-84.05331 32.52202, -84.00849 ...  13269
3232   Baldwin  POLYGON ((-88.02858 30.22676, -88.02399 30.230...   1003

[3233 rows x 3 columns]

In [13]:
merged_df=pd.merge(county_gdf, final_df, left_index=True, right_index=True)
merged_df

,NAME,geometry,fips,so2 above percentile
0,Barbour,"POLYGON ((-85.74803 31.61918, -85.74544 31.618...",1005,2.089041095890411
1,Choctaw,"POLYGON ((-88.47323 31.89386, -88.46888 31.930...",1023,6.301369863013699
2,Conecuh,"POLYGON ((-87.42720 31.26436, -87.42551 31.268...",1035,11.643835616438356
3,Elmore,"POLYGON ((-86.41333 32.75059, -86.37115 32.750...",1051,45.171232876712331
4,Hale,"POLYGON ((-87.87046 32.76244, -87.86818 32.765...",1065,13.321917808219178
...,...,...,...,...
3228,Franklin,"POLYGON ((-78.54551 36.05670, -78.54493 36.077...",37069,21.369863013698630
3229,Martin,"POLYGON ((-102.21103 32.17704, -102.21111 32.3...",48317,0.000000000000000
3230,Wood,"POLYGON ((-81.75582 39.18052, -81.75575 39.180...",54107,51.232876712328768
3231,Taylor,"MULTIPOLYGON (((-84.05331 32.52202, -84.00849 ...",13269,27.568493150684930
3232,Baldwin,"POLYGON ((-88.02858 30.22676, -88.02399 30.230...",1003,4.452054794520548

In [14]:
county_df=merged_df.dropna()
county_df.head()

,NAME,geometry,fips,so2 above percentile
0,Barbour,"POLYGON ((-85.74803 31.61918, -85.74544 31.618...",1005,2.089041095890411
1,Choctaw,"POLYGON ((-88.47323 31.89386, -88.46888 31.930...",1023,6.301369863013699
2,Conecuh,"POLYGON ((-87.42720 31.26436, -87.42551 31.268...",1035,11.643835616438356
3,Elmore,"POLYGON ((-86.41333 32.75059, -86.37115 32.750...",1051,45.171232876712331
4,Hale,"POLYGON ((-87.87046 32.76244, -87.86818 32.765...",1065,13.321917808219178

In [15]:
## convert into pandas dataframe without the geometry column
pd.options.display.float_format = '{:.15f}'.format ## see 15 decimal places of the numbers
county_var=pd.DataFrame(county_df.drop(columns='geometry')) 
county_var

          NAME   fips  so2 above percentile
0      Barbour   1005     2.089041095890411
1      Choctaw   1023     6.301369863013699
2      Conecuh   1035    11.643835616438356
3       Elmore   1051    45.171232876712331
4         Hale   1065    13.321917808219178
...        ...    ...                   ...
3228  Franklin  37069    21.369863013698630
3229    Martin  48317     0.000000000000000
3230      Wood  54107    51.232876712328768
3231    Taylor  13269    27.568493150684930
3232   Baldwin   1003     4.452054794520548

[3233 rows x 3 columns]

In [16]:
county_var.to_pickle('so2_above_percentile.pkl')