#### Notebook to feature engineer fraction of time PM2.5 was above 75th percentile

In [1]:
## conda environment Weather_Prediction

import os
import numpy as np
import pandas as pd
import geopandas as gpd
import xarray as xr
pd.set_option('display.max_columns', None)
pd.set_option('display.precision', 15)

In [2]:
PATH_1=os.path.join('..','..','..','..','Weather_Data','CAMS','2016','2016_single_level_34_variables.nc')
sl_34_variables = xr.open_dataset(PATH_1) ## single level 34 variables
pm2_5=sl_34_variables['pm2p5'] ## get only pm2.5 variable
pm2_5

<xarray.DataArray 'pm2p5' (valid_time: 2688, latitude: 34, longitude: 78)> Size: 29MB
[7128576 values with dtype=float32]
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 22kB 2016-01-31 ... 2016-12-31T21...
  * latitude    (latitude) float64 272B 49.25 48.5 47.75 ... 26.0 25.25 24.5
  * longitude   (longitude) float64 624B -124.8 -124.1 -123.3 ... -67.85 -67.1
Attributes: (12/33)
    GRIB_paramId:                             210073
    GRIB_dataType:                            an
    GRIB_numberOfPoints:                      2652
    GRIB_typeOfLevel:                         surface
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_units:                               kg m**-3
    long_name:                                Particulate matter d <= 2.5 um
    units:                                    kg m**-3
    standard_name:                            mass_concentration_of_pm2p5_amb...
    GRIB_number:                              0
    GRIB_surface:                             0.0

In [3]:
pm2_5.to_dataframe()

                                                               pm2p5
valid_time          latitude longitude
2016-01-31 00:00:00 49.25    -124.849999999999994  0.000000004839642
                             -124.099999999999994  0.000000005734204
                             -123.349999999999994  0.000000007260955
                             -122.599999999999994  0.000000007010009
                             -121.849999999999994  0.000000005048928
...                                                              ...
2016-12-31 21:00:00 24.50    -70.099999999999994   0.000000014629448
                             -69.349999999999994   0.000000015538001
                             -68.599999999999994   0.000000016646471
                             -67.849999999999994   0.000000017259229
                             -67.099999999999994   0.000000017943512

[7128576 rows x 1 columns]

In [4]:
PATH_1=os.path.join('..','CAMS_79_variables_2016.pkl')
get_data = pd.read_pickle(PATH_1) ## load the data with all variables
get_data.head()

,NAME,fips,u10,v10,d2m,t2m,bcaod550,duaod550,lsm,msl,omaod550,pm1,pm2p5,pm10,ssaod550,suaod550,z,sp,aod469,aod550,aod670,aod865,aod1240,tcco,tc_c2h6,tchcho,tc_h2o2,tc_oh,tc_c5h8,tc_ch4,tc_hno3,tcno2,tc_no,gtco3,tc_pan,tc_c3h8,tcso2,tcwv,co,aermr04,aermr05,aermr06,c2h6,hcho,h2o2,aermr09,aermr07,aermr10,aermr08,oh,c5h8,hno3,no2,no,go3,pan,c3h8,aermr01,aermr02,aermr03,q,aermr11,so2,t,lai_hv,lai_lv,asn,sd,tcw,aermssdus,aermssdum,aermssdul,aermssbchphil,aermssomhphil,aermssbchphob,aermssomhphob,aermsssss,aermssssm,aermssssl,aermsssu,aermssso2
18,Autauga,1001,-0.103773943451661,0.238330860484284,285.978841069476914,293.765026431802994,0.005961201169837,0.008741196273109,0.986991154940629,101837.227301303646527,0.069018711316734,0.000000010120445,0.00000001304286,0.000000018001,0.008371154534548,0.059913487760396,1312.645185931505466,100253.921700364371645,0.184722326359176,0.152005751977974,0.117438872759278,0.082490864270272,0.048424365637601,0.000845766688636,0.000003430237943,0.000005402571259,0.000009264568924,0.000000004949938,0.000006845113233,0.009975483635137,0.000004686979135,0.000002795352761,0.000000426623604,0.006248690343926,0.000010010585399,0.000000607311982,0.000002563783065,27.105210505601647,0.000000166052761,0.000000000493627,0.000000000878031,0.000000000280549,0.00000000057011,0.000000004821772,0.000000000885183,0.000000000160163,0.000000006484363,0.000000000189381,0.0000000037266,0.000000000000019,0.00000003056968,0.000000000742895,0.00000000634653,0.000000000320587,0.000000057714392,0.00000000332286,0.000000000233823,0.000000000024604,0.00000000199774,0.000000000280045,0.009910800611649,0.000000001985668,0.000000004946896,292.442623699225408,3.90712796485155,2.626111271202784,0.87983567946631,0.002654818151192,27.216814411134877,0.000001583176779,0.000003199026957,0.000002426670826,0.000000116116263,0.000002231833398,0.000000481748612,0.000010992326099,0.000000212065186,0.000017287833668,0.000001007941311,0.000006336141691,0.00000149047796
19,Baldwin,1003,-0.533989643961039,0.344100933906908,290.036250080983052,294.804390581921552,0.006344210715194,0.010522893439342,0.536937384168002,101801.723525240420713,0.067400227689874,0.000000007677794,0.000000010891709,0.000000015206809,0.012695437323398,0.062503521301647,222.55021994988806,101532.269562191882869,0.19239460015476,0.15946624824341,0.124632296783434,0.089457643505643,0.054656550249251,0.000827462442763,0.000003395294779,0.000003976909739,0.000009955335071,0.000000005022124,0.000002329949765,0.010104239542387,0.000004865833018,0.000002514845173,0.000000405571685,0.006132617710671,0.000008584473493,0.000000571343965,0.000001908023065,30.160667806517768,0.000000141802605,0.000000000570183,0.000000000958288,0.000000000291313,0.000000000512422,0.000000002800057,0.00000000089945,0.000000000137784,0.000000004754546,0.000000000141748,0.000000002367427,0.00000000000003,0.00000001048727,0.000000000858978,0.0000000049516,0.000000000254051,0.000000062287365,0.000000002286594,0.000000000198202,0.000000000075628,0.000000006270831,0.000000003555823,0.012316665196452,0.000000001766485,0.000000002670795,293.856248913577133,3.084487142154205,1.941685532326466,0.879991360059255,0.000792564863189,30.259221424122217,0.000001911866437,0.000003874670409,0.000002867996146,0.000000111472275,0.000001872516854,0.000000526609646,0.000010997628322,0.000000308891062,0.000025296285248,0.00000262174234,0.000006618229058,0.000000860875356
769,Barbour,1005,-0.135359165601791,0.197940996659791,286.469219196545509,294.243027267995387,0.006020224001641,0.008669682745912,0.989718946045979,101838.657033636583947,0.066588461351716,0.000000009396005,0.000000012240362,0.000000016872956,0.009331529365944,0.056007765781541,1083.194284047312294,100531.360933475662023,0.177766655877839,0.146617755138714,0.113714933091703,0.080452308484136,0.047909587080835,0.000837636662334,0.00000341230905,0.000004985478267,0.000009319677482,0.00000000495151,0.000005750594712,0.010003870193744,0.000004688344261,0.000002597910546,0.000000413299113,0.006206097654276,0.000009449352668,0.000000591902412,0.000001936924767,27.870313418826186,0.00000016272585,0.00000000048705,0.000000000871999,0.000000000293315,0.000000000561234,0.000000004331848,0.000000000886396,0.000000000168436,0.000000006103006,0.000000000228844,0.000000003535388,0.00000000000002,0.000000025424601,0.000000000727358,0.000000005300458,0.000000000227341,0.00000005691803,0.000000002954247,0.000000000218855,0.000000000029508,0.000000002402513,0.00000000040633,0.010251003820004,0.000000001561929,0.000000001851623,292.964368613502245,3.92171616752866,2.464506830942574,0.87991985208605,0.001373054324438,27.985471603959081,0.000001571095074,0.000003184173732,0.000002387039081,0.000000124886818,0.000002140470185,0.000000480388672,0.000010639770779,0.000000235146057,0.000019199863892,0.000001294393999,0.00000601280075,0.000000904090859
2967,Bibb,1007,-0.068467080449801,0.285156026538904,285.720524078754977,293.4531527158789,0.005956364840254,0.008845815256549,0.986686577578438,101832.379751060638228,0.070895910128133,0.000000010222985,0.000000013145685,0.000000018139632,0.007811495076971,0.061730885581448,1346.414204328277947,100207.556500605322071,0.188861687465686,0.155240438095675,0.11971581958461,0.083793142014656,0.048834345446624,0.000852130022444,0.000003446103646,0.000005485640265,0.000009204453979,0.000000004956886,0.000006876390388,0.009970806217882,0.000004733884149,0.000003051781752,0.000000450312183,0.006281184485664,0.000010274671105,0.000000619329579,0.000002793848284,26.683361152445929,0.000000167021454,0.000000000503085,0.000000000886532,0.000000000281128,0.000000000570027,0.000000004803939,0.00000000087185,0.000000000154037,0.000000006526574,0.000000000159232,0.000000003657092,0.000000000000019,0.000000031016422,0.000000000778564,0.000000007941233,0.000000000583453,0.000000056766342,0.000000003330349,0.000000000244701,0.000000000021754,0.000000001761438,0.000000000217242,0.009705555285734,0.000000002161806,0.000000005756753,292.110093904316159,3.703117969323651,2.749522659527706,0.879747335883584,0.005264624484385,26.793979283926767,0.000001597836842,0.000003226393095,0.000002507988317,0.0000001108007,0.000002293256516,0.000000486089755,0.000011270301745,0.000000199668707,0.000016262143545,0.000000876448367,0.00000649497366,0.000001694008935
883,Blount,1009,0.056172901329136,0.334335151351488,285.034884393321363,292.784139582845057,0.005730878414327,0.008200069355321,0.979333023550733,101844.037755398472655,0.070035412017471,0.000000009861257,0.00000001258833,0.000000017397383,0.006886369233903,0.062083022866901,1977.501566165548184,99460.995559746908839,0.186340359583594,0.152935779916244,0.117609603473057,0.081834057739339,0.047170377818544,0.000851756101514,0.0000034372446,0.000005237167051,0.000008872485863,0.000000004970233,0.000005523964987,0.009894492837935,0.00000475618681,0.000003252558879,0.000000469552335,0.006327905887853,0.000010523068576,0.000000632786665,0.000003065395353,25.515671853488183,0.000000167735705,0.000000000458492,0.000000000806509,0.000000000264944,0.000000000573614,0.000000004308231,0.000000000838737,0.000000000147105,0.000000006308989,0.000000000141322,0.000000003457402,0.000000000000021,0.000000025214359,0.000000000823019,0.000000008844925,0.000000000712775,0.000000057055926,0.000000003164122,0.000000000271037,0.000000000018247,0.000000001475474,0.000000000157231,0.009321212289839,0.000000002294864,0.00000000650827,291.243752219131011,3.299104073681654,2.785394026127407,0.87944897717499,0.008808480025009,25.633246986165041,0.000001469294861,0.000002975175254,0.000002432862869,0.000000105612556,0.00000227934586,0.000000469121256,0.000011044010774,0.000000178581186,0.000014531217044,0.000000719928678,0.000006450709861,0.000001959686031

In [5]:
percentile_75 = get_data['pm2p5'].quantile(0.75)
percentile_75

1.2553570512840386e-08

In [6]:
pm_threshold=percentile_75

In [7]:
SHAPE_PATH=os.path.join('..','..','..','..','Shapefiles','county_shapefiles','2016_county_shapefile','cb_2016_us_county_500k.shp')
county_gdf = gpd.read_file(SHAPE_PATH)
county_gdf

,STATEFP,COUNTYFP,COUNTYNS,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,19,107,00465242,0500000US19107,19107,Keokuk,06,1500067253,1929323,"POLYGON ((-92.41199 41.50955, -92.35539 41.509..."
1,19,189,00465283,0500000US19189,19189,Winnebago,06,1037261946,3182052,"POLYGON ((-93.97076 43.49960, -93.88843 43.499..."
2,20,093,00485011,0500000US20093,20093,Kearny,06,2254696689,1133601,"POLYGON ((-101.54192 37.91457, -101.54186 37.9..."
3,20,123,00485026,0500000US20123,20123,Mitchell,06,1817632928,44979981,"POLYGON ((-98.49007 39.24167, -98.49005 39.263..."
4,20,187,00485055,0500000US20187,20187,Stanton,06,1762104518,178555,"POLYGON ((-102.04190 37.54119, -102.04189 37.5..."
...,...,...,...,...,...,...,...,...,...,...
3228,72,123,01804542,0500000US72123,72123,Salinas,13,179660999,115910809,"POLYGON ((-66.34257 17.99366, -66.34053 17.995..."
3229,47,017,01639729,0500000US47017,47017,Carroll,06,1547925982,6308712,"POLYGON ((-88.70600 35.79604, -88.70667 35.798..."
3230,51,183,01690257,0500000US51183,51183,Sussex,06,1269664389,6755317,"POLYGON ((-77.61620 36.87920, -77.58713 36.894..."
3231,55,013,01581066,0500000US55013,55013,Burnett,06,2127856271,151932123,"POLYGON ((-92.88571 45.64602, -92.88442 45.652..."
3232,55,041,01581080,0500000US55041,55041,Forest,06,2626878497,83594186,"POLYGON ((-89.04779 45.98234, -89.03148 45.982..."

In [8]:
geometry_column=county_gdf['geometry']
geometry_column

0       POLYGON ((-92.41199 41.50955, -92.35539 41.509...
1       POLYGON ((-93.97076 43.49960, -93.88843 43.499...
2       POLYGON ((-101.54192 37.91457, -101.54186 37.9...
3       POLYGON ((-98.49007 39.24167, -98.49005 39.263...
4       POLYGON ((-102.04190 37.54119, -102.04189 37.5...
                              ...
3228    POLYGON ((-66.34257 17.99366, -66.34053 17.995...
3229    POLYGON ((-88.70600 35.79604, -88.70667 35.798...
3230    POLYGON ((-77.61620 36.87920, -77.58713 36.894...
3231    POLYGON ((-92.88571 45.64602, -92.88442 45.652...
3232    POLYGON ((-89.04779 45.98234, -89.03148 45.982...
Name: geometry, Length: 3233, dtype: geometry

In [9]:
lat_lon=geometry_column.get_coordinates(index_parts=True)
lat_lon

                           x                   y
0    0   -92.411994999999990  41.509547999999995
     1   -92.355389000000002  41.509645999999996
     2   -92.345286999999999  41.509676999999996
     3   -92.297494000000000  41.509789999999995
     4   -92.287641999999991  41.509827999999999
...                      ...                 ...
3232 174 -89.047474999999991  45.796779999999998
     175 -89.047601999999998  45.881585999999999
     176 -89.047601000000000  45.895354999999995
     177 -89.047753000000000  45.924363000000000
     178 -89.047794999999994  45.982344999999995

[1039365 rows x 2 columns]

#### Fraction of time PM2.5 was above threshold

In [10]:
def single_county(var):
    
    ''' Function to interpolate the values in a single county by taking a 100 or less latitude and longitude pair.
        And then to find the fraction of time, PM2.5 was above EPA standard
        Args:
        --------
             var (int): The index of the county in the shapefile.

        Returns:
        --------
            pm_above_df: Dataframe consisting the values of the variables interpolated in the county.
    '''   
    
    
    longitude= lat_lon.loc[(var), 'x']  # get the longitude
    extract_val=len(longitude) ## find number of longitude that a shapfile has

    ## if number of longitude or latitude is less than 100, that many lat-lon pairs will be extracted, if not, a 100 values
    if extract_val < 100:
        extract_val=extract_val
    else:
        extract_val=100

    longitude=longitude[:extract_val]  ## extract first 100 values or values less than 100
    latitude=lat_lon.loc[(var),'y']    ## get the latitude values
    latitude=latitude[:extract_val]    ## extract first 100 values or values less than 100

    lat_list=latitude.tolist()
    lon_list=longitude.tolist()

    ## find the corresponding values of the variables in the finer grid

    year_avg_finer= pm2_5.interp(longitude=lon_list, latitude=lat_list)
    
## get only the 100 (or less) pair of latitude and longitude from the lat and lon list from the 100,000 (or less) rows
    get_vals=[]

    for i in range(0, extract_val):
        row=year_avg_finer.isel(latitude=[i], longitude=[i])
        row_df=row.to_dataframe()
        get_vals.append(row_df)
    
    initial_df=pd.concat(get_vals)
    summary = initial_df.groupby("valid_time").mean(["latitude", "longitude"])
    df=summary

    total_rows=len(df)

    c=0
    for i in range(0, total_rows):
        if df['pm2p5'].values[i] > pm_threshold:
            c=c+1

## convert number to a fraction
    frac_time=(c/total_rows)*100
    pm_above_df=pd.DataFrame({'PM2.5 above threshold':[frac_time]})


    return pm_above_df

In [11]:
len(county_gdf)

3233

In [12]:
%%time

## get the values for all counties

df_list_below=[]

for i in range(0,len(county_gdf)): ## loop for the all list of counties
    try:
        df_list_below.append(single_county(i))
    except:
        pass

CPU times: total: 1h 10min 7s
Wall time: 1h 11min 2s

In [13]:
concatenate_df=pd.concat(df_list_below)
final_df=concatenate_df.reset_index(drop=True)
final_df

      PM2.5 above threshold
0        34.858630952380956
1        29.985119047619047
2        12.909226190476192
3        20.275297619047620
4        12.686011904761903
...                     ...
3228      0.000000000000000
3229     39.174107142857146
3230     39.248511904761905
3231     23.921130952380953
3232     15.885416666666666

[3233 rows x 1 columns]

In [14]:
## lets first create a fips column in the original shape file

county_gdf['fips']=county_gdf['STATEFP'] + county_gdf['COUNTYFP']
county_gdf.dtypes
## convert the data type
county_gdf['fips']=county_gdf['fips'].astype(str).astype(int)
county_gdf.dtypes

county_gdf = county_gdf.drop(['STATEFP','COUNTYFP','COUNTYNS','AFFGEOID','GEOID','LSAD','ALAND','AWATER'], axis=1)
county_gdf

           NAME                                           geometry   fips
0        Keokuk  POLYGON ((-92.41199 41.50955, -92.35539 41.509...  19107
1     Winnebago  POLYGON ((-93.97076 43.49960, -93.88843 43.499...  19189
2        Kearny  POLYGON ((-101.54192 37.91457, -101.54186 37.9...  20093
3      Mitchell  POLYGON ((-98.49007 39.24167, -98.49005 39.263...  20123
4       Stanton  POLYGON ((-102.04190 37.54119, -102.04189 37.5...  20187
...         ...                                                ...    ...
3228    Salinas  POLYGON ((-66.34257 17.99366, -66.34053 17.995...  72123
3229    Carroll  POLYGON ((-88.70600 35.79604, -88.70667 35.798...  47017
3230     Sussex  POLYGON ((-77.61620 36.87920, -77.58713 36.894...  51183
3231    Burnett  POLYGON ((-92.88571 45.64602, -92.88442 45.652...  55013
3232     Forest  POLYGON ((-89.04779 45.98234, -89.03148 45.982...  55041

[3233 rows x 3 columns]

In [15]:
merged_df=pd.merge(county_gdf, final_df, left_index=True, right_index=True)
merged_df

,NAME,geometry,fips,PM2.5 above threshold
0,Keokuk,"POLYGON ((-92.41199 41.50955, -92.35539 41.509...",19107,34.858630952380956
1,Winnebago,"POLYGON ((-93.97076 43.49960, -93.88843 43.499...",19189,29.985119047619047
2,Kearny,"POLYGON ((-101.54192 37.91457, -101.54186 37.9...",20093,12.909226190476192
3,Mitchell,"POLYGON ((-98.49007 39.24167, -98.49005 39.263...",20123,20.275297619047620
4,Stanton,"POLYGON ((-102.04190 37.54119, -102.04189 37.5...",20187,12.686011904761903
...,...,...,...,...
3228,Salinas,"POLYGON ((-66.34257 17.99366, -66.34053 17.995...",72123,0.000000000000000
3229,Carroll,"POLYGON ((-88.70600 35.79604, -88.70667 35.798...",47017,39.174107142857146
3230,Sussex,"POLYGON ((-77.61620 36.87920, -77.58713 36.894...",51183,39.248511904761905
3231,Burnett,"POLYGON ((-92.88571 45.64602, -92.88442 45.652...",55013,23.921130952380953
3232,Forest,"POLYGON ((-89.04779 45.98234, -89.03148 45.982...",55041,15.885416666666666

In [16]:
county_df=merged_df.dropna()
county_df.head()

,NAME,geometry,fips,PM2.5 above threshold
0,Keokuk,"POLYGON ((-92.41199 41.50955, -92.35539 41.509...",19107,34.858630952380956
1,Winnebago,"POLYGON ((-93.97076 43.49960, -93.88843 43.499...",19189,29.985119047619047
2,Kearny,"POLYGON ((-101.54192 37.91457, -101.54186 37.9...",20093,12.909226190476192
3,Mitchell,"POLYGON ((-98.49007 39.24167, -98.49005 39.263...",20123,20.275297619047620
4,Stanton,"POLYGON ((-102.04190 37.54119, -102.04189 37.5...",20187,12.686011904761903

In [17]:
## convert into pandas dataframe without the geometry column
pd.options.display.float_format = '{:.15f}'.format ## see 15 decimal places of the numbers
county_var=pd.DataFrame(county_df.drop(columns='geometry')) 
county_var=county_var.rename(columns={'PM2.5 above threshold':'PM2.5 above percentile'})
county_var

           NAME   fips  PM2.5 above percentile
0        Keokuk  19107      34.858630952380956
1     Winnebago  19189      29.985119047619047
2        Kearny  20093      12.909226190476192
3      Mitchell  20123      20.275297619047620
4       Stanton  20187      12.686011904761903
...         ...    ...                     ...
3228    Salinas  72123       0.000000000000000
3229    Carroll  47017      39.174107142857146
3230     Sussex  51183      39.248511904761905
3231    Burnett  55013      23.921130952380953
3232     Forest  55041      15.885416666666666

[3233 rows x 3 columns]

In [18]:
county_var.to_pickle('PM25_above_percentile.pkl')