#### Notebook to feature engineer fraction of time so2 was above 75th percentile

In [1]:
## conda environment Weather_Prediction

import os
import numpy as np
import pandas as pd
import geopandas as gpd
import xarray as xr
pd.set_option('display.max_columns', None)
pd.set_option('display.precision', 15)

In [2]:
PATH_1=os.path.join('..','..','..','..','Weather_Data','CAMS','2018','2018_multi_level_26_variables.nc')
ml_26_variables = xr.open_dataset(PATH_1) ## multilevel 26 variables
ml_26_variables = ml_26_variables.squeeze(dim="model_level") ## remove the model_level dimension
ml_26_variables=ml_26_variables.drop_vars('model_level') ## the dropped dimension becomes a column, so remove that
ml_26_variables['longitude'] = ml_26_variables['longitude']-360 ## necessary because of longitude data in multi-level case
so2=ml_26_variables['so2'] ## get only so2 variable
so2

<xarray.DataArray 'so2' (valid_time: 2920, latitude: 34, longitude: 78)> Size: 31MB
[7743840 values with dtype=float32]
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 23kB 2018-01-01 ... 2018-12-31T21...
  * latitude    (latitude) float64 272B 49.25 48.5 47.75 ... 26.0 25.25 24.5
  * longitude   (longitude) float64 624B -124.8 -124.1 -123.3 ... -67.85 -67.1
Attributes: (12/31)
    GRIB_paramId:                             210122
    GRIB_dataType:                            an
    GRIB_numberOfPoints:                      2652
    GRIB_typeOfLevel:                         hybrid
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_pv:                                  [0.00000000e+00 2.00000000e+01 ...
    GRIB_shortName:                           so2
    GRIB_units:                               kg kg**-1
    long_name:                                Sulphur dioxide mass mixing ratio
    units:                                    kg kg**-1
    standard_name:                            mass_fraction_of_sulfur_dioxide...

In [3]:
so2.to_dataframe()

                                                                 so2
valid_time          latitude longitude
2018-01-01 00:00:00 49.25    -124.849999999999994  0.000000000511554
                             -124.099999999999994  0.000000000902750
                             -123.349999999999994  0.000000001472008
                             -122.599999999999994  0.000000001252348
                             -121.849999999999994  0.000000000583162
...                                                              ...
2018-12-31 21:00:00 24.50    -70.100000000000023   0.000000000117189
                             -69.350000000000023   0.000000000117802
                             -68.600000000000023   0.000000000114416
                             -67.850000000000023   0.000000000085943
                             -67.100000000000023   0.000000000059014

[7743840 rows x 1 columns]

In [4]:
PATH_2=os.path.join('..','CAMS_79_variables_2018.pkl')
get_data = pd.read_pickle(PATH_2) ## load the data with all variables
get_data.head()

,NAME,fips,u10,v10,d2m,t2m,bcaod550,duaod550,lsm,msl,omaod550,pm1,pm2p5,pm10,ssaod550,suaod550,z,sp,aod469,aod550,aod670,aod865,aod1240,tcco,tc_c2h6,tchcho,tc_h2o2,tc_oh,tc_c5h8,tc_ch4,tc_hno3,tcno2,tc_no,gtco3,tc_pan,tc_c3h8,tcso2,tcwv,co,aermr04,aermr05,aermr06,c2h6,hcho,h2o2,aermr09,aermr07,aermr10,aermr08,oh,c5h8,hno3,no2,no,go3,pan,c3h8,aermr01,aermr02,aermr03,q,aermr11,so2,t,lai_hv,lai_lv,asn,sd,tcw,aermssdus,aermssdum,aermssdul,aermssbchphil,aermssomhphil,aermssbchphob,aermssomhphob,aermsssss,aermssssm,aermssssl,aermsssu,aermssso2
16,Autauga,1001,-0.056862521939005,0.24752361529266,287.516919821259762,293.265590475461238,0.005857146093892,0.008847109419127,0.987158280128199,101802.016343932278687,0.073321482720219,0.000000009351812,0.000000012167515,0.000000016843358,0.012607489996338,0.068460070916856,1301.522040274125857,100229.950604363999446,0.20449841828954,0.16909311577317,0.131491799036666,0.093204418272332,0.055784268070459,0.000826080074857,0.000002932870242,0.000004942383258,0.0000093139783,0.000000005033015,0.000004671660948,0.010031745683662,0.0000043404703,0.00000292187598,0.000000438571746,0.006388722821402,0.000009978605645,0.000000504363966,0.000002340117207,29.653485189266853,0.000000156086028,0.000000000483169,0.00000000080977,0.000000000225695,0.000000000489184,0.000000004372343,0.000000000838296,0.000000000159637,0.00000000609599,0.000000000151395,0.000000003288713,0.00000000000002,0.000000022927346,0.000000000713299,0.000000006095919,0.000000000278305,0.000000059709909,0.000000003286298,0.000000000205268,0.000000000034018,0.000000002756429,0.000000000565363,0.010611689515448,0.000000002040632,0.000000004493795,291.854694504341467,3.908601870989415,2.626007695455742,0.878602219503781,0.000097843104559,29.85859263657678,0.000001632010503,0.000003211934827,0.000002492732728,0.000000108075928,0.000002321888141,0.000000480215833,0.000011200504018,0.000000299629222,0.000024466358542,0.000002111995225,0.000006710803333,0.000001441881782
2758,Baldwin,1003,-0.156795412001169,0.308433085751231,290.986096414624058,295.185230365393181,0.006006058202581,0.014332051723673,0.547271598888048,101765.1201693592011,0.069015078832585,0.000000008307762,0.000000012403774,0.000000016998705,0.018328448993762,0.066298646479782,228.57513677078029,101488.235786967896274,0.207853155501014,0.17398051296152,0.138072728163819,0.101871174629091,0.064905301727,0.000806843476289,0.000002876918348,0.000003789119709,0.0000097359949,0.000000005081415,0.000001783919386,0.010158752232461,0.000004415039444,0.000002604036346,0.000000412645931,0.006284045601327,0.000008217600167,0.000000460553736,0.000001800645063,32.731176361889325,0.000000135850339,0.000000000868489,0.000000001520363,0.000000000402736,0.000000000474076,0.000000002604717,0.000000000975925,0.00000000016004,0.000000005030153,0.000000000165892,0.000000002459314,0.000000000000033,0.000000008346379,0.000000000882115,0.000000004688835,0.000000000247,0.000000065584696,0.00000000216217,0.000000000169516,0.000000000088887,0.000000007329147,0.000000004214427,0.012795374238603,0.000000001844959,0.000000002566208,294.101315387770569,3.12818472792455,1.972863845858774,0.879232828566044,0.000011229246279,32.915870253667002,0.000002683103613,0.000005329339692,0.00000344365011,0.000000115308042,0.000001968648248,0.000000490772913,0.000010897697123,0.000000423459768,0.000034694075907,0.000005002534291,0.000006713817664,0.00000087545632
17,Barbour,1005,-0.072649657700047,0.235801664510329,287.879218365915676,293.818235804994913,0.005866667432569,0.008909990272057,0.98971906608727,101802.668223977001617,0.071424727987677,0.000000009285083,0.000000012203474,0.000000016854301,0.014528577215745,0.065141595567574,1083.19445448392753,100494.11506836010085,0.199958576110971,0.165871702990246,0.129665718431366,0.092786217282425,0.056539215169985,0.000818670495648,0.000002907617519,0.000004674666469,0.000009363262584,0.000000005029195,0.00000404591297,0.010059200681764,0.000004238416193,0.000002699816379,0.00000042481409,0.00635048939413,0.000009474461619,0.000000486766361,0.00000177241819,30.567024262749346,0.000000154979541,0.000000000511034,0.000000000851362,0.000000000213889,0.000000000492641,0.000000004043219,0.000000000842523,0.000000000176933,0.000000006133859,0.000000000211642,0.000000003408485,0.000000000000021,0.000000019704156,0.000000000680644,0.000000005233769,0.000000000189374,0.000000059078816,0.000000002974767,0.000000000194808,0.00000000004095,0.000000003321828,0.000000000802192,0.010918971771149,0.000000001643783,0.000000001733035,292.5499433100033,3.921424000579182,2.464359951362173,0.878780721500208,0.000159764964701,30.767404235764822,0.000001667592971,0.000003254626166,0.000002325621748,0.000000118739649,0.000002257220115,0.000000473247563,0.000010876149038,0.000000336212239,0.000027482763094,0.000002728417997,0.000006404709934,0.000000893340847
2339,Bibb,1007,-0.013240213790202,0.311510106837781,287.109136363387165,292.911211279377994,0.005849079360803,0.009012567376453,0.986686663842153,101797.936481733006076,0.074687345600757,0.000000009172737,0.000000011941797,0.000000016539172,0.011610368744195,0.069907324770937,1346.48795436897035,100170.339275316684507,0.2071870906017,0.171066484932457,0.132719259784037,0.093697309244442,0.055627505019861,0.000831067509998,0.000002952762716,0.000004976674274,0.000009278639433,0.000000005040015,0.000004552497529,0.010025197371009,0.00000448032531,0.00000319959559,0.000000455131239,0.006417954698076,0.000010130020313,0.00000051665326,0.000002554060974,29.106556411571859,0.000000155310114,0.000000000480112,0.000000000815452,0.000000000246153,0.000000000481052,0.000000004257303,0.000000000834917,0.000000000147308,0.000000005956568,0.000000000109747,0.000000003063512,0.000000000000021,0.000000021972028,0.000000000760836,0.000000007548423,0.000000000474554,0.000000058865237,0.00000000326105,0.000000000213167,0.000000000030909,0.00000000250252,0.000000000459562,0.010361043848628,0.000000002225514,0.000000005274395,291.42800887566699,3.702625045599368,2.749445286265227,0.878567121963591,0.000086156170393,29.309812795962859,0.000001642891838,0.00000326314965,0.000002646340182,0.000000098901139,0.00000234904632,0.000000487316013,0.000011461702144,0.000000278831083,0.000022751933828,0.0000018057723,0.000006851427183,0.000001657461583
1020,Blount,1009,0.043623654648565,0.402617285273054,286.460270918036827,292.141066304007097,0.00575556267215,0.008058783509934,0.97933696236543,101810.342290719316225,0.074454961536505,0.000000009022822,0.00000001160956,0.000000016128653,0.010403138483566,0.071294298826149,1976.710840162601471,99423.906543791410513,0.206259471439878,0.169966792818466,0.131386107553771,0.092037144487108,0.053883555415666,0.00083023826487,0.000002963203861,0.000004730087977,0.000008949149979,0.000000005052647,0.00000357279464,0.009948176014518,0.000004571136511,0.000003424117205,0.000000470337313,0.006457569013991,0.000010304445735,0.000000532658364,0.000002796902242,27.850492518423742,0.000000156228414,0.000000000421323,0.000000000719764,0.000000000231025,0.000000000489022,0.000000003805883,0.000000000798321,0.00000000013988,0.000000005825896,0.000000000098392,0.000000002987544,0.000000000000023,0.000000017653892,0.000000000812212,0.000000008524847,0.000000000594633,0.000000058824127,0.000000003100813,0.000000000241078,0.000000000026868,0.000000002176083,0.000000000365976,0.01005042255188,0.000000002412806,0.000000006045084,290.494871683739234,3.298900771651483,2.785372735309721,0.878022554089615,0.000286206014764,28.068106768623043,0.000001451157813,0.000002895843723,0.00000249846579,0.00000009659063,0.000002395947935,0.000000479959283,0.00001129508917,0.00000025014327,0.000020399547279,0.000001487272036,0.000006841683806,0.000001934156433

In [5]:
percentile_75 = get_data['so2'].quantile(0.75) ## calculate 75th percentile
print(percentile_75)
threshold=percentile_75

3.520424854989004e-09

In [6]:
SHAPE_PATH=os.path.join('..','..','..','..','Shapefiles','county_shapefiles','2018_county_shapefile','cb_2018_us_county_500k.shp')
county_gdf = gpd.read_file(SHAPE_PATH)
county_gdf

,STATEFP,COUNTYFP,COUNTYNS,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,21,007,00516850,0500000US21007,21007,Ballard,06,639387454,69473325,"POLYGON ((-89.18137 37.04630, -89.17938 37.053..."
1,21,017,00516855,0500000US21017,21017,Bourbon,06,750439351,4829777,"POLYGON ((-84.44266 38.28324, -84.44114 38.283..."
2,21,031,00516862,0500000US21031,21031,Butler,06,1103571974,13943044,"POLYGON ((-86.94486 37.07341, -86.94346 37.074..."
3,21,065,00516879,0500000US21065,21065,Estill,06,655509930,6516335,"POLYGON ((-84.12662 37.64540, -84.12483 37.646..."
4,21,069,00516881,0500000US21069,21069,Fleming,06,902727151,7182793,"POLYGON ((-83.98428 38.44549, -83.98246 38.450..."
...,...,...,...,...,...,...,...,...,...,...
3228,31,073,00835858,0500000US31073,31073,Gosper,06,1186616237,11831826,"POLYGON ((-100.09510 40.43866, -100.08937 40.4..."
3229,39,075,01074050,0500000US39075,39075,Holmes,06,1094405866,3695230,"POLYGON ((-82.22066 40.66758, -82.19327 40.667..."
3230,48,171,01383871,0500000US48171,48171,Gillespie,06,2740719114,9012764,"POLYGON ((-99.30400 30.49983, -99.28234 30.499..."
3231,55,079,01581100,0500000US55079,55079,Milwaukee,06,625440563,2455383635,"POLYGON ((-88.06959 42.86726, -88.06959 42.872..."
3232,26,139,01623012,0500000US26139,26139,Ottawa,06,1459502408,2765830983,"POLYGON ((-86.26432 43.11830, -86.25103 43.118..."

In [7]:
geometry_column=county_gdf['geometry']
lat_lon=geometry_column.get_coordinates(index_parts=True)
lat_lon

                           x                   y
0    0   -89.181368999999989  37.046304999999997
     1   -89.179383999999999  37.053011999999995
     2   -89.175725000000000  37.062069000000001
     3   -89.171880551089004  37.068183979028497
     4   -89.168087000000000  37.074217999999995
...                      ...                 ...
3232 148 -86.256650867846886  43.087448374873794
     149 -86.258404092491901  43.090980743149295
     150 -86.261183206056998  43.096580055604399
     151 -86.271995813165290  43.118365119164196
     152 -86.264320999999995  43.118296999999998

[1042614 rows x 2 columns]

In [8]:
def single_county(var):
    
    ''' Function to interpolate the values in a single county by taking a 100 or less latitude and longitude pair.
        And then to find the fraction of time above percentile
        Args:
        --------
             var (int): The index of the county in the shapefile.

        Returns:
        --------
            pm_above_df: Dataframe consisting the values of the variables interpolated in the county.
    '''   
    
    
    longitude= lat_lon.loc[(var), 'x']  # get the longitude
    extract_val=len(longitude) ## find number of longitude that a shapfile has

    ## if number of longitude or latitude is less than 100, that many lat-lon pairs will be extracted, if not, a 100 values
    if extract_val < 100:
        extract_val=extract_val
    else:
        extract_val=100

    longitude=longitude[:extract_val]  ## extract first 100 values or values less than 100
    latitude=lat_lon.loc[(var),'y']    ## get the latitude values
    latitude=latitude[:extract_val]    ## extract first 100 values or values less than 100

    lat_list=latitude.tolist()
    lon_list=longitude.tolist()

    ## find the corresponding values of the variables in the finer grid

    year_avg_finer= so2.interp(longitude=lon_list, latitude=lat_list)
    
## get only the 100 (or less) pair of latitude and longitude from the lat and lon list from the 100,000 (or less) rows
    get_vals=[]

    for i in range(0, extract_val):
        row=year_avg_finer.isel(latitude=[i], longitude=[i])
        row_df=row.to_dataframe()
        get_vals.append(row_df)
    
    initial_df=pd.concat(get_vals)
    summary = initial_df.groupby("valid_time").mean(["latitude", "longitude"])
    df=summary

    total_rows=len(df)

    c=0
    for i in range(0, total_rows):
        if df['so2'].values[i] > threshold:
            c=c+1

## convert number to a fraction
    frac_time=(c/total_rows)*100
    pm_above_df=pd.DataFrame({'so2 above percentile':[frac_time]})


    return pm_above_df

In [9]:
len(county_gdf)

3233

In [10]:
%%time

## get the values for all counties

df_list_below=[]

for i in range(0,len(county_gdf)): ## loop for the all list of counties
    try:
        df_list_below.append(single_county(i))
    except:
        pass

CPU times: total: 1h 22min 37s
Wall time: 1h 23min 39s

In [11]:
concatenate_df=pd.concat(df_list_below)
final_df=concatenate_df.reset_index(drop=True)
final_df

      so2 above percentile
0       71.952054794520549
1       63.561643835616444
2       73.458904109589042
3       34.486301369863014
4       63.013698630136986
...                    ...
3228     0.000000000000000
3229    52.294520547945197
3230     0.376712328767123
3231    42.568493150684930
3232    20.650684931506849

[3233 rows x 1 columns]

In [12]:
## lets first create a fips column in the original shape file

county_gdf['fips']=county_gdf['STATEFP'] + county_gdf['COUNTYFP']
county_gdf.dtypes
## convert the data type
county_gdf['fips']=county_gdf['fips'].astype(str).astype(int)
county_gdf.dtypes

county_gdf = county_gdf.drop(['STATEFP','COUNTYFP','COUNTYNS','AFFGEOID','GEOID','LSAD','ALAND','AWATER'], axis=1)
county_gdf

           NAME                                           geometry   fips
0       Ballard  POLYGON ((-89.18137 37.04630, -89.17938 37.053...  21007
1       Bourbon  POLYGON ((-84.44266 38.28324, -84.44114 38.283...  21017
2        Butler  POLYGON ((-86.94486 37.07341, -86.94346 37.074...  21031
3        Estill  POLYGON ((-84.12662 37.64540, -84.12483 37.646...  21065
4       Fleming  POLYGON ((-83.98428 38.44549, -83.98246 38.450...  21069
...         ...                                                ...    ...
3228     Gosper  POLYGON ((-100.09510 40.43866, -100.08937 40.4...  31073
3229     Holmes  POLYGON ((-82.22066 40.66758, -82.19327 40.667...  39075
3230  Gillespie  POLYGON ((-99.30400 30.49983, -99.28234 30.499...  48171
3231  Milwaukee  POLYGON ((-88.06959 42.86726, -88.06959 42.872...  55079
3232     Ottawa  POLYGON ((-86.26432 43.11830, -86.25103 43.118...  26139

[3233 rows x 3 columns]

In [13]:
merged_df=pd.merge(county_gdf, final_df, left_index=True, right_index=True)
merged_df

,NAME,geometry,fips,so2 above percentile
0,Ballard,"POLYGON ((-89.18137 37.04630, -89.17938 37.053...",21007,71.952054794520549
1,Bourbon,"POLYGON ((-84.44266 38.28324, -84.44114 38.283...",21017,63.561643835616444
2,Butler,"POLYGON ((-86.94486 37.07341, -86.94346 37.074...",21031,73.458904109589042
3,Estill,"POLYGON ((-84.12662 37.64540, -84.12483 37.646...",21065,34.486301369863014
4,Fleming,"POLYGON ((-83.98428 38.44549, -83.98246 38.450...",21069,63.013698630136986
...,...,...,...,...
3228,Gosper,"POLYGON ((-100.09510 40.43866, -100.08937 40.4...",31073,0.000000000000000
3229,Holmes,"POLYGON ((-82.22066 40.66758, -82.19327 40.667...",39075,52.294520547945197
3230,Gillespie,"POLYGON ((-99.30400 30.49983, -99.28234 30.499...",48171,0.376712328767123
3231,Milwaukee,"POLYGON ((-88.06959 42.86726, -88.06959 42.872...",55079,42.568493150684930
3232,Ottawa,"POLYGON ((-86.26432 43.11830, -86.25103 43.118...",26139,20.650684931506849

In [14]:
county_df=merged_df.dropna()
county_df.head()

,NAME,geometry,fips,so2 above percentile
0,Ballard,"POLYGON ((-89.18137 37.04630, -89.17938 37.053...",21007,71.952054794520549
1,Bourbon,"POLYGON ((-84.44266 38.28324, -84.44114 38.283...",21017,63.561643835616444
2,Butler,"POLYGON ((-86.94486 37.07341, -86.94346 37.074...",21031,73.458904109589042
3,Estill,"POLYGON ((-84.12662 37.64540, -84.12483 37.646...",21065,34.486301369863014
4,Fleming,"POLYGON ((-83.98428 38.44549, -83.98246 38.450...",21069,63.013698630136986

In [15]:
## convert into pandas dataframe without the geometry column
pd.options.display.float_format = '{:.15f}'.format ## see 15 decimal places of the numbers
county_var=pd.DataFrame(county_df.drop(columns='geometry')) 
county_var

           NAME   fips  so2 above percentile
0       Ballard  21007    71.952054794520549
1       Bourbon  21017    63.561643835616444
2        Butler  21031    73.458904109589042
3        Estill  21065    34.486301369863014
4       Fleming  21069    63.013698630136986
...         ...    ...                   ...
3228     Gosper  31073     0.000000000000000
3229     Holmes  39075    52.294520547945197
3230  Gillespie  48171     0.376712328767123
3231  Milwaukee  55079    42.568493150684930
3232     Ottawa  26139    20.650684931506849

[3233 rows x 3 columns]

In [16]:
county_var.to_pickle('so2_above_percentile.pkl')