#### Notebook to feature engineer fraction of time PM10 was above EPA standard for all counties

In [1]:
## conda environment Weather_Prediction

import os
import numpy as np
import pandas as pd
import geopandas as gpd
import xarray as xr
pd.set_option('display.max_columns', None)
pd.set_option('display.precision', 15)

In [2]:
PATH_1=os.path.join('..','..','..','..','Weather_Data','CAMS','2012','2012_single_level_34_variables.nc')
sl_34_variables = xr.open_dataset(PATH_1) ## single level 34 variables
sl_34_variables
pm10=sl_34_variables['pm10'] ## get only pm2.5 variable
pm10

<xarray.DataArray 'pm10' (valid_time: 2928, latitude: 34, longitude: 78)> Size: 31MB
[7765056 values with dtype=float32]
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 23kB 2012-01-01 ... 2012-12-31T21...
  * latitude    (latitude) float64 272B 49.25 48.5 47.75 ... 26.0 25.25 24.5
  * longitude   (longitude) float64 624B -124.8 -124.1 -123.3 ... -67.85 -67.1
Attributes: (12/33)
    GRIB_paramId:                             210074
    GRIB_dataType:                            an
    GRIB_numberOfPoints:                      2652
    GRIB_typeOfLevel:                         surface
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_units:                               kg m**-3
    long_name:                                Particulate matter d <= 10 um
    units:                                    kg m**-3
    standard_name:                            mass_concentration_of_pm10_ambi...
    GRIB_number:                              0
    GRIB_surface:                             0.0

In [3]:
pm10.to_dataframe()

                                                                pm10
valid_time          latitude longitude
2012-01-01 00:00:00 49.25    -124.849999999999994  0.000000010521645
                             -124.099999999999994  0.000000014306141
                             -123.349999999999994  0.000000016738827
                             -122.599999999999994  0.000000013590475
                             -121.849999999999994  0.000000007809926
...                                                              ...
2012-12-31 21:00:00 24.50    -70.099999999999994   0.000000033419539
                             -69.349999999999994   0.000000034225767
                             -68.599999999999994   0.000000035093002
                             -67.849999999999994   0.000000035986822
                             -67.099999999999994   0.000000036882223

[7765056 rows x 1 columns]

In [4]:
pm_threshold=150*10**(-9) ## epa standard
pm_threshold

1.5000000000000002e-07

In [5]:
SHAPE_PATH=os.path.join('..','..','..','..','Shapefiles','county_shapefiles','2011_county_shapefile','tl_2011_us_county.shp')
county_gdf = gpd.read_file(SHAPE_PATH)
county_gdf

,STATEFP,COUNTYFP,COUNTYNS,GEOID,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,CSAFP,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,72,045,01804502,72045,Comerío,Comerío Municipio,13,H1,G4020,490,41980,None,A,73557132,319735,+18.2250402,-066.2202984,"POLYGON ((-66.25713 18.24744, -66.25695 18.247..."
1,72,009,01804484,72009,Aibonito,Aibonito Municipio,13,H1,G4020,490,41980,None,A,81094444,71897,+18.1306472,-066.2639743,"POLYGON ((-66.25753 18.07588, -66.25937 18.077..."
2,72,039,01804499,72039,Ciales,Ciales Municipio,13,H1,G4020,490,41980,None,A,172309964,459615,+18.2912286,-066.5130169,"POLYGON ((-66.55771 18.27506, -66.55782 18.275..."
3,72,003,01804481,72003,Aguada,Aguada Municipio,13,H1,G4020,None,10380,None,A,79904253,38043835,+18.3756809,-067.1837074,"POLYGON ((-67.16355 18.41748, -67.16190 18.416..."
4,72,151,01804556,72151,Yabucoa,Yabucoa Municipio,13,H1,G4020,490,41980,None,A,143005203,72593008,+18.0598615,-065.8598555,"POLYGON ((-65.87885 18.02066, -65.87926 18.020..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3229,42,099,01213682,42099,Perry,Perry County,06,H1,G4020,276,25420,None,A,1428280078,10597982,+40.3977795,-077.2663284,"POLYGON ((-77.02920 40.38688, -77.02918 40.386..."
3230,40,061,01101818,40061,Haskell,Haskell County,06,H1,G4020,None,None,None,A,1493228577,126266671,+35.2322937,-095.1095776,"POLYGON ((-95.22136 35.27282, -95.22103 35.273..."
3231,17,197,01785190,17197,Will,Will County,06,H1,G4020,176,16980,16974,A,2167580642,31904479,+41.4484742,-087.9784564,"POLYGON ((-88.25535 41.55009, -88.25539 41.550..."
3232,40,081,01101828,40081,Lincoln,Lincoln County,06,H1,G4020,416,36420,None,A,2466481584,34614223,+35.7031175,-096.8813917,"POLYGON ((-97.14113 35.60848, -97.14119 35.609..."
3233,39,055,01074040,39055,Geauga,Geauga County,06,H1,G4020,184,17460,None,A,1036420277,21054492,+41.4993217,-081.1735054,"POLYGON ((-81.39113 41.46705, -81.39113 41.467..."

In [6]:
geometry_column=county_gdf['geometry']
geometry_column

0       POLYGON ((-66.25713 18.24744, -66.25695 18.247...
1       POLYGON ((-66.25753 18.07588, -66.25937 18.077...
2       POLYGON ((-66.55771 18.27506, -66.55782 18.275...
3       POLYGON ((-67.16355 18.41748, -67.16190 18.416...
4       POLYGON ((-65.87885 18.02066, -65.87926 18.020...
                              ...
3229    POLYGON ((-77.02920 40.38688, -77.02918 40.386...
3230    POLYGON ((-95.22136 35.27282, -95.22103 35.273...
3231    POLYGON ((-88.25535 41.55009, -88.25539 41.550...
3232    POLYGON ((-97.14113 35.60848, -97.14119 35.609...
3233    POLYGON ((-81.39113 41.46705, -81.39113 41.467...
Name: geometry, Length: 3234, dtype: geometry

In [7]:
lat_lon=geometry_column.get_coordinates(index_parts=True)
lat_lon

                            x                   y
0    0    -66.257125000000002  18.247439000000000
     1    -66.256954999999991  18.247450999999998
     2    -66.256174999999999  18.247370999999998
     3    -66.255698999999993  18.247496999999999
     4    -66.255297999999996  18.247540999999998
...                       ...                 ...
3233 1161 -81.391229999999993  41.463234000000000
     1162 -81.391228999999996  41.463273000000001
     1163 -81.391212999999993  41.463906000000001
     1164 -81.391134999999991  41.466968000000001
     1165 -81.391133999999994  41.467050999999998

[7394987 rows x 2 columns]

#### Fraction of time PM10 was above EPA threshold

In [8]:
def single_county(var):
    
    ''' Function to interpolate the values in a single county by taking a 100 or less latitude and longitude pair.
        And then to find the fraction of time, PM2.5 was above EPA standard
        Args:
        --------
             var (int): The index of the county in the shapefile.

        Returns:
        --------
            pm_above_df: Dataframe consisting the values of the variables interpolated in the county.
    '''   
    
    
    longitude= lat_lon.loc[(var), 'x']  # get the longitude
    extract_val=len(longitude) ## find number of longitude that a shapfile has

    ## if number of longitude or latitude is less than 100, that many lat-lon pairs will be extracted, if not, a 100 values
    if extract_val < 100:
        extract_val=extract_val
    else:
        extract_val=100

    longitude=longitude[:extract_val]  ## extract first 100 values or values less than 100
    latitude=lat_lon.loc[(var),'y']    ## get the latitude values
    latitude=latitude[:extract_val]    ## extract first 100 values or values less than 100

    lat_list=latitude.tolist()
    lon_list=longitude.tolist()

    ## find the corresponding values of the variables in the finer grid

    year_avg_finer= pm10.interp(longitude=lon_list, latitude=lat_list)
    
## get only the 100 (or less) pair of latitude and longitude from the lat and lon list from the 100,000 (or less) rows
    get_vals=[]

    for i in range(0, extract_val):
        row=year_avg_finer.isel(latitude=[i], longitude=[i])
        row_df=row.to_dataframe()
        get_vals.append(row_df)
    
    initial_df=pd.concat(get_vals)
    summary = initial_df.groupby("valid_time").mean(["latitude", "longitude"])
    df=summary

    total_rows=len(df)

    c=0
    for i in range(0, total_rows):
        if df['pm10'].values[i] > pm_threshold:
            c=c+1

## convert number to a fraction
    frac_time=(c/total_rows)*100
    pm_above_df=pd.DataFrame({'PM10 above threshold':[frac_time]})


    return pm_above_df

In [9]:
len(county_gdf)

3234

In [10]:
%%time

## get the values for all counties

df_list_below=[]

for i in range(0,len(county_gdf)): ## loop for the all list of counties
    try:
        df_list_below.append(single_county(i))
    except:
        pass

CPU times: total: 51min 14s
Wall time: 51min 43s

In [11]:
concatenate_df=pd.concat(df_list_below)
final_df=concatenate_df.reset_index(drop=True)
final_df

      PM10 above threshold
0                      0.0
1                      0.0
2                      0.0
3                      0.0
4                      0.0
...                    ...
3229                   0.0
3230                   0.0
3231                   0.0
3232                   0.0
3233                   0.0

[3234 rows x 1 columns]

In [12]:
## lets first create a fips column in the original shape file

county_gdf['fips']=county_gdf['STATEFP'] + county_gdf['COUNTYFP']
county_gdf.dtypes
## convert the data type
county_gdf['fips']=county_gdf['fips'].astype(str).astype(int)
county_gdf.dtypes

county_gdf = county_gdf.drop(['STATEFP','COUNTYFP','COUNTYNS','GEOID','NAMELSAD','LSAD','CLASSFP','MTFCC'
                             ,'CSAFP','CBSAFP','METDIVFP','FUNCSTAT','ALAND','AWATER','INTPTLAT',
                             'INTPTLON'], axis=1)
county_gdf

          NAME                                           geometry   fips
0      Comerío  POLYGON ((-66.25713 18.24744, -66.25695 18.247...  72045
1     Aibonito  POLYGON ((-66.25753 18.07588, -66.25937 18.077...  72009
2       Ciales  POLYGON ((-66.55771 18.27506, -66.55782 18.275...  72039
3       Aguada  POLYGON ((-67.16355 18.41748, -67.16190 18.416...  72003
4      Yabucoa  POLYGON ((-65.87885 18.02066, -65.87926 18.020...  72151
...        ...                                                ...    ...
3229     Perry  POLYGON ((-77.02920 40.38688, -77.02918 40.386...  42099
3230   Haskell  POLYGON ((-95.22136 35.27282, -95.22103 35.273...  40061
3231      Will  POLYGON ((-88.25535 41.55009, -88.25539 41.550...  17197
3232   Lincoln  POLYGON ((-97.14113 35.60848, -97.14119 35.609...  40081
3233    Geauga  POLYGON ((-81.39113 41.46705, -81.39113 41.467...  39055

[3234 rows x 3 columns]

In [13]:
merged_df=pd.merge(county_gdf, final_df, left_index=True, right_index=True)
merged_df

,NAME,geometry,fips,PM10 above threshold
0,Comerío,"POLYGON ((-66.25713 18.24744, -66.25695 18.247...",72045,0.0
1,Aibonito,"POLYGON ((-66.25753 18.07588, -66.25937 18.077...",72009,0.0
2,Ciales,"POLYGON ((-66.55771 18.27506, -66.55782 18.275...",72039,0.0
3,Aguada,"POLYGON ((-67.16355 18.41748, -67.16190 18.416...",72003,0.0
4,Yabucoa,"POLYGON ((-65.87885 18.02066, -65.87926 18.020...",72151,0.0
...,...,...,...,...
3229,Perry,"POLYGON ((-77.02920 40.38688, -77.02918 40.386...",42099,0.0
3230,Haskell,"POLYGON ((-95.22136 35.27282, -95.22103 35.273...",40061,0.0
3231,Will,"POLYGON ((-88.25535 41.55009, -88.25539 41.550...",17197,0.0
3232,Lincoln,"POLYGON ((-97.14113 35.60848, -97.14119 35.609...",40081,0.0
3233,Geauga,"POLYGON ((-81.39113 41.46705, -81.39113 41.467...",39055,0.0

In [14]:
county_df=merged_df.dropna()
county_df.head()

,NAME,geometry,fips,PM10 above threshold
0,Comerío,"POLYGON ((-66.25713 18.24744, -66.25695 18.247...",72045,0.0
1,Aibonito,"POLYGON ((-66.25753 18.07588, -66.25937 18.077...",72009,0.0
2,Ciales,"POLYGON ((-66.55771 18.27506, -66.55782 18.275...",72039,0.0
3,Aguada,"POLYGON ((-67.16355 18.41748, -67.16190 18.416...",72003,0.0
4,Yabucoa,"POLYGON ((-65.87885 18.02066, -65.87926 18.020...",72151,0.0

In [15]:
## convert into pandas dataframe without the geometry column
pd.options.display.float_format = '{:.15f}'.format ## see 15 decimal places of the numbers
county_var=pd.DataFrame(county_df.drop(columns='geometry')) 
county_var

          NAME   fips  PM10 above threshold
0      Comerío  72045     0.000000000000000
1     Aibonito  72009     0.000000000000000
2       Ciales  72039     0.000000000000000
3       Aguada  72003     0.000000000000000
4      Yabucoa  72151     0.000000000000000
...        ...    ...                   ...
3229     Perry  42099     0.000000000000000
3230   Haskell  40061     0.000000000000000
3231      Will  17197     0.000000000000000
3232   Lincoln  40081     0.000000000000000
3233    Geauga  39055     0.000000000000000

[3234 rows x 3 columns]

In [16]:
county_var.to_pickle('PM10_above_threshold.pkl')