#### Notebook to feature engineer fraction of time temperature was below 25th percentile

In [1]:
## conda environment Weather_Prediction

import os
import numpy as np
import pandas as pd
import geopandas as gpd
import xarray as xr
pd.set_option('display.max_columns', None)
pd.set_option('display.precision', 15)

In [2]:
PATH_1=os.path.join('..','..','..','..','Weather_Data','CAMS','2012','2012_multi_level_26_variables.nc')
ml_26_variables = xr.open_dataset(PATH_1) ## multilevel 26 variables
ml_26_variables = ml_26_variables.squeeze(dim="model_level") ## remove the model_level dimension
ml_26_variables=ml_26_variables.drop_vars('model_level') ## the dropped dimension becomes a column, so remove that
ml_26_variables['longitude'] = ml_26_variables['longitude']-360 ## necessary because of longitude data in multi-level case
temp=ml_26_variables['t'] ## get only the temperature variable
temp

<xarray.DataArray 't' (valid_time: 2928, latitude: 34, longitude: 78)> Size: 31MB
[7765056 values with dtype=float32]
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 23kB 2012-01-01 ... 2012-12-31T21...
  * latitude    (latitude) float64 272B 49.25 48.5 47.75 ... 26.0 25.25 24.5
  * longitude   (longitude) float64 624B -124.8 -124.1 -123.3 ... -67.85 -67.1
Attributes: (12/31)
    GRIB_paramId:                             130
    GRIB_dataType:                            an
    GRIB_numberOfPoints:                      2652
    GRIB_typeOfLevel:                         hybrid
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_pv:                                  [0.00000000e+00 2.00000000e+01 ...
    GRIB_shortName:                           t
    GRIB_units:                               K
    long_name:                                Temperature
    units:                                    K
    standard_name:                            air_temperature

In [3]:
temp.to_dataframe()

                                                                    t
valid_time          latitude longitude
2012-01-01 00:00:00 49.25    -124.849999999999994  275.70001220703125
                             -124.099999999999994  275.41973876953125
                             -123.349999999999994  274.96954345703125
                             -122.599999999999994  273.20001220703125
                             -121.849999999999994  269.85235595703125
...                                                               ...
2012-12-31 21:00:00 24.50    -70.100000000000023   293.68664550781250
                             -69.350000000000023   293.60656738281250
                             -68.600000000000023   293.56750488281250
                             -67.850000000000023   293.55480957031250
                             -67.100000000000023   293.58996582031250

[7765056 rows x 1 columns]

In [4]:
PATH_2=os.path.join('..','CAMS_79_variables_2012.pkl')
get_data = pd.read_pickle(PATH_2) ## load the data with all variables
get_data.head()

,NAME,fips,u10,v10,d2m,t2m,bcaod550,duaod550,lsm,msl,omaod550,pm1,pm2p5,pm10,ssaod550,suaod550,z,sp,aod469,aod550,aod670,aod865,aod1240,tcco,tc_c2h6,tchcho,tc_h2o2,tc_oh,tc_c5h8,tc_ch4,tc_hno3,tcno2,tc_no,gtco3,tc_pan,tc_c3h8,tcso2,tcwv,co,aermr04,aermr05,aermr06,c2h6,hcho,h2o2,aermr09,aermr07,aermr10,aermr08,oh,c5h8,hno3,no2,no,go3,pan,c3h8,aermr01,aermr02,aermr03,q,aermr11,so2,t,lai_hv,lai_lv,asn,sd,tcw,aermssdus,aermssdum,aermssdul,aermssbchphil,aermssomhphil,aermssbchphob,aermssomhphob,aermsssss,aermssssm,aermssssl,aermsssu,aermssso2
1748,Autauga,1001,0.064634813162156,0.172399894091909,285.513501463962257,292.554171566943808,0.007229633205111,0.011406505242057,0.986497734585937,101758.939673815431888,0.078036124869926,0.000000010506578,0.000000013811044,0.000000018926162,0.009656695585845,0.074252594553515,1225.350570704614029,100277.673819511284819,0.219283782966464,0.180581673100591,0.139664418328063,0.098344398697557,0.057882036108778,0.000888759984775,0.000003475321995,0.000004475851538,0.000009273222875,0.000000004873831,0.00000418936144,0.009934445158332,0.000005376097492,0.000003065955259,0.000000431587387,0.006309977651718,0.000009585101972,0.000000609305017,0.000002841800995,26.248812777625776,0.00000017373257,0.000000000717625,0.000000001238601,0.000000000428633,0.000000000573758,0.000000004288932,0.000000000874546,0.00000000020075,0.000000006869994,0.000000000189237,0.000000003509371,0.000000000000021,0.000000023273271,0.000000000877117,0.000000007458536,0.000000000471289,0.000000059542709,0.000000003294238,0.000000000233207,0.000000000027354,0.000000002212875,0.00000000027555,0.00984931252565,0.000000002546964,0.000000005578397,292.354466060505786,3.877203761588099,2.677350857845567,0.879906924141229,0.007581993605669,26.352698500649648,0.000002239089103,0.000004448217628,0.000003546408426,0.000000119193803,0.000002142938211,0.000000647212229,0.000013780474278,0.0000002431174,0.000019765499111,0.000001204163474,0.000008174877399,0.000001622519676
2845,Baldwin,1003,-0.210732758719659,0.334346061448856,288.958325215247498,293.66149409807042,0.007093468324236,0.014240288671171,0.625803026729053,101740.052225065155653,0.072943186273547,0.000000008866853,0.000000012741315,0.000000017486837,0.014832435468044,0.073940332455206,272.665501952284444,101409.374723481028923,0.220345802519998,0.183049641101029,0.143618441448382,0.103949733890485,0.064277765999241,0.000865354451735,0.000003393813255,0.000003562724688,0.000009863690159,0.000000004933693,0.000001953952032,0.010048808280672,0.00000534372927,0.000002679105863,0.000000407545467,0.006206748150849,0.000008391152769,0.000000563183872,0.000002226781841,29.374750339394847,0.000000152236898,0.000000000909202,0.000000001514345,0.000000000491649,0.000000000535917,0.000000002789546,0.000000000893497,0.000000000184328,0.00000000542757,0.000000000194006,0.000000002707611,0.00000000000003,0.000000010524301,0.000000000992272,0.000000005769044,0.000000000317591,0.000000062382889,0.000000002403146,0.000000000204042,0.000000000072939,0.000000006026077,0.00000000316529,0.011945430561241,0.000000002076845,0.000000003314428,293.585185446492119,3.411881699344627,2.187440878862613,0.880001717061968,0.004854835917758,29.487872023430828,0.000002787334206,0.000005581301551,0.00000444020562,0.000000116049843,0.000001789080317,0.000000636276216,0.000013037083433,0.000000341859329,0.000027938679006,0.00000313766114,0.000008165020786,0.000001013448658
1439,Barbour,1005,0.09710873049905,0.145431625644046,285.695066653863478,292.914944402317929,0.007025660498198,0.011077222883694,0.987905769603974,101764.617154517167364,0.073907502055795,0.000000010188715,0.000000013448016,0.000000018391956,0.010691097167472,0.068148464718164,1256.402743839678351,100246.67544251254003,0.206956770996652,0.17084978059076,0.132679218165438,0.094127292900448,0.056214931879401,0.000877172816705,0.000003435868964,0.000004296276204,0.00000920896376,0.000000004876972,0.000003723566573,0.009931044123661,0.000005080429337,0.000002777844392,0.000000410598418,0.006272923318558,0.000009284996189,0.000000593533473,0.000002206730731,27.002472683059388,0.000000172667508,0.000000000705865,0.000000001220277,0.000000000424708,0.000000000583398,0.000000003914749,0.000000000881963,0.000000000219574,0.00000000671251,0.000000000274056,0.000000003611073,0.000000000000021,0.000000019143339,0.000000000810197,0.000000005762455,0.00000000025163,0.000000058954508,0.000000002975422,0.000000000222518,0.000000000031519,0.000000002556053,0.00000000038652,0.010056666208473,0.000000001975968,0.00000000206777,292.729487927762079,4.036021445949966,2.504478864589482,0.879993127774135,0.005560464014753,27.109887120813642,0.00000218080535,0.0000043352129,0.000003399755328,0.000000130543707,0.000002070364711,0.000000614224304,0.000012907504478,0.000000264976017,0.00002158024592,0.000001459277706,0.00000749100234,0.000001049322626
1429,Bibb,1007,0.070924115000863,0.202234240448571,285.539025320298663,292.150932076858453,0.007251515472199,0.011191574820085,0.987537243234926,101757.718522217925056,0.078939181860179,0.000000010303034,0.000000013531673,0.000000018533191,0.009117438833452,0.075027105129653,1220.928527623458876,100280.320409947060398,0.220644029701642,0.181526788273531,0.140167859883376,0.098382987320146,0.057562355450401,0.000893858117159,0.000003494553678,0.000004422054197,0.000009203433122,0.000000004875902,0.00000406858184,0.009934627414826,0.000005493606531,0.000003251899366,0.000000448405345,0.006330377314179,0.000009632236663,0.000000617703698,0.000002880166345,25.931264586133253,0.000000174291813,0.000000000711649,0.000000001218014,0.000000000410247,0.000000000567922,0.000000004260157,0.000000000844782,0.000000000193639,0.000000006741661,0.000000000164776,0.000000003335892,0.000000000000021,0.000000023909371,0.000000000909897,0.000000008788812,0.000000000694757,0.000000058176541,0.000000003300346,0.000000000238861,0.000000000024994,0.00000000202057,0.000000000227281,0.009858634530612,0.000000002621098,0.00000000562433,291.991149591093915,3.704579375173288,2.781650628119325,0.879774337621914,0.010019918757302,26.035520120817019,0.000002192532253,0.000004353905464,0.000003523249978,0.000000115624575,0.000002157293046,0.000000653125464,0.000013962206189,0.000000231545339,0.000018812518487,0.000001072996336,0.000008244159397,0.000001656534615
1466,Blount,1009,0.148850510713362,0.244205155568542,284.972011302653073,291.345408229960526,0.007077797792573,0.009757205146796,0.980500303262546,101770.881935573299415,0.078041882964406,0.000000010360032,0.000000013372228,0.000000018399244,0.008013309824438,0.075687291859497,1957.980677294532143,99406.524345830373932,0.217523249873145,0.178577392479601,0.137346876961817,0.095585162247393,0.055091200621258,0.000892331446567,0.000003495766453,0.000004178691548,0.000008814252102,0.000000004884442,0.000003121755397,0.009844728056813,0.00000552232666,0.000003507384127,0.000000472001182,0.006368284165517,0.000009847377923,0.000000633511201,0.000003265401712,24.687779898570898,0.000000178450763,0.000000000613202,0.000000001053454,0.000000000361094,0.000000000584538,0.0000000038192,0.000000000793215,0.000000000188176,0.000000006760658,0.000000000159939,0.000000003395354,0.000000000000024,0.000000019930062,0.000000000973939,0.000000010440495,0.000000000966301,0.000000057604526,0.000000003147979,0.000000000283724,0.000000000021015,0.000000001700201,0.00000000016846,0.0095656548081,0.000000002885672,0.000000007596756,291.027239086309692,3.341645737097007,2.774901935459976,0.879580477236193,0.012208553789454,24.791398421863509,0.000001903288898,0.000003786191466,0.000003142138992,0.000000114659957,0.000002182317105,0.000000635660568,0.000013663154761,0.00000020582716,0.000016706949429,0.000000832778298,0.00000819208883,0.000002080739236

In [5]:
percentile_75 = get_data['t'].quantile(0.25) ## get temperature data
print(percentile_75)
threshold=percentile_75

284.40478859440356

In [6]:
SHAPE_PATH=os.path.join('..','..','..','..','Shapefiles','county_shapefiles','2011_county_shapefile','tl_2011_us_county.shp')
county_gdf = gpd.read_file(SHAPE_PATH)
county_gdf

,STATEFP,COUNTYFP,COUNTYNS,GEOID,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,CSAFP,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,72,045,01804502,72045,Comerío,Comerío Municipio,13,H1,G4020,490,41980,None,A,73557132,319735,+18.2250402,-066.2202984,"POLYGON ((-66.25713 18.24744, -66.25695 18.247..."
1,72,009,01804484,72009,Aibonito,Aibonito Municipio,13,H1,G4020,490,41980,None,A,81094444,71897,+18.1306472,-066.2639743,"POLYGON ((-66.25753 18.07588, -66.25937 18.077..."
2,72,039,01804499,72039,Ciales,Ciales Municipio,13,H1,G4020,490,41980,None,A,172309964,459615,+18.2912286,-066.5130169,"POLYGON ((-66.55771 18.27506, -66.55782 18.275..."
3,72,003,01804481,72003,Aguada,Aguada Municipio,13,H1,G4020,None,10380,None,A,79904253,38043835,+18.3756809,-067.1837074,"POLYGON ((-67.16355 18.41748, -67.16190 18.416..."
4,72,151,01804556,72151,Yabucoa,Yabucoa Municipio,13,H1,G4020,490,41980,None,A,143005203,72593008,+18.0598615,-065.8598555,"POLYGON ((-65.87885 18.02066, -65.87926 18.020..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3229,42,099,01213682,42099,Perry,Perry County,06,H1,G4020,276,25420,None,A,1428280078,10597982,+40.3977795,-077.2663284,"POLYGON ((-77.02920 40.38688, -77.02918 40.386..."
3230,40,061,01101818,40061,Haskell,Haskell County,06,H1,G4020,None,None,None,A,1493228577,126266671,+35.2322937,-095.1095776,"POLYGON ((-95.22136 35.27282, -95.22103 35.273..."
3231,17,197,01785190,17197,Will,Will County,06,H1,G4020,176,16980,16974,A,2167580642,31904479,+41.4484742,-087.9784564,"POLYGON ((-88.25535 41.55009, -88.25539 41.550..."
3232,40,081,01101828,40081,Lincoln,Lincoln County,06,H1,G4020,416,36420,None,A,2466481584,34614223,+35.7031175,-096.8813917,"POLYGON ((-97.14113 35.60848, -97.14119 35.609..."
3233,39,055,01074040,39055,Geauga,Geauga County,06,H1,G4020,184,17460,None,A,1036420277,21054492,+41.4993217,-081.1735054,"POLYGON ((-81.39113 41.46705, -81.39113 41.467..."

In [7]:
geometry_column=county_gdf['geometry']
lat_lon=geometry_column.get_coordinates(index_parts=True)
lat_lon

                            x                   y
0    0    -66.257125000000002  18.247439000000000
     1    -66.256954999999991  18.247450999999998
     2    -66.256174999999999  18.247370999999998
     3    -66.255698999999993  18.247496999999999
     4    -66.255297999999996  18.247540999999998
...                       ...                 ...
3233 1161 -81.391229999999993  41.463234000000000
     1162 -81.391228999999996  41.463273000000001
     1163 -81.391212999999993  41.463906000000001
     1164 -81.391134999999991  41.466968000000001
     1165 -81.391133999999994  41.467050999999998

[7394987 rows x 2 columns]

In [8]:
def single_county(var):
    
    ''' Function to interpolate the values in a single county by taking a 100 or less latitude and longitude pair.
        And then to find the fraction of time, PM2.5 was above EPA standard
        Args:
        --------
             var (int): The index of the county in the shapefile.

        Returns:
        --------
            pm_above_df: Dataframe consisting the values of the variables interpolated in the county.
    '''   
    
    
    longitude= lat_lon.loc[(var), 'x']  # get the longitude
    extract_val=len(longitude) ## find number of longitude that a shapfile has

    ## if number of longitude or latitude is less than 100, that many lat-lon pairs will be extracted, if not, a 100 values
    if extract_val < 100:
        extract_val=extract_val
    else:
        extract_val=100

    longitude=longitude[:extract_val]  ## extract first 100 values or values less than 100
    latitude=lat_lon.loc[(var),'y']    ## get the latitude values
    latitude=latitude[:extract_val]    ## extract first 100 values or values less than 100

    lat_list=latitude.tolist()
    lon_list=longitude.tolist()

    ## find the corresponding values of the variables in the finer grid

    year_avg_finer= temp.interp(longitude=lon_list, latitude=lat_list)
    
## get only the 100 (or less) pair of latitude and longitude from the lat and lon list from the 100,000 (or less) rows
    get_vals=[]

    for i in range(0, extract_val):
        row=year_avg_finer.isel(latitude=[i], longitude=[i])
        row_df=row.to_dataframe()
        get_vals.append(row_df)
    
    initial_df=pd.concat(get_vals)
    summary = initial_df.groupby("valid_time").mean(["latitude", "longitude"])
    df=summary

    total_rows=len(df)

    c=0
    for i in range(0, total_rows):
        if df['t'].values[i] < threshold:
            c=c+1

## convert number to a fraction
    frac_time=(c/total_rows)*100
    pm_above_df=pd.DataFrame({'Temp below percentile':[frac_time]})


    return pm_above_df

In [9]:
len(county_gdf)

3234

In [10]:
%%time

## get the values for all counties

df_list_below=[]

for i in range(0,len(county_gdf)): ## loop for the all list of counties
    try:
        df_list_below.append(single_county(i))
    except:
        pass

CPU times: total: 55min 17s
Wall time: 55min 59s

In [11]:
concatenate_df=pd.concat(df_list_below)
final_df=concatenate_df.reset_index(drop=True)
final_df

      Temp below percentile
0         0.000000000000000
1         0.000000000000000
2         0.000000000000000
3         0.000000000000000
4         0.000000000000000
...                     ...
3229     46.174863387978142
3230     24.419398907103826
3231     45.901639344262293
3232     26.229508196721312
3233     48.019125683060111

[3234 rows x 1 columns]

In [12]:
## lets first create a fips column in the original shape file

county_gdf['fips']=county_gdf['STATEFP'] + county_gdf['COUNTYFP']
county_gdf.dtypes
## convert the data type
county_gdf['fips']=county_gdf['fips'].astype(str).astype(int)
county_gdf.dtypes

county_gdf = county_gdf.drop(['STATEFP','COUNTYFP','COUNTYNS','GEOID','NAMELSAD','LSAD','CLASSFP','MTFCC'
                             ,'CSAFP','CBSAFP','METDIVFP','FUNCSTAT','ALAND','AWATER','INTPTLAT',
                             'INTPTLON'], axis=1)
county_gdf

          NAME                                           geometry   fips
0      Comerío  POLYGON ((-66.25713 18.24744, -66.25695 18.247...  72045
1     Aibonito  POLYGON ((-66.25753 18.07588, -66.25937 18.077...  72009
2       Ciales  POLYGON ((-66.55771 18.27506, -66.55782 18.275...  72039
3       Aguada  POLYGON ((-67.16355 18.41748, -67.16190 18.416...  72003
4      Yabucoa  POLYGON ((-65.87885 18.02066, -65.87926 18.020...  72151
...        ...                                                ...    ...
3229     Perry  POLYGON ((-77.02920 40.38688, -77.02918 40.386...  42099
3230   Haskell  POLYGON ((-95.22136 35.27282, -95.22103 35.273...  40061
3231      Will  POLYGON ((-88.25535 41.55009, -88.25539 41.550...  17197
3232   Lincoln  POLYGON ((-97.14113 35.60848, -97.14119 35.609...  40081
3233    Geauga  POLYGON ((-81.39113 41.46705, -81.39113 41.467...  39055

[3234 rows x 3 columns]

In [13]:
merged_df=pd.merge(county_gdf, final_df, left_index=True, right_index=True)
merged_df

,NAME,geometry,fips,Temp below percentile
0,Comerío,"POLYGON ((-66.25713 18.24744, -66.25695 18.247...",72045,0.000000000000000
1,Aibonito,"POLYGON ((-66.25753 18.07588, -66.25937 18.077...",72009,0.000000000000000
2,Ciales,"POLYGON ((-66.55771 18.27506, -66.55782 18.275...",72039,0.000000000000000
3,Aguada,"POLYGON ((-67.16355 18.41748, -67.16190 18.416...",72003,0.000000000000000
4,Yabucoa,"POLYGON ((-65.87885 18.02066, -65.87926 18.020...",72151,0.000000000000000
...,...,...,...,...
3229,Perry,"POLYGON ((-77.02920 40.38688, -77.02918 40.386...",42099,46.174863387978142
3230,Haskell,"POLYGON ((-95.22136 35.27282, -95.22103 35.273...",40061,24.419398907103826
3231,Will,"POLYGON ((-88.25535 41.55009, -88.25539 41.550...",17197,45.901639344262293
3232,Lincoln,"POLYGON ((-97.14113 35.60848, -97.14119 35.609...",40081,26.229508196721312
3233,Geauga,"POLYGON ((-81.39113 41.46705, -81.39113 41.467...",39055,48.019125683060111

In [14]:
county_df=merged_df.dropna()
county_df.head()

,NAME,geometry,fips,Temp below percentile
0,Comerío,"POLYGON ((-66.25713 18.24744, -66.25695 18.247...",72045,0.0
1,Aibonito,"POLYGON ((-66.25753 18.07588, -66.25937 18.077...",72009,0.0
2,Ciales,"POLYGON ((-66.55771 18.27506, -66.55782 18.275...",72039,0.0
3,Aguada,"POLYGON ((-67.16355 18.41748, -67.16190 18.416...",72003,0.0
4,Yabucoa,"POLYGON ((-65.87885 18.02066, -65.87926 18.020...",72151,0.0

In [15]:
## convert into pandas dataframe without the geometry column
pd.options.display.float_format = '{:.15f}'.format ## see 15 decimal places of the numbers
county_var=pd.DataFrame(county_df.drop(columns='geometry')) 
county_var

          NAME   fips  Temp below percentile
0      Comerío  72045      0.000000000000000
1     Aibonito  72009      0.000000000000000
2       Ciales  72039      0.000000000000000
3       Aguada  72003      0.000000000000000
4      Yabucoa  72151      0.000000000000000
...        ...    ...                    ...
3229     Perry  42099     46.174863387978142
3230   Haskell  40061     24.419398907103826
3231      Will  17197     45.901639344262293
3232   Lincoln  40081     26.229508196721312
3233    Geauga  39055     48.019125683060111

[3234 rows x 3 columns]

In [16]:
county_var.to_pickle('temp_below_percentile.pkl')