#### Notebook to feature engineer fraction of time PM1 was above 75th percentile

In [1]:
## conda environment Weather_Prediction

import os
import numpy as np
import pandas as pd
import geopandas as gpd
import xarray as xr
pd.set_option('display.max_columns', None)
pd.set_option('display.precision', 15)

In [2]:
PATH_1=os.path.join('..','..','..','..','Weather_Data','CAMS','2006','2006_single_level_34_variables.nc')
sl_34_variables = xr.open_dataset(PATH_1) ## single level 34 variables
pm1=sl_34_variables['pm1'] ## get only pm1 variable
pm1

<xarray.DataArray 'pm1' (valid_time: 2920, latitude: 34, longitude: 78)> Size: 31MB
[7743840 values with dtype=float32]
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 23kB 2006-01-01 ... 2006-12-31T21...
  * latitude    (latitude) float64 272B 49.25 48.5 47.75 ... 26.0 25.25 24.5
  * longitude   (longitude) float64 624B -124.8 -124.1 -123.3 ... -67.85 -67.1
Attributes: (12/33)
    GRIB_paramId:                             210072
    GRIB_dataType:                            an
    GRIB_numberOfPoints:                      2652
    GRIB_typeOfLevel:                         surface
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_units:                               kg m**-3
    long_name:                                Particulate matter d <= 1 um
    units:                                    kg m**-3
    standard_name:                            mass_concentration_of_pm1_ambie...
    GRIB_number:                              0
    GRIB_surface:                             0.0

In [3]:
pm1.to_dataframe()

                                                                 pm1
valid_time          latitude longitude
2006-01-01 00:00:00 49.25    -124.849999999999994  0.000000005273644
                             -124.099999999999994  0.000000009949853
                             -123.349999999999994  0.000000016820234
                             -122.599999999999994  0.000000014187012
                             -121.849999999999994  0.000000006381146
...                                                              ...
2006-12-31 21:00:00 24.50    -70.099999999999994   0.000000000659298
                             -69.349999999999994   0.000000000609454
                             -68.599999999999994   0.000000000542229
                             -67.849999999999994   0.000000000482368
                             -67.099999999999994   0.000000000438600

[7743840 rows x 1 columns]

In [4]:
PATH_1=os.path.join('..','CAMS_79_variables_2006.pkl')
get_data = pd.read_pickle(PATH_1) ## load the data with all variables
get_data.head()

,NAME,fips,u10,v10,d2m,t2m,bcaod550,duaod550,lsm,msl,omaod550,pm1,pm2p5,pm10,ssaod550,suaod550,z,sp,aod469,aod550,aod670,aod865,aod1240,tcco,tc_c2h6,tchcho,tc_h2o2,tc_oh,tc_c5h8,tc_ch4,tc_hno3,tcno2,tc_no,gtco3,tc_pan,tc_c3h8,tcso2,tcwv,co,aermr04,aermr05,aermr06,c2h6,hcho,h2o2,aermr09,aermr07,aermr10,aermr08,oh,c5h8,hno3,no2,no,go3,pan,c3h8,aermr01,aermr02,aermr03,q,aermr11,so2,t,lai_hv,lai_lv,asn,sd,tcw,aermssdus,aermssdum,aermssdul,aermssbchphil,aermssomhphil,aermssbchphob,aermssomhphob,aermsssss,aermssssm,aermssssl,aermsssu,aermssso2
1536,Autauga,1001,0.210047468506641,0.123385897340788,283.949377262439214,292.114536887409429,0.00851973222729,0.009542208816439,0.986464531564209,101770.709572945721447,0.098791946968075,0.000000014179909,0.000000017869096,0.000000024747516,0.008882410725671,0.104069724601322,1368.670051439976305,100115.094837177690351,0.281749788861147,0.229805933789892,0.174930914100779,0.119484558723294,0.066764036924051,0.000937051117396,0.000003640964285,0.000005115930851,0.000009465348351,0.000000004811513,0.000004620941846,0.009819872916577,0.000005818471279,0.000003519283051,0.000000440763373,0.00632602927812,0.000010557776336,0.000000687100539,0.00000437990735,25.067602811941406,0.000000200849233,0.000000000612567,0.000000001068655,0.000000000351682,0.000000000649788,0.00000000487623,0.000000000961654,0.000000000261121,0.000000009408011,0.000000000270735,0.000000004814023,0.000000000000022,0.000000025040761,0.000000001125761,0.000000008336818,0.000000000603008,0.000000065146738,0.000000003959071,0.000000000281205,0.000000000026099,0.000000002113125,0.000000000319285,0.009087116556219,0.000000003839943,0.000000007754716,292.065369060838805,3.904460199286052,2.618741604547198,0.879888048566865,0.00007040870922,25.135250769035675,0.000001896481128,0.000003767403808,0.000002711982152,0.000000164421196,0.000003050184712,0.000000736943795,0.000017306710798,0.000000228948257,0.000018615193892,0.000001115778792,0.000011942381564,0.000002526960692
441,Baldwin,1003,-0.207111961205487,0.381928357331876,288.578829481557875,293.494987710311932,0.007893513918585,0.011877776890095,0.422456727373741,101754.556463998684194,0.080457455938472,0.000000009607858,0.000000013484384,0.00000001890659,0.013309800468087,0.090809278297525,170.454787516937728,101547.582713373820297,0.248484031002264,0.204347748890448,0.157780866777318,0.111006614385978,0.065719276911641,0.000896458974701,0.000003538491119,0.000003483062297,0.000010347184793,0.000000004888711,0.000001393584708,0.009961177844531,0.000006012467398,0.000002781274451,0.000000385269756,0.006180344878703,0.000008267263914,0.000000620219686,0.000003168236452,28.003454839086981,0.000000164180412,0.000000000704567,0.000000001205794,0.000000000446502,0.000000000573421,0.000000002435285,0.000000001021362,0.000000000191089,0.000000005891704,0.00000000018093,0.000000002705477,0.000000000000038,0.000000006732054,0.000000001384068,0.000000005461807,0.000000000304292,0.000000070758661,0.000000002515718,0.000000000227695,0.000000000089844,0.000000007473568,0.000000004845618,0.011821505960439,0.00000000298174,0.000000004022051,293.727269373045544,2.493748263318578,1.556460793604144,0.879992840120809,0.000159828659051,28.015730211352064,0.000002306767308,0.000004718852329,0.000003622891304,0.000000140755632,0.000002138688376,0.000000694735386,0.000014603570163,0.000000332793449,0.000027235271824,0.00000318536081,0.000010801190676,0.000001407014703
2221,Barbour,1005,0.288308646254696,0.082507869749353,284.221876617777866,292.332943913591691,0.008459369170384,0.009338806640861,0.986926074501393,101772.729666609913693,0.096727356071791,0.000000013774068,0.000000017441019,0.00000002412058,0.009508076500904,0.097908731294258,1263.685437879796154,100244.62612476493814,0.271738174862865,0.221942587213575,0.169330571326487,0.116135033501507,0.065428778260663,0.000932949592985,0.000003628244435,0.000004989123859,0.000009452932675,0.000000004807296,0.000004734806831,0.009833856727654,0.000005747994732,0.00000318805051,0.000000419862612,0.006298556005403,0.000010245418549,0.000000675771147,0.000003393221713,25.570698764540353,0.000000201238224,0.000000000622421,0.000000001089042,0.000000000356242,0.000000000655645,0.000000004675721,0.000000000962515,0.000000000264186,0.000000009331175,0.000000000295714,0.000000004898475,0.000000000000022,0.000000025784572,0.000000001056441,0.000000006571349,0.000000000368202,0.000000062040005,0.00000000368266,0.00000000026825,0.000000000028516,0.000000002307585,0.000000000361913,0.009378274937748,0.000000003143771,0.00000000290447,292.436785570034431,4.174570187840095,2.367511530630567,0.879954108264943,0.000043751905364,25.622068662072078,0.000001863030676,0.0000037043752,0.000002586163731,0.000000170435871,0.000003036587372,0.000000724515806,0.000016788637021,0.000000244071754,0.000019861083212,0.000001270301935,0.00001114718037,0.000001630493532
2388,Bibb,1007,0.193651237891773,0.16084793884593,283.871042144035357,291.510129508885598,0.008348259820438,0.009254724074296,0.986427446209294,101770.090300961950561,0.098745183209383,0.000000014404945,0.00000001802359,0.000000025021737,0.008076706807995,0.106208385868209,1465.598787847873382,99995.279724330728641,0.283159612611315,0.230633289775798,0.175155519979483,0.119115749298021,0.066017347716166,0.00094147210233,0.000003661327695,0.000004964961936,0.000009300675541,0.000000004819371,0.00000413973812,0.009807159784439,0.00000598861092,0.00000401216013,0.000000485821602,0.006366659788871,0.000010608562986,0.000000703069927,0.000005098739231,24.421778736613327,0.000000202266913,0.000000000577976,0.000000000995214,0.000000000320309,0.000000000648605,0.00000000463187,0.000000000917313,0.000000000243062,0.000000009441062,0.000000000217149,0.000000004766478,0.000000000000024,0.000000023318867,0.000000001202419,0.00000001103957,0.000000001107723,0.000000062939145,0.000000003867921,0.000000000302824,0.000000000022344,0.00000000180718,0.000000000247475,0.008917736354099,0.000000004352485,0.000000011104489,291.403624752458256,3.638957935933739,2.754823872966046,0.879774093064269,0.000092931362996,24.501005033948516,0.000001829755931,0.000003628993206,0.000002743729358,0.000000152666753,0.000003107280579,0.00000073077551,0.000017407176792,0.000000210759641,0.000017117253928,0.000000934749835,0.000012275839158,0.000003185859009
2153,Blount,1009,0.245932881671878,0.213296015392496,283.542886195556662,290.734878557177808,0.008212726638089,0.008485518369924,0.979014066638673,101778.388231996446848,0.098820598799373,0.000000014433505,0.000000017895324,0.000000024902497,0.007334576529023,0.107367319738281,2029.708085049063129,99322.769209719277569,0.282927224474757,0.230220465970017,0.174501715629252,0.118125767549103,0.064878379358193,0.000940289306713,0.000003660717498,0.000004604779032,0.000008977604643,0.000000004828851,0.000003073643524,0.009738597722297,0.000006106493935,0.000004260479004,0.000000508891184,0.006410315396785,0.000010671097924,0.000000717492805,0.00000526726123,23.465618989564522,0.000000206796313,0.000000000516943,0.000000000879747,0.00000000028407,0.000000000658678,0.00000000407351,0.00000000087002,0.000000000237644,0.000000009496439,0.000000000202185,0.000000004788274,0.000000000000026,0.000000018548405,0.000000001273021,0.000000012047511,0.000000001277682,0.000000062345261,0.00000000367658,0.000000000336627,0.000000000019025,0.0000000015383,0.000000000191631,0.008746191216085,0.000000004538517,0.000000011356699,290.454607505323224,3.286418753252266,2.78269651469914,0.879259909460572,0.000955579741799,23.552124904982751,0.000001670162248,0.000003306024431,0.000002620347116,0.000000148303174,0.000003141957767,0.000000720805624,0.000017266896278,0.000000192242587,0.000015599003404,0.000000793022651,0.000012218486719,0.000003396631417

In [5]:
percentile_75 = get_data['pm1'].quantile(0.75)
threshold=percentile_75
print(threshold)

1.4606010980266628e-08

In [6]:
## use county shapefile from 2008 as the shapefile before 2008 could not be found
SHAPE_PATH=os.path.join('..','..','..','..','Shapefiles','county_shapefiles','2008_county_shapefile','tl_2008_us_county.shp')
county_gdf = gpd.read_file(SHAPE_PATH)
county_gdf

,STATEFP,COUNTYFP,COUNTYNS,CNTYIDFP,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,CSAFP,CBSAFP,METDIVFP,FUNCSTAT,geometry
0,19,175,00465276,19175,Union,Union County,06,H1,G4020,None,None,None,A,"POLYGON ((-94.47051 40.97504, -94.47050 40.975..."
1,19,177,00465277,19177,Van Buren,Van Buren County,06,H1,G4020,None,None,None,A,"POLYGON ((-91.96059 40.90070, -91.95925 40.900..."
2,20,097,00485013,20097,Kiowa,Kiowa County,06,H1,G4020,None,None,None,A,"POLYGON ((-99.01471 37.67895, -99.01473 37.678..."
3,20,109,00485019,20109,Logan,Logan County,06,H1,G4020,None,None,None,A,"POLYGON ((-100.89562 39.13329, -100.89404 39.1..."
4,20,003,00484971,20003,Anderson,Anderson County,06,H1,G4020,None,None,None,A,"POLYGON ((-95.51741 38.20619, -95.51741 38.206..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3228,35,015,00936829,35015,Eddy,Eddy County,06,H1,G4020,None,16100,None,A,"POLYGON ((-104.09554 32.00000, -104.09586 32.0..."
3229,40,015,01101795,40015,Caddo,Caddo County,06,H1,G4020,None,None,None,A,"POLYGON ((-98.36984 35.55133, -98.36964 35.551..."
3230,40,025,01101800,40025,Cimarron,Cimarron County,06,H1,G4020,None,None,None,A,"POLYGON ((-102.14252 36.50032, -102.14380 36.5..."
3231,40,069,01101822,40069,Johnston,Johnston County,06,H1,G4020,None,None,None,A,"POLYGON ((-96.74415 34.17223, -96.74416 34.172..."
3232,39,061,01074043,39061,Hamilton,Hamilton County,06,H1,G4020,178,17140,None,A,"POLYGON ((-84.27514 39.28921, -84.27467 39.289..."

In [7]:
geometry_column=county_gdf['geometry']
geometry_column
lat_lon=geometry_column.get_coordinates(index_parts=True)
lat_lon

                            x                   y
0    0    -94.470506000000000  40.975042999999999
     1    -94.470500999999999  40.975550999999996
     2    -94.470511999999999  40.978164000000000
     3    -94.470497999999992  40.978803999999997
     4    -94.470501999999996  40.979332999999997
...                       ...                 ...
3232 3894 -84.275637000000003  39.289242000000002
     3895 -84.275549999999996  39.289235999999995
     3896 -84.275515999999996  39.289234000000000
     3897 -84.275508000000002  39.289232999999996
     3898 -84.275143000000000  39.289206999999998

[7781581 rows x 2 columns]

In [8]:
def single_county(var):
    
    ''' Function to interpolate the values in a single county by taking a 100 or less latitude and longitude pair.
        And then to find the fraction of time
        Args:
        --------
             var (int): The index of the county in the shapefile.

        Returns:
        --------
            pm_above_df: Dataframe consisting the values of the variables interpolated in the county.
    '''   
    
    
    longitude= lat_lon.loc[(var), 'x']  # get the longitude
    extract_val=len(longitude) ## find number of longitude that a shapfile has

    ## if number of longitude or latitude is less than 100, that many lat-lon pairs will be extracted, if not, a 100 values
    if extract_val < 100:
        extract_val=extract_val
    else:
        extract_val=100

    longitude=longitude[:extract_val]  ## extract first 100 values or values less than 100
    latitude=lat_lon.loc[(var),'y']    ## get the latitude values
    latitude=latitude[:extract_val]    ## extract first 100 values or values less than 100

    lat_list=latitude.tolist()
    lon_list=longitude.tolist()

    ## find the corresponding values of the variables in the finer grid

    year_avg_finer= pm1.interp(longitude=lon_list, latitude=lat_list)
    
## get only the 100 (or less) pair of latitude and longitude from the lat and lon list from the 100,000 (or less) rows
    get_vals=[]

    for i in range(0, extract_val):
        row=year_avg_finer.isel(latitude=[i], longitude=[i])
        row_df=row.to_dataframe()
        get_vals.append(row_df)
    
    initial_df=pd.concat(get_vals)
    summary = initial_df.groupby("valid_time").mean(["latitude", "longitude"])
    df=summary

    total_rows=len(df)

    c=0
    for i in range(0, total_rows):
        if df['pm1'].values[i] > threshold:
            c=c+1

## convert number to a fraction
    frac_time=(c/total_rows)*100
    pm_above_df=pd.DataFrame({'PM1 above percentile':[frac_time]})


    return pm_above_df

In [9]:
len(county_gdf)

3233

In [10]:
%%time

## get the values for all counties

df_list_below=[]

for i in range(0,len(county_gdf)): ## loop for the all list of counties
    try:
        df_list_below.append(single_county(i))
    except:
        pass

CPU times: total: 1h 6min 41s
Wall time: 1h 7min 38s

In [11]:
concatenate_df=pd.concat(df_list_below)
final_df=concatenate_df.reset_index(drop=True)
final_df

      PM1 above percentile
0       24.417808219178085
1       29.863013698630137
2        6.164383561643835
3        4.897260273972603
4       20.205479452054796
...                    ...
3228     2.945205479452055
3229     9.075342465753424
3230     3.938356164383562
3231    17.294520547945204
3232    58.732876712328761

[3233 rows x 1 columns]

In [12]:
## lets first create a fips column in the original shape file

county_gdf['fips']=county_gdf['STATEFP'] + county_gdf['COUNTYFP']
county_gdf.dtypes
## convert the data type
county_gdf['fips']=county_gdf['fips'].astype(str).astype(int)
county_gdf.dtypes

county_gdf = county_gdf.drop([ 'STATEFP','COUNTYFP','COUNTYNS','CNTYIDFP','NAMELSAD','LSAD','CLASSFP','MTFCC',
                                 'CSAFP','CBSAFP','METDIVFP','FUNCSTAT'], axis=1)
county_gdf

           NAME                                           geometry   fips
0         Union  POLYGON ((-94.47051 40.97504, -94.47050 40.975...  19175
1     Van Buren  POLYGON ((-91.96059 40.90070, -91.95925 40.900...  19177
2         Kiowa  POLYGON ((-99.01471 37.67895, -99.01473 37.678...  20097
3         Logan  POLYGON ((-100.89562 39.13329, -100.89404 39.1...  20109
4      Anderson  POLYGON ((-95.51741 38.20619, -95.51741 38.206...  20003
...         ...                                                ...    ...
3228       Eddy  POLYGON ((-104.09554 32.00000, -104.09586 32.0...  35015
3229      Caddo  POLYGON ((-98.36984 35.55133, -98.36964 35.551...  40015
3230   Cimarron  POLYGON ((-102.14252 36.50032, -102.14380 36.5...  40025
3231   Johnston  POLYGON ((-96.74415 34.17223, -96.74416 34.172...  40069
3232   Hamilton  POLYGON ((-84.27514 39.28921, -84.27467 39.289...  39061

[3233 rows x 3 columns]

In [13]:
merged_df=pd.merge(county_gdf, final_df, left_index=True, right_index=True)
merged_df

,NAME,geometry,fips,PM1 above percentile
0,Union,"POLYGON ((-94.47051 40.97504, -94.47050 40.975...",19175,24.417808219178085
1,Van Buren,"POLYGON ((-91.96059 40.90070, -91.95925 40.900...",19177,29.863013698630137
2,Kiowa,"POLYGON ((-99.01471 37.67895, -99.01473 37.678...",20097,6.164383561643835
3,Logan,"POLYGON ((-100.89562 39.13329, -100.89404 39.1...",20109,4.897260273972603
4,Anderson,"POLYGON ((-95.51741 38.20619, -95.51741 38.206...",20003,20.205479452054796
...,...,...,...,...
3228,Eddy,"POLYGON ((-104.09554 32.00000, -104.09586 32.0...",35015,2.945205479452055
3229,Caddo,"POLYGON ((-98.36984 35.55133, -98.36964 35.551...",40015,9.075342465753424
3230,Cimarron,"POLYGON ((-102.14252 36.50032, -102.14380 36.5...",40025,3.938356164383562
3231,Johnston,"POLYGON ((-96.74415 34.17223, -96.74416 34.172...",40069,17.294520547945204
3232,Hamilton,"POLYGON ((-84.27514 39.28921, -84.27467 39.289...",39061,58.732876712328761

In [14]:
county_df=merged_df.dropna()
county_df.head()

,NAME,geometry,fips,PM1 above percentile
0,Union,"POLYGON ((-94.47051 40.97504, -94.47050 40.975...",19175,24.417808219178085
1,Van Buren,"POLYGON ((-91.96059 40.90070, -91.95925 40.900...",19177,29.863013698630137
2,Kiowa,"POLYGON ((-99.01471 37.67895, -99.01473 37.678...",20097,6.164383561643835
3,Logan,"POLYGON ((-100.89562 39.13329, -100.89404 39.1...",20109,4.897260273972603
4,Anderson,"POLYGON ((-95.51741 38.20619, -95.51741 38.206...",20003,20.205479452054796

In [15]:
## convert into pandas dataframe without the geometry column
pd.options.display.float_format = '{:.15f}'.format ## see 15 decimal places of the numbers
county_var=pd.DataFrame(county_df.drop(columns='geometry')) 
county_var

           NAME   fips  PM1 above percentile
0         Union  19175    24.417808219178085
1     Van Buren  19177    29.863013698630137
2         Kiowa  20097     6.164383561643835
3         Logan  20109     4.897260273972603
4      Anderson  20003    20.205479452054796
...         ...    ...                   ...
3228       Eddy  35015     2.945205479452055
3229      Caddo  40015     9.075342465753424
3230   Cimarron  40025     3.938356164383562
3231   Johnston  40069    17.294520547945204
3232   Hamilton  39061    58.732876712328761

[3233 rows x 3 columns]

In [16]:
county_var.to_pickle('PM1_above_percentile.pkl')