#### Notebook to feature engineer fraction of time PM2.5 was above 75th percentile

In [1]:
## conda environment Weather_Prediction

import os
import numpy as np
import pandas as pd
import geopandas as gpd
import xarray as xr
pd.set_option('display.max_columns', None)
pd.set_option('display.precision', 15)

In [2]:
PATH_1=os.path.join('..','..','..','..','Weather_Data','CAMS','2013','2013_single_level_34_variables.nc')
sl_34_variables = xr.open_dataset(PATH_1) ## single level 34 variables
pm2_5=sl_34_variables['pm2p5'] ## get only pm2.5 variable
pm2_5

<xarray.DataArray 'pm2p5' (valid_time: 2920, latitude: 34, longitude: 78)> Size: 31MB
[7743840 values with dtype=float32]
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 23kB 2013-01-01 ... 2013-12-31T21...
  * latitude    (latitude) float64 272B 49.25 48.5 47.75 ... 26.0 25.25 24.5
  * longitude   (longitude) float64 624B -124.8 -124.1 -123.3 ... -67.85 -67.1
Attributes: (12/33)
    GRIB_paramId:                             210073
    GRIB_dataType:                            an
    GRIB_numberOfPoints:                      2652
    GRIB_typeOfLevel:                         surface
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_units:                               kg m**-3
    long_name:                                Particulate matter d <= 2.5 um
    units:                                    kg m**-3
    standard_name:                            mass_concentration_of_pm2p5_amb...
    GRIB_number:                              0
    GRIB_surface:                             0.0

In [3]:
pm2_5.to_dataframe()

                                                               pm2p5
valid_time          latitude longitude
2013-01-01 00:00:00 49.25    -124.849999999999994  0.000000000544033
                             -124.099999999999994  0.000000002306491
                             -123.349999999999994  0.000000005696207
                             -122.599999999999994  0.000000005721946
                             -121.849999999999994  0.000000004011410
...                                                              ...
2013-12-31 21:00:00 24.50    -70.099999999999994   0.000000002408640
                             -69.349999999999994   0.000000002266598
                             -68.599999999999994   0.000000002028001
                             -67.849999999999994   0.000000001808969
                             -67.099999999999994   0.000000001759547

[7743840 rows x 1 columns]

In [4]:
PATH_1=os.path.join('..','CAMS_79_variables_2013.pkl')
get_data = pd.read_pickle(PATH_1) ## load the data with all variables
get_data.head()

,NAME,fips,u10,v10,d2m,t2m,bcaod550,duaod550,lsm,msl,omaod550,pm1,pm2p5,pm10,ssaod550,suaod550,z,sp,aod469,aod550,aod670,aod865,aod1240,tcco,tc_c2h6,tchcho,tc_h2o2,tc_oh,tc_c5h8,tc_ch4,tc_hno3,tcno2,tc_no,gtco3,tc_pan,tc_c3h8,tcso2,tcwv,co,aermr04,aermr05,aermr06,c2h6,hcho,h2o2,aermr09,aermr07,aermr10,aermr08,oh,c5h8,hno3,no2,no,go3,pan,c3h8,aermr01,aermr02,aermr03,q,aermr11,so2,t,lai_hv,lai_lv,asn,sd,tcw,aermssdus,aermssdum,aermssdul,aermssbchphil,aermssomhphil,aermssbchphob,aermssomhphob,aermsssss,aermssssm,aermssssl,aermsssu,aermssso2
0,Autauga,1001,-0.245622537221334,0.071159187959857,284.910005089032211,291.182064540634315,0.006305822257257,0.010566229172084,0.987013964046399,101866.847522281575948,0.072771623471116,0.000000009702004,0.000000012940081,0.000000017749584,0.01097808366649,0.073444777468556,1310.666826870668956,100274.189993930238415,0.21051887564945,0.174066628303705,0.135317247275209,0.095924498405521,0.057153278674993,0.000845367671666,0.000003241687502,0.000003812225776,0.000008397017599,0.00000000488602,0.000003235791624,0.009945190815352,0.00000448251515,0.000002916904612,0.000000427351536,0.00626073235118,0.000008420641004,0.000000597790022,0.000002624052961,26.907374062734874,0.0000001649062,0.000000000709842,0.000000001249829,0.000000000510312,0.000000000538542,0.000000003501525,0.000000000739778,0.000000000181734,0.000000006216833,0.000000000184036,0.000000003241284,0.00000000000002,0.000000017136887,0.000000000807742,0.000000006414622,0.000000000423867,0.000000057157181,0.000000002750023,0.000000000232277,0.000000000031017,0.000000002509669,0.000000000329563,0.009755806494418,0.000000002317012,0.000000005082,290.815107265578547,3.906944745772017,2.626067656367741,0.879782953665777,0.000033797716697,27.033217272317529,0.000002041879853,0.000004113013881,0.000003607717539,0.000000126090934,0.000002239020712,0.000000542336178,0.00001184297406,0.000000256758456,0.000020579747215,0.000001145917415,0.000007425985522,0.000001551713648
769,Baldwin,1003,-0.762848419331037,0.087763472287264,288.750430154934634,293.016071564804747,0.006552633923696,0.014749739014158,0.530448463251705,101811.641524154809304,0.069721199208977,0.00000000856051,0.00000001268239,0.000000017489699,0.015842606991557,0.073233448467198,219.598966793320727,101544.24660066254728,0.216019102169781,0.18009967134247,0.142026385696035,0.103637728241703,0.064962127054864,0.000825569914892,0.000003184710655,0.000003080346751,0.000009260198211,0.000000004940491,0.000001322491829,0.01007318421965,0.000004505513695,0.000002475476394,0.00000038951959,0.006115300204305,0.000007280496403,0.000000553529543,0.00000200910831,30.294331358095814,0.000000143507288,0.000000000958754,0.00000000163134,0.000000000637893,0.000000000498101,0.000000002218418,0.000000000841463,0.000000000172129,0.000000005146118,0.000000000173968,0.000000002484526,0.000000000000032,0.000000006737638,0.000000000932501,0.000000004724531,0.000000000287915,0.000000061638062,0.000000001964815,0.000000000194632,0.000000000086083,0.000000007115235,0.000000003913003,0.011915642715677,0.000000002059052,0.000000002647938,292.869378157899575,3.051871036159986,1.920246649928854,0.879975894376574,0.000010755348307,30.403740792923291,0.000002833920608,0.000005755326347,0.000005119825524,0.000000127023293,0.000001956941754,0.000000568242943,0.000011797018417,0.000000361457433,0.000029241505257,0.000003056133892,0.000007847574284,0.000000904095456
978,Barbour,1005,-0.264347027989757,0.026862975371975,285.860652931231073,291.775169704643133,0.00628602106368,0.01205619055821,0.989722920389318,101860.076953441326623,0.071559820329632,0.000000009988104,0.000000013530342,0.000000018504909,0.012998265619844,0.070307483597614,1082.55658972910669,100544.85529870991013,0.208586401053569,0.173207865065745,0.135629461443557,0.097506896604919,0.059552248329856,0.000834643270951,0.000003203534419,0.000003673027828,0.000008615400311,0.000000004896893,0.000002895263636,0.009972358164771,0.000004378821267,0.00000261388497,0.00000040331406,0.006192678938291,0.000008024017502,0.000000575664047,0.000001950756327,28.298083793425672,0.000000164599271,0.000000000809258,0.000000001418708,0.00000000061111,0.000000000547861,0.000000003393476,0.000000000759082,0.000000000201917,0.000000006425952,0.000000000255174,0.000000003497751,0.000000000000021,0.000000015716758,0.000000000771716,0.000000005392756,0.000000000242157,0.000000056293858,0.000000002556927,0.000000000220156,0.000000000038846,0.000000003151686,0.000000000508596,0.010320585662572,0.000000001892151,0.000000001910919,291.486945152625026,3.920961064965877,2.464257714473272,0.879925656091749,0.0,28.426624005498756,0.000002325077576,0.000004698850773,0.000004150028505,0.000000134880523,0.000002175313975,0.000000531804901,0.000011584661398,0.00000029874994,0.000024054202803,0.000001571642775,0.000007180024461,0.000000929471529
2485,Bibb,1007,-0.204831910669626,0.102813951315986,284.558460728837304,290.606953515983491,0.006432663833982,0.009768002480435,0.986674553792982,101870.225196079045418,0.074188361405877,0.000000009596909,0.00000001266727,0.000000017402681,0.009858255285723,0.074822749363335,1346.47012061560531,100231.906114151555812,0.212232381631312,0.17507007334287,0.135556430328454,0.095339525829985,0.056012543662158,0.000854420250782,0.00000327842005,0.000003794999808,0.000008258307434,0.000000004886173,0.000003055715028,0.009940973977466,0.00000459117036,0.000003225996799,0.000000455660088,0.006313855868944,0.000008631258268,0.000000614812286,0.000002866520003,26.092901151303032,0.000000165907086,0.000000000651344,0.000000001146215,0.000000000435228,0.000000000538701,0.000000003407034,0.000000000712047,0.00000000017497,0.000000006168381,0.000000000148687,0.000000003118213,0.000000000000021,0.000000016448747,0.000000000841346,0.000000007947962,0.000000000751258,0.000000056047184,0.00000000276168,0.000000000244373,0.000000000026928,0.000000002175197,0.00000000025432,0.009543552113445,0.000000002505792,0.000000005972286,290.253593705623189,3.703697313743902,2.748821364307786,0.879554520998147,0.000189654659344,26.218415563732844,0.000001883775539,0.000003793477511,0.000003371003881,0.00000012093393,0.00000229623226,0.000000560617896,0.000012127780912,0.000000234822756,0.00001876411405,0.000000933831673,0.000007520067154,0.000001793807994
1,Blount,1009,-0.120287852144202,0.205279055448026,283.957347661596998,289.621758304782475,0.00636158275068,0.00863699135828,0.979337866161448,101890.028973800479434,0.074015823502177,0.0000000094617,0.000000012294537,0.000000016946638,0.008711437362093,0.074811607205051,1976.754446701409961,99486.522110620382591,0.209560935267279,0.17253746273555,0.133130005245127,0.09292803743325,0.053850869471458,0.000855890538993,0.000003286663433,0.000003574831913,0.000007925859329,0.000000004893557,0.000002271110858,0.009863969173879,0.000004638689963,0.000003466344084,0.000000478348591,0.006378116412873,0.00000882381007,0.000000631765244,0.000003097828738,24.682091869376606,0.000000168367219,0.000000000562868,0.000000000991482,0.000000000369037,0.000000000548414,0.000000003017108,0.000000000661267,0.00000000017017,0.000000006092052,0.000000000138199,0.000000003069692,0.000000000000023,0.000000012949814,0.000000000875797,0.000000009080846,0.000000000938215,0.000000055503555,0.000000002651474,0.000000000276763,0.000000000022833,0.000000001844486,0.000000000187108,0.009246295054884,0.000000002669181,0.000000006767186,289.142170840999313,3.298928581756866,2.785360804287578,0.878945907261599,0.000534949366478,24.815968088763601,0.000001656414954,0.000003339985725,0.00000306387551,0.000000117345934,0.000002317859089,0.000000556426418,0.000011994563457,0.000000209742051,0.000016697817224,0.000000733711009,0.000007387955396,0.000002070140772

In [5]:
percentile_75 = get_data['pm2p5'].quantile(0.75)
percentile_75

1.3391971391224438e-08

In [6]:
pm_threshold=percentile_75

In [7]:
SHAPE_PATH=os.path.join('..','..','..','..','Shapefiles','county_shapefiles','2013_county_shapefile','cb_2013_us_county_500k.shp')
county_gdf = gpd.read_file(SHAPE_PATH)
county_gdf

,STATEFP,COUNTYFP,COUNTYNS,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,01,001,00161526,0500000US01001,01001,Autauga,06,1539584443,25773561,"POLYGON ((-86.92120 32.65754, -86.92035 32.658..."
1,01,009,00161530,0500000US01009,01009,Blount,06,1670041814,15077461,"POLYGON ((-86.96336 33.85822, -86.95967 33.857..."
2,01,023,00161537,0500000US01023,01023,Choctaw,06,2365954803,19059247,"POLYGON ((-88.47323 31.89386, -88.46888 31.930..."
3,01,033,00161542,0500000US01033,01033,Colbert,06,1534878355,80029923,"POLYGON ((-88.13925 34.58779, -88.13872 34.589..."
4,01,049,00161550,0500000US01049,01049,DeKalb,06,2012664422,4121499,"POLYGON ((-86.11889 34.40384, -86.11002 34.403..."
...,...,...,...,...,...,...,...,...,...,...
3229,13,171,00326713,0500000US13171,13171,Lamar,06,475262687,6046028,"POLYGON ((-84.26917 33.03144, -84.25906 33.031..."
3230,18,007,00450403,0500000US18007,18007,Benton,06,1052616465,236033,"POLYGON ((-87.52650 40.47716, -87.52638 40.491..."
3231,16,053,00395662,0500000US16053,16053,Jerome,06,1546716831,12848211,"POLYGON ((-114.61740 42.85081, -114.59511 42.8..."
3232,17,095,00424249,0500000US17095,17095,Knox,06,1855506498,8834347,"POLYGON ((-90.44412 40.72857, -90.44400 40.729..."
3233,18,087,00450368,0500000US18087,18087,LaGrange,06,983195242,18359940,"POLYGON ((-85.65975 41.75910, -85.65074 41.759..."

In [8]:
geometry_column=county_gdf['geometry']
geometry_column

0       POLYGON ((-86.92120 32.65754, -86.92035 32.658...
1       POLYGON ((-86.96336 33.85822, -86.95967 33.857...
2       POLYGON ((-88.47323 31.89386, -88.46888 31.930...
3       POLYGON ((-88.13925 34.58779, -88.13872 34.589...
4       POLYGON ((-86.11889 34.40384, -86.11002 34.403...
                              ...
3229    POLYGON ((-84.26917 33.03144, -84.25906 33.031...
3230    POLYGON ((-87.52650 40.47716, -87.52638 40.491...
3231    POLYGON ((-114.61740 42.85081, -114.59511 42.8...
3232    POLYGON ((-90.44412 40.72857, -90.44400 40.729...
3233    POLYGON ((-85.65975 41.75910, -85.65074 41.759...
Name: geometry, Length: 3234, dtype: geometry

In [9]:
lat_lon=geometry_column.get_coordinates(index_parts=True)
lat_lon

                          x                   y
0    0  -86.921195999999995  32.657541999999999
     1  -86.920351999999994  32.658563000000001
     2  -86.920411000000001  32.660077000000001
     3  -86.917594999999992  32.664169000000001
     4  -86.914609999999996  32.664355000000000
...                     ...                 ...
3233 66 -85.658035999999996  41.675677000000000
     67 -85.657950999999997  41.676459000000001
     68 -85.658614000000000  41.696899999999999
     69 -85.658769999999990  41.704004999999995
     70 -85.659750008000898  41.759100801830094

[893880 rows x 2 columns]

#### Fraction of time PM2.5 was above threshold

In [10]:
def single_county(var):
    
    ''' Function to interpolate the values in a single county by taking a 100 or less latitude and longitude pair.
        And then to find the fraction of time, PM2.5 was above EPA standard
        Args:
        --------
             var (int): The index of the county in the shapefile.

        Returns:
        --------
            pm_above_df: Dataframe consisting the values of the variables interpolated in the county.
    '''   
    
    
    longitude= lat_lon.loc[(var), 'x']  # get the longitude
    extract_val=len(longitude) ## find number of longitude that a shapfile has

    ## if number of longitude or latitude is less than 100, that many lat-lon pairs will be extracted, if not, a 100 values
    if extract_val < 100:
        extract_val=extract_val
    else:
        extract_val=100

    longitude=longitude[:extract_val]  ## extract first 100 values or values less than 100
    latitude=lat_lon.loc[(var),'y']    ## get the latitude values
    latitude=latitude[:extract_val]    ## extract first 100 values or values less than 100

    lat_list=latitude.tolist()
    lon_list=longitude.tolist()

    ## find the corresponding values of the variables in the finer grid

    year_avg_finer= pm2_5.interp(longitude=lon_list, latitude=lat_list)
    
## get only the 100 (or less) pair of latitude and longitude from the lat and lon list from the 100,000 (or less) rows
    get_vals=[]

    for i in range(0, extract_val):
        row=year_avg_finer.isel(latitude=[i], longitude=[i])
        row_df=row.to_dataframe()
        get_vals.append(row_df)
    
    initial_df=pd.concat(get_vals)
    summary = initial_df.groupby("valid_time").mean(["latitude", "longitude"])
    df=summary

    total_rows=len(df)

    c=0
    for i in range(0, total_rows):
        if df['pm2p5'].values[i] > pm_threshold:
            c=c+1

## convert number to a fraction
    frac_time=(c/total_rows)*100
    pm_above_df=pd.DataFrame({'PM2.5 above threshold':[frac_time]})


    return pm_above_df

In [11]:
len(county_gdf)

3234

In [12]:
%%time

## get the values for all counties

df_list_below=[]

for i in range(0,len(county_gdf)): ## loop for the all list of counties
    try:
        df_list_below.append(single_county(i))
    except:
        pass

CPU times: total: 1h 13min 13s
Wall time: 1h 14min 12s

In [13]:
concatenate_df=pd.concat(df_list_below)
final_df=concatenate_df.reset_index(drop=True)
final_df

      PM2.5 above threshold
0        37.363013698630141
1        37.945205479452056
2        37.773972602739725
3        35.034246575342465
4        39.212328767123289
...                     ...
3229     48.767123287671232
3230     44.726027397260275
3231     20.136986301369863
3232     38.767123287671232
3233     41.746575342465754

[3234 rows x 1 columns]

In [14]:
## lets first create a fips column in the original shape file

county_gdf['fips']=county_gdf['STATEFP'] + county_gdf['COUNTYFP']
county_gdf.dtypes
## convert the data type
county_gdf['fips']=county_gdf['fips'].astype(str).astype(int)
county_gdf.dtypes

county_gdf = county_gdf.drop(['STATEFP','COUNTYFP','COUNTYNS','AFFGEOID','GEOID','LSAD','ALAND','AWATER'], axis=1)
county_gdf

          NAME                                           geometry   fips
0      Autauga  POLYGON ((-86.92120 32.65754, -86.92035 32.658...   1001
1       Blount  POLYGON ((-86.96336 33.85822, -86.95967 33.857...   1009
2      Choctaw  POLYGON ((-88.47323 31.89386, -88.46888 31.930...   1023
3      Colbert  POLYGON ((-88.13925 34.58779, -88.13872 34.589...   1033
4       DeKalb  POLYGON ((-86.11889 34.40384, -86.11002 34.403...   1049
...        ...                                                ...    ...
3229     Lamar  POLYGON ((-84.26917 33.03144, -84.25906 33.031...  13171
3230    Benton  POLYGON ((-87.52650 40.47716, -87.52638 40.491...  18007
3231    Jerome  POLYGON ((-114.61740 42.85081, -114.59511 42.8...  16053
3232      Knox  POLYGON ((-90.44412 40.72857, -90.44400 40.729...  17095
3233  LaGrange  POLYGON ((-85.65975 41.75910, -85.65074 41.759...  18087

[3234 rows x 3 columns]

In [15]:
merged_df=pd.merge(county_gdf, final_df, left_index=True, right_index=True)
merged_df

,NAME,geometry,fips,PM2.5 above threshold
0,Autauga,"POLYGON ((-86.92120 32.65754, -86.92035 32.658...",1001,37.363013698630141
1,Blount,"POLYGON ((-86.96336 33.85822, -86.95967 33.857...",1009,37.945205479452056
2,Choctaw,"POLYGON ((-88.47323 31.89386, -88.46888 31.930...",1023,37.773972602739725
3,Colbert,"POLYGON ((-88.13925 34.58779, -88.13872 34.589...",1033,35.034246575342465
4,DeKalb,"POLYGON ((-86.11889 34.40384, -86.11002 34.403...",1049,39.212328767123289
...,...,...,...,...
3229,Lamar,"POLYGON ((-84.26917 33.03144, -84.25906 33.031...",13171,48.767123287671232
3230,Benton,"POLYGON ((-87.52650 40.47716, -87.52638 40.491...",18007,44.726027397260275
3231,Jerome,"POLYGON ((-114.61740 42.85081, -114.59511 42.8...",16053,20.136986301369863
3232,Knox,"POLYGON ((-90.44412 40.72857, -90.44400 40.729...",17095,38.767123287671232
3233,LaGrange,"POLYGON ((-85.65975 41.75910, -85.65074 41.759...",18087,41.746575342465754

In [16]:
county_df=merged_df.dropna()
county_df.head()

,NAME,geometry,fips,PM2.5 above threshold
0,Autauga,"POLYGON ((-86.92120 32.65754, -86.92035 32.658...",1001,37.363013698630141
1,Blount,"POLYGON ((-86.96336 33.85822, -86.95967 33.857...",1009,37.945205479452056
2,Choctaw,"POLYGON ((-88.47323 31.89386, -88.46888 31.930...",1023,37.773972602739725
3,Colbert,"POLYGON ((-88.13925 34.58779, -88.13872 34.589...",1033,35.034246575342465
4,DeKalb,"POLYGON ((-86.11889 34.40384, -86.11002 34.403...",1049,39.212328767123289

In [17]:
## convert into pandas dataframe without the geometry column
pd.options.display.float_format = '{:.15f}'.format ## see 15 decimal places of the numbers
county_var=pd.DataFrame(county_df.drop(columns='geometry')) 
county_var=county_var.rename(columns={'PM2.5 above threshold':'PM2.5 above percentile'})
county_var

          NAME   fips  PM2.5 above percentile
0      Autauga   1001      37.363013698630141
1       Blount   1009      37.945205479452056
2      Choctaw   1023      37.773972602739725
3      Colbert   1033      35.034246575342465
4       DeKalb   1049      39.212328767123289
...        ...    ...                     ...
3229     Lamar  13171      48.767123287671232
3230    Benton  18007      44.726027397260275
3231    Jerome  16053      20.136986301369863
3232      Knox  17095      38.767123287671232
3233  LaGrange  18087      41.746575342465754

[3234 rows x 3 columns]

In [18]:
county_var.to_pickle('PM25_above_percentile.pkl')