#### Notebook to feature engineer fraction of time hydrogen peroxide was above 90th percentile

In [1]:
## conda environment Weather_Prediction

import os
import numpy as np
import pandas as pd
import geopandas as gpd
import xarray as xr
pd.set_option('display.max_columns', None)
pd.set_option('display.precision', 15)

In [2]:
PATH_1=os.path.join('..','..','..','..','Weather_Data','CAMS','2010','2010_multi_level_26_variables.nc')
ml_26_variables = xr.open_dataset(PATH_1) ## multilevel 26 variables
ml_26_variables = ml_26_variables.squeeze(dim="model_level") ## remove the model_level dimension
ml_26_variables=ml_26_variables.drop_vars('model_level') ## the dropped dimension becomes a column, so remove that
ml_26_variables['longitude'] = ml_26_variables['longitude']-360 ## necessary because of longitude data in multi-level case
oxide=ml_26_variables['h2o2'] ## get only formaldehyde variable
oxide

<xarray.DataArray 'h2o2' (valid_time: 2920, latitude: 34, longitude: 78)> Size: 31MB
[7743840 values with dtype=float32]
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 23kB 2010-01-01 ... 2010-12-31T21...
  * latitude    (latitude) float64 272B 49.25 48.5 47.75 ... 26.0 25.25 24.5
  * longitude   (longitude) float64 624B -124.8 -124.1 -123.3 ... -67.85 -67.1
Attributes: (12/31)
    GRIB_paramId:                             217003
    GRIB_dataType:                            an
    GRIB_numberOfPoints:                      2652
    GRIB_typeOfLevel:                         hybrid
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_pv:                                  [0.00000000e+00 2.00000000e+01 ...
    GRIB_shortName:                           h2o2
    GRIB_units:                               kg kg**-1
    long_name:                                Hydrogen peroxide
    units:                                    kg kg**-1
    standard_name:                            mass_fraction_of_hydrogen_perox...

In [3]:
oxide.to_dataframe()

                                                                h2o2
valid_time          latitude longitude
2010-01-01 00:00:00 49.25    -124.849999999999994  0.000000000014142
                             -124.099999999999994  0.000000000015198
                             -123.349999999999994  0.000000000010079
                             -122.599999999999994  0.000000000007717
                             -121.849999999999994  0.000000000007572
...                                                              ...
2010-12-31 21:00:00 24.50    -70.100000000000023   0.000000000671815
                             -69.350000000000023   0.000000000585708
                             -68.600000000000023   0.000000000565808
                             -67.850000000000023   0.000000000634915
                             -67.100000000000023   0.000000000692178

[7743840 rows x 1 columns]

In [4]:
PATH_2=os.path.join('..','CAMS_79_variables_2010.pkl')
get_data = pd.read_pickle(PATH_2) ## load the data with all variables
get_data.head()

,NAME,fips,u10,v10,d2m,t2m,bcaod550,duaod550,lsm,msl,omaod550,pm1,pm2p5,pm10,ssaod550,suaod550,z,sp,aod469,aod550,aod670,aod865,aod1240,tcco,tc_c2h6,tchcho,tc_h2o2,tc_oh,tc_c5h8,tc_ch4,tc_hno3,tcno2,tc_no,gtco3,tc_pan,tc_c3h8,tcso2,tcwv,co,aermr04,aermr05,aermr06,c2h6,hcho,h2o2,aermr09,aermr07,aermr10,aermr08,oh,c5h8,hno3,no2,no,go3,pan,c3h8,aermr01,aermr02,aermr03,q,aermr11,so2,t,lai_hv,lai_lv,asn,sd,tcw,aermssdus,aermssdum,aermssdul,aermssbchphil,aermssomhphil,aermssbchphob,aermssomhphob,aermsssss,aermssssm,aermssssl,aermsssu,aermssso2
0,Cleburne,1029,0.413019434594599,-0.107667534800677,282.703011090698624,289.893417245668104,0.006258739615706,0.008160391066076,0.984092741942983,101706.946097755164374,0.077656936743596,0.000000013209071,0.000000016596175,0.000000022974717,0.006331957315087,0.078413175927836,2494.903586698830168,98688.656328798519098,0.216232524283858,0.176821250124215,0.135063312999248,0.092722597516053,0.052063239229144,0.000883831551561,0.000003354210954,0.000004170064362,0.000008342861307,0.000000004900253,0.000002915968832,0.009737069079883,0.000005400752913,0.00000383058123,0.000000545639453,0.006656034353289,0.000009709419429,0.000000714954464,0.000004630331125,23.867765901925651,0.000000192211475,0.000000000574751,0.000000001017461,0.000000000367301,0.000000000631366,0.000000003833444,0.000000000814928,0.000000000209479,0.000000008615652,0.000000000250372,0.000000004937969,0.000000000000024,0.0000000200919,0.000000000958619,0.000000010742353,0.000000001957913,0.000000056939407,0.000000002957058,0.000000000357892,0.000000000018423,0.000000001473682,0.000000000177664,0.008898821944244,0.000000003402435,0.000000013648311,289.661870795791629,3.619148809531778,2.688592340271431,0.877661895152047,0.007418503795786,23.930190478270088,0.000001594230494,0.000003208428781,0.000002502028556,0.000000138454882,0.000002728134267,0.000000525528974,0.000012896589333,0.000000201315302,0.000013297177741,0.000000747483738,0.00000850965718,0.000003311531996
1,Coffee,1031,0.268069503331686,-0.025964159362308,284.557905905267091,291.568022322015281,0.006529789509552,0.011947764919442,0.975374466427369,101688.666378423571587,0.073944227350269,0.000000011704877,0.000000015386833,0.00000002104627,0.008699463101208,0.067619409624997,862.953049591901276,100639.679412019177107,0.20474818819534,0.168740499422022,0.13073182857184,0.092493296449725,0.054778775476052,0.000880218196462,0.000003367609055,0.000004028736041,0.000009042325203,0.00000000488884,0.000003190729882,0.00993843205113,0.000005313718438,0.000002841331554,0.000000431648211,0.006481265555991,0.0000086764048,0.000000670538953,0.000002297448555,26.599668888938126,0.000000180774758,0.000000000795403,0.000000001402711,0.000000000548723,0.00000000058304,0.000000003986732,0.000000000897714,0.000000000227225,0.000000007729934,0.00000000031479,0.000000004373578,0.000000000000022,0.000000019090314,0.00000000087337,0.000000006269221,0.000000000357744,0.000000058946815,0.000000002855801,0.00000000024289,0.000000000030086,0.000000002424879,0.000000000486797,0.00996931892414,0.000000001970724,0.000000002079944,291.584133208273954,3.822411901466365,2.457700141763605,0.879109909071357,0.005603812351802,26.641267412910267,0.000002309854832,0.000004722679324,0.000003729229752,0.000000143891341,0.000002409504448,0.000000549173395,0.000012645736989,0.000000256596916,0.000018046175446,0.000001360598997,0.000007570531817,0.000001001107217
2,Coosa,1037,0.287795389085165,-0.054850648263903,283.356933538902581,290.727280362134422,0.006264528985226,0.009890516497617,0.983458525689603,101698.476434528434766,0.076068681851832,0.000000011866521,0.000000015307483,0.000000021049703,0.007162071259771,0.073970158099324,1656.032388422055419,99690.3003234150965,0.211317774769209,0.1733558542931,0.133191581438985,0.092599646969807,0.053156056523538,0.00088649567171,0.000003369844124,0.000004317511298,0.00000864025526,0.000000004882921,0.000003656188983,0.009840242743546,0.000005277674991,0.000003332716055,0.000000479932509,0.006601615483004,0.000009350434951,0.000000697182351,0.000003677509011,25.161047647636607,0.000000181217639,0.000000000687577,0.000000001225738,0.000000000452833,0.000000000580772,0.000000004111423,0.00000000086339,0.000000000197954,0.000000007765761,0.00000000022335,0.000000004261324,0.000000000000021,0.000000021232174,0.000000000872678,0.000000008185645,0.000000000812128,0.000000058574548,0.000000003035037,0.000000000277194,0.000000000021932,0.000000001756327,0.000000000238569,0.009234842556025,0.000000002801659,0.000000008723111,290.56635498992199,3.832068895593299,2.629367126387233,0.878466712117054,0.006247661373253,25.214005578659339,0.000001926033789,0.000003905363962,0.000003024427612,0.000000132560875,0.00000256006163,0.000000532191207,0.000012807379524,0.000000220508414,0.00001494090789,0.000000919188059,0.000008125544892,0.000002337069398
3,Covington,1039,0.204409639926685,0.031479696827375,285.071317340624944,291.81762322796277,0.006593483297519,0.012547580856641,0.908247644927926,101689.194018789828988,0.074449850444392,0.000000011572168,0.00000001536835,0.000000021009637,0.009130608880504,0.068838194726964,735.074572376534434,100795.132671530693187,0.207950906578626,0.17155967652985,0.133133756796652,0.094488637148123,0.056231567086892,0.000879925890144,0.000003369576607,0.00000396412595,0.000009048167211,0.000000004895941,0.000003099741513,0.009954086554608,0.000005293818412,0.000002837197865,0.000000431548218,0.006476885536591,0.000008577965435,0.00000066908504,0.000002287129718,26.845247567029201,0.000000176054765,0.000000000829272,0.000000001473834,0.000000000580653,0.000000000572875,0.000000003763878,0.000000000913753,0.000000000228777,0.000000007538537,0.000000000319621,0.000000004193781,0.000000000000023,0.000000017459518,0.000000000905119,0.000000005981842,0.000000000326493,0.000000060742594,0.000000002768015,0.000000000233883,0.000000000035084,0.000000002839623,0.000000000734254,0.01019987207452,0.000000002057928,0.000000002316081,291.760274083522802,4.001326895194379,2.614644094666042,0.879078742588267,0.005333547477311,26.88855378782786,0.000002424398354,0.000004968287001,0.000003899905881,0.000000144152712,0.000002379692855,0.000000555966003,0.000012731649664,0.000000263988473,0.000018667225619,0.000001505963897,0.000007676439895,0.00000101332766
4,Crenshaw,1041,0.249259249783334,-0.004673367299516,284.419312396581972,291.552837159239914,0.006506663733168,0.011888078149614,0.971049299058844,101689.90975093828456,0.074415569005802,0.000000011540691,0.000000015206574,0.00000002078763,0.008581274183418,0.068438472635641,926.71797327015895,100563.503025452548172,0.206116680270441,0.16982998915003,0.131512450759935,0.092943806929847,0.054917993789753,0.000881664557368,0.000003369574852,0.000004099867766,0.000008982319145,0.00000000488739,0.000003422084473,0.009930540452035,0.000005278278726,0.000002867657231,0.000000433836051,0.006498165124727,0.000008756350004,0.000000673551977,0.000002349034029,26.471133645101844,0.000000179013862,0.000000000797829,0.000000001417836,0.000000000553234,0.0000000005742,0.000000004006963,0.000000000902978,0.00000000022303,0.000000007613757,0.000000000301376,0.000000004241416,0.000000000000022,0.000000019671013,0.00000000086548,0.000000006133669,0.000000000334918,0.000000059554075,0.000000002892819,0.000000000238259,0.000000000029409,0.000000002367886,0.000000000440495,0.00986049968079,0.000000002027284,0.000000002171638,291.522237376798387,3.962099586429611,2.558194683406658,0.879018092331396,0.005657706914161,26.515297934828478,0.000002301521792,0.000004702980619,0.000003682802864,0.000000141813402,0.000002416457578,0.000000548858282,0.000012703412093,0.000000253055595,0.000017737671066,0.000001310175206,0.000007628165454,0.000001057048376

In [5]:
percentile_75 = get_data['h2o2'].quantile(0.90) ## calculate 90th percentile
print(percentile_75)
threshold=percentile_75

8.428266689155035e-10

In [6]:
SHAPE_PATH=os.path.join('..','..','..','..','Shapefiles','county_shapefiles','2010_county_shapefile','gz_2010_us_050_00_500k.shp')
county_gdf = gpd.read_file(SHAPE_PATH)
county_gdf

,GEO_ID,STATE,COUNTY,NAME,LSAD,CENSUSAREA,geometry
0,0500000US01029,01,029,Cleburne,County,560.100000000000023,"POLYGON ((-85.38872 33.91304, -85.38088 33.873..."
1,0500000US01031,01,031,Coffee,County,678.971999999999980,"POLYGON ((-86.03044 31.61894, -86.00408 31.619..."
2,0500000US01037,01,037,Coosa,County,650.926000000000045,"POLYGON ((-86.00928 33.10164, -86.00917 33.090..."
3,0500000US01039,01,039,Covington,County,1030.455999999999904,"POLYGON ((-86.34851 30.99434, -86.35023 30.994..."
4,0500000US01041,01,041,Crenshaw,County,608.840000000000032,"POLYGON ((-86.14699 31.68045, -86.14711 31.663..."
...,...,...,...,...,...,...,...
3216,0500000US72131,72,131,San Sebastián,Muno,70.423000000000002,"POLYGON ((-66.90748 18.25314, -66.90739 18.253..."
3217,0500000US72133,72,133,Santa Isabel,Muno,34.023000000000003,"POLYGON ((-66.37968 17.94398, -66.38029 17.943..."
3218,0500000US72137,72,137,Toa Baja,Muno,23.241000000000000,"MULTIPOLYGON (((-66.13957 18.46232, -66.13956 ..."
3219,0500000US72139,72,139,Trujillo Alto,Muno,20.763999999999999,"POLYGON ((-66.02917 18.37590, -66.02828 18.376..."
3220,0500000US72153,72,153,Yauco,Muno,68.191999999999993,"POLYGON ((-66.85229 17.95500, -66.85280 17.955..."

In [7]:
geometry_column=county_gdf['geometry']
lat_lon=geometry_column.get_coordinates(index_parts=True)
lat_lon

                           x                   y
0    0   -85.388717131256499  33.913044246670701
     1   -85.380884997931091  33.873507903946098
     2   -85.379455261980397  33.866290645479701
     3   -85.377426000000000  33.856046999999997
     4   -85.376402728158496  33.850655745661598
...                      ...                 ...
3220 202 -66.833717999999990  17.989763000000000
     203 -66.835281999999992  17.988274000000001
     204 -66.835428999999991  17.986322999999999
     205 -66.836681999999996  17.965971000000000
     206 -66.852288475598698  17.955003724282498

[837022 rows x 2 columns]

In [8]:
def single_county(var):
    
    ''' Function to interpolate the values in a single county by taking a 100 or less latitude and longitude pair.
        And then to find the fraction of time above percentile
        Args:
        --------
             var (int): The index of the county in the shapefile.

        Returns:
        --------
            pm_above_df: Dataframe consisting the values of the variables interpolated in the county.
    '''   
    
    
    longitude= lat_lon.loc[(var), 'x']  # get the longitude
    extract_val=len(longitude) ## find number of longitude that a shapfile has

    ## if number of longitude or latitude is less than 100, that many lat-lon pairs will be extracted, if not, a 100 values
    if extract_val < 100:
        extract_val=extract_val
    else:
        extract_val=100

    longitude=longitude[:extract_val]  ## extract first 100 values or values less than 100
    latitude=lat_lon.loc[(var),'y']    ## get the latitude values
    latitude=latitude[:extract_val]    ## extract first 100 values or values less than 100

    lat_list=latitude.tolist()
    lon_list=longitude.tolist()

    ## find the corresponding values of the variables in the finer grid

    year_avg_finer= oxide.interp(longitude=lon_list, latitude=lat_list)
    
## get only the 100 (or less) pair of latitude and longitude from the lat and lon list from the 100,000 (or less) rows
    get_vals=[]

    for i in range(0, extract_val):
        row=year_avg_finer.isel(latitude=[i], longitude=[i])
        row_df=row.to_dataframe()
        get_vals.append(row_df)
    
    initial_df=pd.concat(get_vals)
    summary = initial_df.groupby("valid_time").mean(["latitude", "longitude"])
    df=summary

    total_rows=len(df)

    c=0
    for i in range(0, total_rows):
        if df['h2o2'].values[i] > threshold:
            c=c+1

## convert number to a fraction
    frac_time=(c/total_rows)*100
    pm_above_df=pd.DataFrame({'peroxide above percentile':[frac_time]})


    return pm_above_df

In [9]:
len(county_gdf)

3221

In [10]:
%%time

## get the values for all counties

df_list_below=[]

for i in range(0,len(county_gdf)): ## loop for the all list of counties
    try:
        df_list_below.append(single_county(i))
    except:
        pass

CPU times: total: 1h 13min 49s
Wall time: 1h 14min 35s

In [11]:
concatenate_df=pd.concat(df_list_below)
final_df=concatenate_df.reset_index(drop=True)
final_df

      peroxide above percentile
0            28.047945205479451
1            32.020547945205479
2            29.554794520547944
3            34.554794520547944
4            32.020547945205479
...                         ...
3216          0.000000000000000
3217          0.000000000000000
3218          0.000000000000000
3219          0.000000000000000
3220          0.000000000000000

[3221 rows x 1 columns]

In [12]:
## lets first create a fips column in the original shape file

county_gdf['fips']=county_gdf['STATE'] + county_gdf['COUNTY']
county_gdf.dtypes
## convert the data type
county_gdf['fips']=county_gdf['fips'].astype(str).astype(int)
county_gdf.dtypes

county_gdf = county_gdf.drop(['GEO_ID','STATE','LSAD','COUNTY','LSAD','CENSUSAREA'], axis=1)
county_gdf

               NAME                                           geometry   fips
0          Cleburne  POLYGON ((-85.38872 33.91304, -85.38088 33.873...   1029
1            Coffee  POLYGON ((-86.03044 31.61894, -86.00408 31.619...   1031
2             Coosa  POLYGON ((-86.00928 33.10164, -86.00917 33.090...   1037
3         Covington  POLYGON ((-86.34851 30.99434, -86.35023 30.994...   1039
4          Crenshaw  POLYGON ((-86.14699 31.68045, -86.14711 31.663...   1041
...             ...                                                ...    ...
3216  San Sebastián  POLYGON ((-66.90748 18.25314, -66.90739 18.253...  72131
3217   Santa Isabel  POLYGON ((-66.37968 17.94398, -66.38029 17.943...  72133
3218       Toa Baja  MULTIPOLYGON (((-66.13957 18.46232, -66.13956 ...  72137
3219  Trujillo Alto  POLYGON ((-66.02917 18.37590, -66.02828 18.376...  72139
3220          Yauco  POLYGON ((-66.85229 17.95500, -66.85280 17.955...  72153

[3221 rows x 3 columns]

In [13]:
merged_df=pd.merge(county_gdf, final_df, left_index=True, right_index=True)
merged_df

,NAME,geometry,fips,peroxide above percentile
0,Cleburne,"POLYGON ((-85.38872 33.91304, -85.38088 33.873...",1029,28.047945205479451
1,Coffee,"POLYGON ((-86.03044 31.61894, -86.00408 31.619...",1031,32.020547945205479
2,Coosa,"POLYGON ((-86.00928 33.10164, -86.00917 33.090...",1037,29.554794520547944
3,Covington,"POLYGON ((-86.34851 30.99434, -86.35023 30.994...",1039,34.554794520547944
4,Crenshaw,"POLYGON ((-86.14699 31.68045, -86.14711 31.663...",1041,32.020547945205479
...,...,...,...,...
3216,San Sebastián,"POLYGON ((-66.90748 18.25314, -66.90739 18.253...",72131,0.000000000000000
3217,Santa Isabel,"POLYGON ((-66.37968 17.94398, -66.38029 17.943...",72133,0.000000000000000
3218,Toa Baja,"MULTIPOLYGON (((-66.13957 18.46232, -66.13956 ...",72137,0.000000000000000
3219,Trujillo Alto,"POLYGON ((-66.02917 18.37590, -66.02828 18.376...",72139,0.000000000000000
3220,Yauco,"POLYGON ((-66.85229 17.95500, -66.85280 17.955...",72153,0.000000000000000

In [14]:
county_df=merged_df.dropna()
county_df.head()

,NAME,geometry,fips,peroxide above percentile
0,Cleburne,"POLYGON ((-85.38872 33.91304, -85.38088 33.873...",1029,28.047945205479451
1,Coffee,"POLYGON ((-86.03044 31.61894, -86.00408 31.619...",1031,32.020547945205479
2,Coosa,"POLYGON ((-86.00928 33.10164, -86.00917 33.090...",1037,29.554794520547944
3,Covington,"POLYGON ((-86.34851 30.99434, -86.35023 30.994...",1039,34.554794520547944
4,Crenshaw,"POLYGON ((-86.14699 31.68045, -86.14711 31.663...",1041,32.020547945205479

In [15]:
## convert into pandas dataframe without the geometry column
pd.options.display.float_format = '{:.15f}'.format ## see 15 decimal places of the numbers
county_var=pd.DataFrame(county_df.drop(columns='geometry')) 
county_var

               NAME   fips  peroxide above percentile
0          Cleburne   1029         28.047945205479451
1            Coffee   1031         32.020547945205479
2             Coosa   1037         29.554794520547944
3         Covington   1039         34.554794520547944
4          Crenshaw   1041         32.020547945205479
...             ...    ...                        ...
3216  San Sebastián  72131          0.000000000000000
3217   Santa Isabel  72133          0.000000000000000
3218       Toa Baja  72137          0.000000000000000
3219  Trujillo Alto  72139          0.000000000000000
3220          Yauco  72153          0.000000000000000

[3221 rows x 3 columns]

In [16]:
county_var.to_pickle('peroxide_above_percentile.pkl')