#### Notebook to feature engineer fraction of time PM10 was above EPA standard for all counties

In [1]:
## conda environment Weather_Prediction

import os
import numpy as np
import pandas as pd
import geopandas as gpd
import xarray as xr
pd.set_option('display.max_columns', None)
pd.set_option('display.precision', 15)

In [2]:
PATH_1=os.path.join('..','..','..','..','Weather_Data','CAMS','2009','2009_single_level_34_variables.nc')
sl_34_variables = xr.open_dataset(PATH_1) ## single level 34 variables
sl_34_variables
pm10=sl_34_variables['pm10'] ## get only pm2.5 variable
pm10

<xarray.DataArray 'pm10' (valid_time: 2920, latitude: 34, longitude: 78)> Size: 31MB
[7743840 values with dtype=float32]
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 23kB 2009-01-01 ... 2009-12-31T21...
  * latitude    (latitude) float64 272B 49.25 48.5 47.75 ... 26.0 25.25 24.5
  * longitude   (longitude) float64 624B -124.8 -124.1 -123.3 ... -67.85 -67.1
Attributes: (12/33)
    GRIB_paramId:                             210074
    GRIB_dataType:                            an
    GRIB_numberOfPoints:                      2652
    GRIB_typeOfLevel:                         surface
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_units:                               kg m**-3
    long_name:                                Particulate matter d <= 10 um
    units:                                    kg m**-3
    standard_name:                            mass_concentration_of_pm10_ambi...
    GRIB_number:                              0
    GRIB_surface:                             0.0

In [3]:
pm10.to_dataframe()

                                                                pm10
valid_time          latitude longitude
2009-01-01 00:00:00 49.25    -124.849999999999994  0.000000013512392
                             -124.099999999999994  0.000000018051184
                             -123.349999999999994  0.000000018474276
                             -122.599999999999994  0.000000015168192
                             -121.849999999999994  0.000000010948320
...                                                              ...
2009-12-31 21:00:00 24.50    -70.099999999999994   0.000000011471684
                             -69.349999999999994   0.000000012514882
                             -68.599999999999994   0.000000012117525
                             -67.849999999999994   0.000000010920267
                             -67.099999999999994   0.000000012667428

[7743840 rows x 1 columns]

In [4]:
pm_threshold=150*10**(-9) ## epa standard
pm_threshold

1.5000000000000002e-07

In [5]:
SHAPE_PATH=os.path.join('..','..','..','..','Shapefiles','county_shapefiles','2009_county_shapefile','tl_2009_us_county.shp')
county_gdf = gpd.read_file(SHAPE_PATH)
county_gdf

,STATEFP,COUNTYFP,COUNTYNS,CNTYIDFP,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,CSAFP,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,16,035,00395697,16035,Clearwater,Clearwater County,06,H1,G4020,None,None,None,A,6364465317,79541433,+46.6725699,-115.6535002,"POLYGON ((-115.97504 46.29399, -115.97542 46.2..."
1,16,033,00399755,16033,Clark,Clark County,06,H1,G4020,None,None,None,A,4569211245,2476849,+44.2862511,-112.3611201,"POLYGON ((-112.73322 44.49991, -112.73152 44.5..."
2,16,025,00399408,16025,Camas,Camas County,06,H1,G4020,None,None,None,A,2782930314,11535337,+43.4633957,-114.8044265,"POLYGON ((-114.46408 43.32532, -114.46307 43.3..."
3,16,049,00395699,16049,Idaho,Idaho County,06,H1,G4020,None,None,None,A,21956209975,67333453,+45.8492367,-115.4673755,"POLYGON ((-116.52984 45.53828, -116.52981 45.5..."
4,16,019,00395407,16019,Bonneville,Bonneville County,06,H1,G4020,292,26820,None,A,4832931620,89483679,+43.3951707,-111.6218783,"POLYGON ((-112.52009 43.54467, -112.52010 43.5..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3229,48,069,01383820,48069,Castro,Castro County,06,H1,G4020,None,None,None,A,2316590566,12585110,+34.5336206,-102.2587856,"POLYGON ((-102.12045 34.74766, -102.12042 34.7..."
3230,48,127,01383849,48127,Dimmit,Dimmit County,06,H1,G4020,None,None,None,A,3441683133,14576058,+28.4235871,-099.7658713,"POLYGON ((-100.00815 28.19871, -100.01229 28.1..."
3231,48,271,01383921,48271,Kinney,Kinney County,06,H1,G4020,None,None,None,A,3522514289,13125084,+29.3470864,-100.4177003,"POLYGON ((-100.69998 29.49896, -100.69999 29.5..."
3232,48,177,01383874,48177,Gonzales,Gonzales County,06,H1,G4020,None,None,None,A,2762705077,8200950,+29.4687114,-097.4777298,"POLYGON ((-97.77281 29.26596, -97.77331 29.266..."
3233,48,089,01383830,48089,Colorado,Colorado County,06,H1,G4020,None,None,None,A,2487086404,34736359,+29.5958137,-096.5082946,"POLYGON ((-96.66181 29.85619, -96.65864 29.859..."

In [6]:
geometry_column=county_gdf['geometry']
geometry_column

0       POLYGON ((-115.97504 46.29399, -115.97542 46.2...
1       POLYGON ((-112.73322 44.49991, -112.73152 44.5...
2       POLYGON ((-114.46408 43.32532, -114.46307 43.3...
3       POLYGON ((-116.52984 45.53828, -116.52981 45.5...
4       POLYGON ((-112.52009 43.54467, -112.52010 43.5...
                              ...
3229    POLYGON ((-102.12045 34.74766, -102.12042 34.7...
3230    POLYGON ((-100.00815 28.19871, -100.01229 28.1...
3231    POLYGON ((-100.69998 29.49896, -100.69999 29.5...
3232    POLYGON ((-97.77281 29.26596, -97.77331 29.266...
3233    POLYGON ((-96.66181 29.85619, -96.65864 29.859...
Name: geometry, Length: 3234, dtype: geometry

In [7]:
lat_lon=geometry_column.get_coordinates(index_parts=True)
lat_lon

                             x                   y
0    0    -115.975042000000002  46.293987000000001
     1    -115.975423000000006  46.294055999999998
     2    -115.975768000000002  46.294208999999995
     3    -115.975971000000001  46.294354999999996
     4    -115.976267000000007  46.294494999999998
...                        ...                 ...
3233 3483  -96.665371999999991  29.852008999999999
     3484  -96.665150999999994  29.852266999999998
     3485  -96.662978999999993  29.854689999999998
     3486  -96.661906000000002  29.856083999999999
     3487  -96.661813999999993  29.856192999999998

[7629005 rows x 2 columns]

#### Fraction of time PM10 was above EPA threshold

In [8]:
def single_county(var):
    
    ''' Function to interpolate the values in a single county by taking a 100 or less latitude and longitude pair.
        And then to find the fraction of time, PM2.5 was above EPA standard
        Args:
        --------
             var (int): The index of the county in the shapefile.

        Returns:
        --------
            pm_above_df: Dataframe consisting the values of the variables interpolated in the county.
    '''   
    
    
    longitude= lat_lon.loc[(var), 'x']  # get the longitude
    extract_val=len(longitude) ## find number of longitude that a shapfile has

    ## if number of longitude or latitude is less than 100, that many lat-lon pairs will be extracted, if not, a 100 values
    if extract_val < 100:
        extract_val=extract_val
    else:
        extract_val=100

    longitude=longitude[:extract_val]  ## extract first 100 values or values less than 100
    latitude=lat_lon.loc[(var),'y']    ## get the latitude values
    latitude=latitude[:extract_val]    ## extract first 100 values or values less than 100

    lat_list=latitude.tolist()
    lon_list=longitude.tolist()

    ## find the corresponding values of the variables in the finer grid

    year_avg_finer= pm10.interp(longitude=lon_list, latitude=lat_list)
    
## get only the 100 (or less) pair of latitude and longitude from the lat and lon list from the 100,000 (or less) rows
    get_vals=[]

    for i in range(0, extract_val):
        row=year_avg_finer.isel(latitude=[i], longitude=[i])
        row_df=row.to_dataframe()
        get_vals.append(row_df)
    
    initial_df=pd.concat(get_vals)
    summary = initial_df.groupby("valid_time").mean(["latitude", "longitude"])
    df=summary

    total_rows=len(df)

    c=0
    for i in range(0, total_rows):
        if df['pm10'].values[i] > pm_threshold:
            c=c+1

## convert number to a fraction
    frac_time=(c/total_rows)*100
    pm_above_df=pd.DataFrame({'PM10 above threshold':[frac_time]})


    return pm_above_df

In [9]:
len(county_gdf)

3234

In [10]:
%%time

## get the values for all counties

df_list_below=[]

for i in range(0,len(county_gdf)): ## loop for the all list of counties
    try:
        df_list_below.append(single_county(i))
    except:
        pass

CPU times: total: 49min 22s
Wall time: 49min 56s

In [11]:
concatenate_df=pd.concat(df_list_below)
final_df=concatenate_df.reset_index(drop=True)
final_df

      PM10 above threshold
0        0.513698630136986
1        0.000000000000000
2        0.000000000000000
3        0.239726027397260
4        0.753424657534247
...                    ...
3229     0.000000000000000
3230     0.000000000000000
3231     0.000000000000000
3232     0.000000000000000
3233     0.000000000000000

[3234 rows x 1 columns]

In [12]:
## lets first create a fips column in the original shape file

county_gdf['fips']=county_gdf['STATEFP'] + county_gdf['COUNTYFP']
county_gdf.dtypes
## convert the data type
county_gdf['fips']=county_gdf['fips'].astype(str).astype(int)
county_gdf.dtypes

county_gdf = county_gdf.drop(['STATEFP','COUNTYFP','COUNTYNS','CNTYIDFP','NAMELSAD','LSAD','CLASSFP',
                             'MTFCC','CSAFP','CBSAFP','METDIVFP','FUNCSTAT','ALAND','AWATER','INTPTLAT',
                             'INTPTLON'], axis=1)
county_gdf

            NAME                                           geometry   fips
0     Clearwater  POLYGON ((-115.97504 46.29399, -115.97542 46.2...  16035
1          Clark  POLYGON ((-112.73322 44.49991, -112.73152 44.5...  16033
2          Camas  POLYGON ((-114.46408 43.32532, -114.46307 43.3...  16025
3          Idaho  POLYGON ((-116.52984 45.53828, -116.52981 45.5...  16049
4     Bonneville  POLYGON ((-112.52009 43.54467, -112.52010 43.5...  16019
...          ...                                                ...    ...
3229      Castro  POLYGON ((-102.12045 34.74766, -102.12042 34.7...  48069
3230      Dimmit  POLYGON ((-100.00815 28.19871, -100.01229 28.1...  48127
3231      Kinney  POLYGON ((-100.69998 29.49896, -100.69999 29.5...  48271
3232    Gonzales  POLYGON ((-97.77281 29.26596, -97.77331 29.266...  48177
3233    Colorado  POLYGON ((-96.66181 29.85619, -96.65864 29.859...  48089

[3234 rows x 3 columns]

In [13]:
merged_df=pd.merge(county_gdf, final_df, left_index=True, right_index=True)
merged_df

,NAME,geometry,fips,PM10 above threshold
0,Clearwater,"POLYGON ((-115.97504 46.29399, -115.97542 46.2...",16035,0.513698630136986
1,Clark,"POLYGON ((-112.73322 44.49991, -112.73152 44.5...",16033,0.000000000000000
2,Camas,"POLYGON ((-114.46408 43.32532, -114.46307 43.3...",16025,0.000000000000000
3,Idaho,"POLYGON ((-116.52984 45.53828, -116.52981 45.5...",16049,0.239726027397260
4,Bonneville,"POLYGON ((-112.52009 43.54467, -112.52010 43.5...",16019,0.753424657534247
...,...,...,...,...
3229,Castro,"POLYGON ((-102.12045 34.74766, -102.12042 34.7...",48069,0.000000000000000
3230,Dimmit,"POLYGON ((-100.00815 28.19871, -100.01229 28.1...",48127,0.000000000000000
3231,Kinney,"POLYGON ((-100.69998 29.49896, -100.69999 29.5...",48271,0.000000000000000
3232,Gonzales,"POLYGON ((-97.77281 29.26596, -97.77331 29.266...",48177,0.000000000000000
3233,Colorado,"POLYGON ((-96.66181 29.85619, -96.65864 29.859...",48089,0.000000000000000

In [14]:
county_df=merged_df.dropna()
county_df.head()

,NAME,geometry,fips,PM10 above threshold
0,Clearwater,"POLYGON ((-115.97504 46.29399, -115.97542 46.2...",16035,0.513698630136986
1,Clark,"POLYGON ((-112.73322 44.49991, -112.73152 44.5...",16033,0.000000000000000
2,Camas,"POLYGON ((-114.46408 43.32532, -114.46307 43.3...",16025,0.000000000000000
3,Idaho,"POLYGON ((-116.52984 45.53828, -116.52981 45.5...",16049,0.239726027397260
4,Bonneville,"POLYGON ((-112.52009 43.54467, -112.52010 43.5...",16019,0.753424657534247

In [15]:
## convert into pandas dataframe without the geometry column
pd.options.display.float_format = '{:.15f}'.format ## see 15 decimal places of the numbers
county_var=pd.DataFrame(county_df.drop(columns='geometry')) 
county_var

            NAME   fips  PM10 above threshold
0     Clearwater  16035     0.513698630136986
1          Clark  16033     0.000000000000000
2          Camas  16025     0.000000000000000
3          Idaho  16049     0.239726027397260
4     Bonneville  16019     0.753424657534247
...          ...    ...                   ...
3229      Castro  48069     0.000000000000000
3230      Dimmit  48127     0.000000000000000
3231      Kinney  48271     0.000000000000000
3232    Gonzales  48177     0.000000000000000
3233    Colorado  48089     0.000000000000000

[3234 rows x 3 columns]

In [16]:
county_var.to_pickle('PM10_above_threshold.pkl')