#### Notebook to feature engineer fraction of time temperature was above 90F

In [1]:
## conda environment Weather_Prediction

import os
import numpy as np
import pandas as pd
import geopandas as gpd
import xarray as xr
pd.set_option('display.max_columns', None)
pd.set_option('display.precision', 15)

In [2]:
PATH_1=os.path.join('..','..','..','..','Weather_Data','CAMS','2009','2009_multi_level_26_variables.nc')
ml_26_variables = xr.open_dataset(PATH_1) ## multilevel 26 variables
ml_26_variables = ml_26_variables.squeeze(dim="model_level") ## remove the model_level dimension
ml_26_variables=ml_26_variables.drop_vars('model_level') ## the dropped dimension becomes a column, so remove that
ml_26_variables['longitude'] = ml_26_variables['longitude']-360 ## necessary because of longitude data in multi-level case
temp=ml_26_variables['t'] ## get only the temperature variable
temp

<xarray.DataArray 't' (valid_time: 2920, latitude: 34, longitude: 78)> Size: 31MB
[7743840 values with dtype=float32]
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 23kB 2009-01-01 ... 2009-12-31T21...
  * latitude    (latitude) float64 272B 49.25 48.5 47.75 ... 26.0 25.25 24.5
  * longitude   (longitude) float64 624B -124.8 -124.1 -123.3 ... -67.85 -67.1
Attributes: (12/31)
    GRIB_paramId:                             130
    GRIB_dataType:                            an
    GRIB_numberOfPoints:                      2652
    GRIB_typeOfLevel:                         hybrid
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_pv:                                  [0.00000000e+00 2.00000000e+01 ...
    GRIB_shortName:                           t
    GRIB_units:                               K
    long_name:                                Temperature
    units:                                    K
    standard_name:                            air_temperature

In [3]:
temp.to_dataframe()

                                                                     t
valid_time          latitude longitude
2009-01-01 00:00:00 49.25    -124.849999999999994  275.886138916015625
                             -124.099999999999994  275.169342041015625
                             -123.349999999999994  273.987701416015625
                             -122.599999999999994  271.543365478515625
                             -121.849999999999994  268.424224853515625
...                                                                ...
2009-12-31 21:00:00 24.50    -70.100000000000023   295.622985839843750
                             -69.350000000000023   295.548767089843750
                             -68.600000000000023   295.405212402343750
                             -67.850000000000023   295.232360839843750
                             -67.100000000000023   294.980407714843750

[7743840 rows x 1 columns]

In [4]:
PATH_2=os.path.join('..','CAMS_79_variables_2009.pkl')
get_data = pd.read_pickle(PATH_2) ## load the data with all variables
get_data.head()

,NAME,fips,u10,v10,d2m,t2m,bcaod550,duaod550,lsm,msl,omaod550,pm1,pm2p5,pm10,ssaod550,suaod550,z,sp,aod469,aod550,aod670,aod865,aod1240,tcco,tc_c2h6,tchcho,tc_h2o2,tc_oh,tc_c5h8,tc_ch4,tc_hno3,tcno2,tc_no,gtco3,tc_pan,tc_c3h8,tcso2,tcwv,co,aermr04,aermr05,aermr06,c2h6,hcho,h2o2,aermr09,aermr07,aermr10,aermr08,oh,c5h8,hno3,no2,no,go3,pan,c3h8,aermr01,aermr02,aermr03,q,aermr11,so2,t,lai_hv,lai_lv,asn,sd,tcw,aermssdus,aermssdum,aermssdul,aermssbchphil,aermssomhphil,aermssbchphob,aermssomhphob,aermsssss,aermssssm,aermssssl,aermsssu,aermssso2
520,Autauga,1001,0.073119410528947,0.201535636163385,285.402855917927127,291.137112764570588,0.006292674342034,0.008306800781765,0.987325569663562,101765.213057046945323,0.076955570062839,0.000000010048535,0.000000012965955,0.000000017971784,0.01076599082654,0.076192907095036,1315.784621524003342,100168.189549494578387,0.216672330422359,0.178514013040987,0.13790751814739,0.096449251277419,0.056288246864038,0.000852824528897,0.000003319589567,0.000003680093612,0.000008370981779,0.000000004928073,0.000002705314256,0.009872510611199,0.00000509835793,0.000003236524614,0.000000480114919,0.006231566996383,0.000007658503123,0.000000632301166,0.000002846143125,26.971687940064033,0.000000165060695,0.000000000528014,0.000000000902829,0.000000000321493,0.000000000525099,0.000000003377601,0.000000000729718,0.000000000179097,0.000000006655052,0.000000000166802,0.000000003454038,0.000000000000024,0.000000015446789,0.000000000953771,0.000000006801671,0.000000000381064,0.000000057214311,0.000000002617769,0.000000000235087,0.000000000031532,0.000000002486505,0.00000000033428,0.01010461055274,0.000000002503881,0.000000005328814,290.813494226783348,3.916056010594448,2.617223264108416,0.879592301671114,0.00058605865904,27.085313939663077,0.000001602749004,0.000003167401344,0.000002886148285,0.000000131955411,0.000002485902945,0.000000535704828,0.000012300054402,0.000000440661993,0.000019557117885,0.000001181565011,0.000007667184362,0.000001702025245
516,Baldwin,1003,-0.217477259600201,0.546058128054984,289.1267118677751,293.165400951745198,0.006434460217095,0.011734424729921,0.422456727373741,101733.33933134288236,0.070605896521185,0.000000007737504,0.000000011413681,0.000000016047645,0.0153892355373,0.076808011214938,170.454787516937728,101525.833599956458784,0.218229055217598,0.180972119893424,0.141469602865032,0.101523996493923,0.062164182752194,0.000830952883695,0.000003248894257,0.000002881306595,0.000009613777665,0.000000004966827,0.000000961899272,0.010008999525339,0.000005194606998,0.000002566922556,0.000000417599898,0.006114037997087,0.000006447612883,0.000000574732872,0.000002206123538,29.812820260846344,0.000000136864603,0.000000000705791,0.000000001164693,0.000000000361443,0.000000000473641,0.00000000176425,0.000000000920088,0.000000000153108,0.000000004764501,0.000000000137272,0.000000002123666,0.00000000000004,0.000000004289995,0.000000001152025,0.000000004101472,0.000000000206956,0.000000063409327,0.000000001591998,0.00000000018591,0.000000000102758,0.000000008488177,0.000000005407938,0.012125870126163,0.000000002192161,0.00000000261434,293.055124694880192,2.493748263318578,1.556460793604144,0.87999195140757,0.000000560914293,29.847070876843613,0.00000227076207,0.00000452885825,0.000003875699645,0.000000119146049,0.000001926305493,0.000000563855881,0.0000120485795,0.000000534976048,0.000028463636312,0.000003533916107,0.000008383921818,0.000000969674838
522,Barbour,1005,0.187915897840291,0.121698561569697,285.227076406652941,291.684570522568606,0.006479177346758,0.009010010628471,0.986926074501393,101768.19372813742666,0.076504841398626,0.00000001049271,0.000000013608337,0.000000018790993,0.011519536595264,0.073755608409891,1263.685437879796154,100235.407767391545349,0.214802217874091,0.177269321612105,0.137365723373558,0.096687090089152,0.057062518922512,0.000849300088726,0.000003304499961,0.000003706805707,0.000008568425183,0.000000004924378,0.000002649368643,0.009879172407764,0.000005050113979,0.000003054078263,0.000000464533062,0.006202982936367,0.000007608726545,0.000000624895642,0.000002339746467,27.360969681220809,0.000000167626684,0.000000000589456,0.000000001006421,0.000000000360228,0.000000000551527,0.000000003170318,0.000000000768353,0.000000000204368,0.00000000701414,0.000000000242817,0.000000003795469,0.000000000000024,0.000000014192781,0.000000000894667,0.000000005818047,0.00000000029199,0.000000054758248,0.000000002368468,0.000000000234102,0.000000000034625,0.000000002735266,0.000000000397571,0.010059266456181,0.000000002132089,0.000000002197161,291.419337874986923,4.174570187840095,2.367511530630567,0.879749720686517,0.00034106288836,27.453537802685265,0.000001754070065,0.000003456246406,0.000002971873164,0.000000149365505,0.00000252812487,0.000000539579327,0.000012258252572,0.000000452889093,0.000020819704961,0.00000133776729,0.000007517708023,0.000001193942752
501,Bibb,1007,0.012627341837905,0.275287448153957,285.041223822191569,290.572843947004287,0.00627806542134,0.007665669383936,0.987025388372866,101761.712652610440273,0.079443133385507,0.000000010359129,0.00000001318585,0.00000001833255,0.009724964728935,0.078587942048742,1352.761730778134279,100117.529339122527745,0.220936290523694,0.181699886428372,0.139903183247556,0.09714233838061,0.055908240769892,0.000860570689116,0.000003350241059,0.000003569380777,0.000008054795875,0.000000004939854,0.000002396412198,0.009867684956061,0.0000052467134,0.000003677274316,0.000000521831722,0.006279137875082,0.000007776924712,0.000000652126699,0.000003238359258,26.253320785768313,0.000000167251434,0.000000000471605,0.000000000810096,0.000000000293636,0.000000000529493,0.000000003165326,0.000000000671407,0.000000000175005,0.000000006828752,0.000000000148468,0.000000003517184,0.000000000000025,0.000000014373541,0.000000001031367,0.000000009047132,0.000000000845016,0.000000055274774,0.000000002545501,0.000000000252967,0.000000000027278,0.000000002134994,0.000000000237373,0.009847582099814,0.000000002828018,0.000000007162371,290.1715692035487,3.660203275149777,2.772281654851798,0.879450160091823,0.000991831140394,26.386113572146513,0.000001469640875,0.000002905276108,0.000002773868584,0.000000129934287,0.000002638356813,0.000000535560945,0.00001253939946,0.000000424714515,0.000017824379162,0.000000954696606,0.000007761838454,0.000002099004899
535,Blount,1009,0.075675699258684,0.333432987344331,284.306410239659726,289.774696245277653,0.0062119491251,0.0068031892856,0.979014066638673,101775.495818469324149,0.079883115735614,0.00000001080698,0.000000013574753,0.000000018914889,0.008735013678377,0.079188066505717,2029.708085049063129,99312.315274155524094,0.220174782683395,0.180821394748368,0.138847420108713,0.09580640288684,0.054462322219554,0.000858835647438,0.000003348815255,0.0000033055192,0.000007632389917,0.00000000494879,0.000001660806937,0.009785136489853,0.000005323414678,0.000003933199329,0.000000544278896,0.0063284512159,0.000007891880796,0.000000669206367,0.000003502212832,24.861446203243148,0.000000171828179,0.000000000422574,0.000000000729815,0.000000000273449,0.00000000054928,0.000000002725773,0.000000000617783,0.000000000180178,0.000000007128882,0.000000000161093,0.000000003751488,0.000000000000027,0.000000010562512,0.000000001097795,0.000000010102576,0.000000001030974,0.000000054640335,0.000000002394653,0.000000000291949,0.000000000023828,0.00000000185053,0.000000000167048,0.00944991111887,0.000000003036652,0.000000007964709,289.187136232900855,3.286418753252266,2.78269651469914,0.879096066823078,0.002128218955038,25.009708156261514,0.00000129946352,0.000002563057378,0.000002532074007,0.000000134607672,0.000002761791394,0.000000523860723,0.000012409446279,0.000000409320373,0.000016111915905,0.000000775360007,0.000007655002924,0.000002402978088

In [5]:
threshold= 305.372 ## set threshold 90 F

In [6]:
SHAPE_PATH=os.path.join('..','..','..','..','Shapefiles','county_shapefiles','2009_county_shapefile','tl_2009_us_county.shp')
county_gdf = gpd.read_file(SHAPE_PATH)
county_gdf

,STATEFP,COUNTYFP,COUNTYNS,CNTYIDFP,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,CSAFP,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,16,035,00395697,16035,Clearwater,Clearwater County,06,H1,G4020,None,None,None,A,6364465317,79541433,+46.6725699,-115.6535002,"POLYGON ((-115.97504 46.29399, -115.97542 46.2..."
1,16,033,00399755,16033,Clark,Clark County,06,H1,G4020,None,None,None,A,4569211245,2476849,+44.2862511,-112.3611201,"POLYGON ((-112.73322 44.49991, -112.73152 44.5..."
2,16,025,00399408,16025,Camas,Camas County,06,H1,G4020,None,None,None,A,2782930314,11535337,+43.4633957,-114.8044265,"POLYGON ((-114.46408 43.32532, -114.46307 43.3..."
3,16,049,00395699,16049,Idaho,Idaho County,06,H1,G4020,None,None,None,A,21956209975,67333453,+45.8492367,-115.4673755,"POLYGON ((-116.52984 45.53828, -116.52981 45.5..."
4,16,019,00395407,16019,Bonneville,Bonneville County,06,H1,G4020,292,26820,None,A,4832931620,89483679,+43.3951707,-111.6218783,"POLYGON ((-112.52009 43.54467, -112.52010 43.5..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3229,48,069,01383820,48069,Castro,Castro County,06,H1,G4020,None,None,None,A,2316590566,12585110,+34.5336206,-102.2587856,"POLYGON ((-102.12045 34.74766, -102.12042 34.7..."
3230,48,127,01383849,48127,Dimmit,Dimmit County,06,H1,G4020,None,None,None,A,3441683133,14576058,+28.4235871,-099.7658713,"POLYGON ((-100.00815 28.19871, -100.01229 28.1..."
3231,48,271,01383921,48271,Kinney,Kinney County,06,H1,G4020,None,None,None,A,3522514289,13125084,+29.3470864,-100.4177003,"POLYGON ((-100.69998 29.49896, -100.69999 29.5..."
3232,48,177,01383874,48177,Gonzales,Gonzales County,06,H1,G4020,None,None,None,A,2762705077,8200950,+29.4687114,-097.4777298,"POLYGON ((-97.77281 29.26596, -97.77331 29.266..."
3233,48,089,01383830,48089,Colorado,Colorado County,06,H1,G4020,None,None,None,A,2487086404,34736359,+29.5958137,-096.5082946,"POLYGON ((-96.66181 29.85619, -96.65864 29.859..."

In [7]:
geometry_column=county_gdf['geometry']
lat_lon=geometry_column.get_coordinates(index_parts=True)
lat_lon

                             x                   y
0    0    -115.975042000000002  46.293987000000001
     1    -115.975423000000006  46.294055999999998
     2    -115.975768000000002  46.294208999999995
     3    -115.975971000000001  46.294354999999996
     4    -115.976267000000007  46.294494999999998
...                        ...                 ...
3233 3483  -96.665371999999991  29.852008999999999
     3484  -96.665150999999994  29.852266999999998
     3485  -96.662978999999993  29.854689999999998
     3486  -96.661906000000002  29.856083999999999
     3487  -96.661813999999993  29.856192999999998

[7629005 rows x 2 columns]

In [8]:
def single_county(var):
    
    ''' Function to interpolate the values in a single county by taking a 100 or less latitude and longitude pair.
        And then to find the fraction of time, PM2.5 was above EPA standard
        Args:
        --------
             var (int): The index of the county in the shapefile.

        Returns:
        --------
            pm_above_df: Dataframe consisting the values of the variables interpolated in the county.
    '''   
    
    
    longitude= lat_lon.loc[(var), 'x']  # get the longitude
    extract_val=len(longitude) ## find number of longitude that a shapfile has

    ## if number of longitude or latitude is less than 100, that many lat-lon pairs will be extracted, if not, a 100 values
    if extract_val < 100:
        extract_val=extract_val
    else:
        extract_val=100

    longitude=longitude[:extract_val]  ## extract first 100 values or values less than 100
    latitude=lat_lon.loc[(var),'y']    ## get the latitude values
    latitude=latitude[:extract_val]    ## extract first 100 values or values less than 100

    lat_list=latitude.tolist()
    lon_list=longitude.tolist()

    ## find the corresponding values of the variables in the finer grid

    year_avg_finer= temp.interp(longitude=lon_list, latitude=lat_list)
    
## get only the 100 (or less) pair of latitude and longitude from the lat and lon list from the 100,000 (or less) rows
    get_vals=[]

    for i in range(0, extract_val):
        row=year_avg_finer.isel(latitude=[i], longitude=[i])
        row_df=row.to_dataframe()
        get_vals.append(row_df)
    
    initial_df=pd.concat(get_vals)
    summary = initial_df.groupby("valid_time").mean(["latitude", "longitude"])
    df=summary

    total_rows=len(df)

    c=0
    for i in range(0, total_rows):
        if df['t'].values[i] > threshold:
            c=c+1

## convert number to a fraction
    frac_time=(c/total_rows)*100
    pm_above_df=pd.DataFrame({'Temp above threshold':[frac_time]})


    return pm_above_df

In [9]:
len(county_gdf)

3234

In [10]:
%%time

## get the values for all counties

df_list_below=[]

for i in range(0,len(county_gdf)): ## loop for the all list of counties
    try:
        df_list_below.append(single_county(i))
    except:
        pass

CPU times: total: 47min 38s
Wall time: 48min 12s

In [11]:
concatenate_df=pd.concat(df_list_below)
final_df=concatenate_df.reset_index(drop=True)
final_df

      Temp above threshold
0        0.000000000000000
1        0.000000000000000
2        0.000000000000000
3        0.000000000000000
4        0.000000000000000
...                    ...
3229     2.397260273972603
3230    14.041095890410960
3231     8.493150684931507
3232     8.561643835616438
3233     7.363013698630137

[3234 rows x 1 columns]

In [12]:
## lets first create a fips column in the original shape file

county_gdf['fips']=county_gdf['STATEFP'] + county_gdf['COUNTYFP']
county_gdf.dtypes
## convert the data type
county_gdf['fips']=county_gdf['fips'].astype(str).astype(int)
county_gdf.dtypes

county_gdf = county_gdf.drop([ 'STATEFP','COUNTYFP','COUNTYNS','CNTYIDFP','NAMELSAD','LSAD','CLASSFP','MTFCC',
                                 'CSAFP','CBSAFP','METDIVFP','FUNCSTAT'], axis=1)
county_gdf

,NAME,ALAND,AWATER,INTPTLAT,INTPTLON,geometry,fips
0,Clearwater,6364465317,79541433,+46.6725699,-115.6535002,"POLYGON ((-115.97504 46.29399, -115.97542 46.2...",16035
1,Clark,4569211245,2476849,+44.2862511,-112.3611201,"POLYGON ((-112.73322 44.49991, -112.73152 44.5...",16033
2,Camas,2782930314,11535337,+43.4633957,-114.8044265,"POLYGON ((-114.46408 43.32532, -114.46307 43.3...",16025
3,Idaho,21956209975,67333453,+45.8492367,-115.4673755,"POLYGON ((-116.52984 45.53828, -116.52981 45.5...",16049
4,Bonneville,4832931620,89483679,+43.3951707,-111.6218783,"POLYGON ((-112.52009 43.54467, -112.52010 43.5...",16019
...,...,...,...,...,...,...,...
3229,Castro,2316590566,12585110,+34.5336206,-102.2587856,"POLYGON ((-102.12045 34.74766, -102.12042 34.7...",48069
3230,Dimmit,3441683133,14576058,+28.4235871,-099.7658713,"POLYGON ((-100.00815 28.19871, -100.01229 28.1...",48127
3231,Kinney,3522514289,13125084,+29.3470864,-100.4177003,"POLYGON ((-100.69998 29.49896, -100.69999 29.5...",48271
3232,Gonzales,2762705077,8200950,+29.4687114,-097.4777298,"POLYGON ((-97.77281 29.26596, -97.77331 29.266...",48177
3233,Colorado,2487086404,34736359,+29.5958137,-096.5082946,"POLYGON ((-96.66181 29.85619, -96.65864 29.859...",48089

In [13]:
merged_df=pd.merge(county_gdf, final_df, left_index=True, right_index=True)
merged_df

,NAME,ALAND,AWATER,INTPTLAT,INTPTLON,geometry,fips,Temp above threshold
0,Clearwater,6364465317,79541433,+46.6725699,-115.6535002,"POLYGON ((-115.97504 46.29399, -115.97542 46.2...",16035,0.000000000000000
1,Clark,4569211245,2476849,+44.2862511,-112.3611201,"POLYGON ((-112.73322 44.49991, -112.73152 44.5...",16033,0.000000000000000
2,Camas,2782930314,11535337,+43.4633957,-114.8044265,"POLYGON ((-114.46408 43.32532, -114.46307 43.3...",16025,0.000000000000000
3,Idaho,21956209975,67333453,+45.8492367,-115.4673755,"POLYGON ((-116.52984 45.53828, -116.52981 45.5...",16049,0.000000000000000
4,Bonneville,4832931620,89483679,+43.3951707,-111.6218783,"POLYGON ((-112.52009 43.54467, -112.52010 43.5...",16019,0.000000000000000
...,...,...,...,...,...,...,...,...
3229,Castro,2316590566,12585110,+34.5336206,-102.2587856,"POLYGON ((-102.12045 34.74766, -102.12042 34.7...",48069,2.397260273972603
3230,Dimmit,3441683133,14576058,+28.4235871,-099.7658713,"POLYGON ((-100.00815 28.19871, -100.01229 28.1...",48127,14.041095890410960
3231,Kinney,3522514289,13125084,+29.3470864,-100.4177003,"POLYGON ((-100.69998 29.49896, -100.69999 29.5...",48271,8.493150684931507
3232,Gonzales,2762705077,8200950,+29.4687114,-097.4777298,"POLYGON ((-97.77281 29.26596, -97.77331 29.266...",48177,8.561643835616438
3233,Colorado,2487086404,34736359,+29.5958137,-096.5082946,"POLYGON ((-96.66181 29.85619, -96.65864 29.859...",48089,7.363013698630137

In [14]:
county_df=merged_df.dropna()
county_df.head()

,NAME,ALAND,AWATER,INTPTLAT,INTPTLON,geometry,fips,Temp above threshold
0,Clearwater,6364465317,79541433,+46.6725699,-115.6535002,"POLYGON ((-115.97504 46.29399, -115.97542 46.2...",16035,0.0
1,Clark,4569211245,2476849,+44.2862511,-112.3611201,"POLYGON ((-112.73322 44.49991, -112.73152 44.5...",16033,0.0
2,Camas,2782930314,11535337,+43.4633957,-114.8044265,"POLYGON ((-114.46408 43.32532, -114.46307 43.3...",16025,0.0
3,Idaho,21956209975,67333453,+45.8492367,-115.4673755,"POLYGON ((-116.52984 45.53828, -116.52981 45.5...",16049,0.0
4,Bonneville,4832931620,89483679,+43.3951707,-111.6218783,"POLYGON ((-112.52009 43.54467, -112.52010 43.5...",16019,0.0

In [15]:
## convert into pandas dataframe without the geometry column
pd.options.display.float_format = '{:.15f}'.format ## see 15 decimal places of the numbers
county_var=pd.DataFrame(county_df.drop(columns='geometry')) 
county_var

,NAME,ALAND,AWATER,INTPTLAT,INTPTLON,fips,Temp above threshold
0,Clearwater,6364465317,79541433,+46.6725699,-115.6535002,16035,0.000000000000000
1,Clark,4569211245,2476849,+44.2862511,-112.3611201,16033,0.000000000000000
2,Camas,2782930314,11535337,+43.4633957,-114.8044265,16025,0.000000000000000
3,Idaho,21956209975,67333453,+45.8492367,-115.4673755,16049,0.000000000000000
4,Bonneville,4832931620,89483679,+43.3951707,-111.6218783,16019,0.000000000000000
...,...,...,...,...,...,...,...
3229,Castro,2316590566,12585110,+34.5336206,-102.2587856,48069,2.397260273972603
3230,Dimmit,3441683133,14576058,+28.4235871,-099.7658713,48127,14.041095890410960
3231,Kinney,3522514289,13125084,+29.3470864,-100.4177003,48271,8.493150684931507
3232,Gonzales,2762705077,8200950,+29.4687114,-097.4777298,48177,8.561643835616438
3233,Colorado,2487086404,34736359,+29.5958137,-096.5082946,48089,7.363013698630137

In [16]:
county_var.to_pickle('temp_above_threshold.pkl')