#### Notebook to feature engineer fraction of time so2 was above 90th percentile

In [1]:
## conda environment Weather_Prediction

import os
import numpy as np
import pandas as pd
import geopandas as gpd
import xarray as xr
pd.set_option('display.max_columns', None)
pd.set_option('display.precision', 15)

In [2]:
PATH_1=os.path.join('..','..','..','..','Weather_Data','CAMS','2007','2007_multi_level_26_variables.nc')
ml_26_variables = xr.open_dataset(PATH_1) ## multilevel 26 variables
ml_26_variables = ml_26_variables.squeeze(dim="model_level") ## remove the model_level dimension
ml_26_variables=ml_26_variables.drop_vars('model_level') ## the dropped dimension becomes a column, so remove that
ml_26_variables['longitude'] = ml_26_variables['longitude']-360 ## necessary because of longitude data in multi-level case
so2=ml_26_variables['so2'] ## get only so2 variable
so2

<xarray.DataArray 'so2' (valid_time: 2920, latitude: 34, longitude: 78)> Size: 31MB
[7743840 values with dtype=float32]
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 23kB 2007-01-01 ... 2007-12-31T21...
  * latitude    (latitude) float64 272B 49.25 48.5 47.75 ... 26.0 25.25 24.5
  * longitude   (longitude) float64 624B -124.8 -124.1 -123.3 ... -67.85 -67.1
Attributes: (12/31)
    GRIB_paramId:                             210122
    GRIB_dataType:                            an
    GRIB_numberOfPoints:                      2652
    GRIB_typeOfLevel:                         hybrid
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_pv:                                  [0.00000000e+00 2.00000000e+01 ...
    GRIB_shortName:                           so2
    GRIB_units:                               kg kg**-1
    long_name:                                Sulphur dioxide mass mixing ratio
    units:                                    kg kg**-1
    standard_name:                            mass_fraction_of_sulfur_dioxide...

In [3]:
so2.to_dataframe()

                                                                 so2
valid_time          latitude longitude
2007-01-01 00:00:00 49.25    -124.849999999999994  0.000000001170666
                             -124.099999999999994  0.000000002365260
                             -123.349999999999994  0.000000004360548
                             -122.599999999999994  0.000000003643603
                             -121.849999999999994  0.000000001488909
...                                                              ...
2007-12-31 21:00:00 24.50    -70.100000000000023   0.000000000143200
                             -69.350000000000023   0.000000000165468
                             -68.600000000000023   0.000000000196269
                             -67.850000000000023   0.000000000164019
                             -67.100000000000023   0.000000000121822

[7743840 rows x 1 columns]

In [4]:
PATH_2=os.path.join('..','CAMS_79_variables_2007.pkl')
get_data = pd.read_pickle(PATH_2) ## load the data with all variables
get_data.head()

,NAME,fips,u10,v10,d2m,t2m,bcaod550,duaod550,lsm,msl,omaod550,pm1,pm2p5,pm10,ssaod550,suaod550,z,sp,aod469,aod550,aod670,aod865,aod1240,tcco,tc_c2h6,tchcho,tc_h2o2,tc_oh,tc_c5h8,tc_ch4,tc_hno3,tcno2,tc_no,gtco3,tc_pan,tc_c3h8,tcso2,tcwv,co,aermr04,aermr05,aermr06,c2h6,hcho,h2o2,aermr09,aermr07,aermr10,aermr08,oh,c5h8,hno3,no2,no,go3,pan,c3h8,aermr01,aermr02,aermr03,q,aermr11,so2,t,lai_hv,lai_lv,asn,sd,tcw,aermssdus,aermssdum,aermssdul,aermssbchphil,aermssomhphil,aermssbchphob,aermssomhphob,aermsssss,aermssssm,aermssssl,aermsssu,aermssso2
1536,Autauga,1001,-0.145081495233009,0.037969070287171,283.659580785162746,292.327994006618042,0.008950339167969,0.008734354045796,0.986464531564209,101847.023645228589885,0.101791173978126,0.000000013802305,0.000000017315602,0.000000024071584,0.009777383694107,0.098779543214663,1368.670051439976305,100190.286124633479631,0.279607349895111,0.228032791750708,0.173623018984247,0.118622767783307,0.066526604474522,0.000935456032256,0.000003565167024,0.000004441778917,0.000009180281274,0.000000004871132,0.000003467643716,0.009846869936512,0.000006204630253,0.000003458695721,0.000000466749385,0.006357170731654,0.000009708567306,0.000000666746841,0.000004086999738,25.884526430341936,0.00000019345543,0.000000000539127,0.000000000924778,0.000000000306597,0.000000000621535,0.000000004189675,0.000000000879831,0.000000000266316,0.000000009475496,0.000000000250366,0.000000004669512,0.000000000000023,0.000000020141195,0.000000001098598,0.000000008048469,0.000000000521161,0.000000063262249,0.000000003387819,0.000000000270595,0.000000000029686,0.000000002399442,0.000000000284141,0.009103187477939,0.000000003514694,0.000000007469123,292.296919320869904,3.904460199286052,2.618741604547198,0.879866908442036,0.000059184969656,25.924132467002011,0.00000175200722,0.000003455709463,0.000002399699455,0.000000171571263,0.00000305259849,0.000000773995442,0.000018264458215,0.000000257109315,0.000020942916107,0.000001146670526,0.000011475792062,0.000002319058983
441,Baldwin,1003,-0.831200521861337,-0.043009072938372,288.751637887770869,293.327123131983001,0.008036979921704,0.013702649779558,0.422456727373741,101806.365220763109392,0.082489200604332,0.000000009848272,0.000000013640069,0.000000019101895,0.014547872996398,0.0885366373414,170.454787516937728,101599.131343106229906,0.251301403997228,0.20731334645501,0.160910329059753,0.114339647931992,0.068773770649217,0.000901186582462,0.000003476538717,0.000003226206104,0.000010092937062,0.000000004932762,0.00000103125283,0.009987583737406,0.00000614573795,0.000002800054192,0.000000407580352,0.006242697194994,0.000007829209154,0.000000602268501,0.000002987563243,29.232544673405993,0.000000163326732,0.000000000701207,0.000000001143792,0.000000000406401,0.00000000055963,0.000000002282223,0.000000000925527,0.000000000209359,0.00000000621252,0.000000000186048,0.000000002734972,0.000000000000039,0.000000005453291,0.000000001316288,0.000000005425232,0.000000000281528,0.000000068710997,0.000000002457598,0.00000000022522,0.000000000086186,0.000000007136365,0.000000004176862,0.01194876640655,0.000000002897104,0.000000003828518,293.54229832279583,2.493748263318578,1.556460793604144,0.879988647029053,0.000159430466286,29.235735462021289,0.000002665969672,0.00000545049263,0.000004261063825,0.00000013963504,0.000002160967072,0.000000710419688,0.000015060725409,0.00000036710232,0.000030050887351,0.000003150989808,0.000010334578382,0.000001302044481
2221,Barbour,1005,-0.178294651236864,-0.09092860935809,283.71367571691917,292.746119524969231,0.009285416921739,0.009301919413331,0.986926074501393,101843.260076660779305,0.101235556113158,0.000000013745265,0.000000017359324,0.000000024043859,0.010392691700399,0.094447499457519,1263.685437879796154,100314.224012174265226,0.275067894945095,0.224662987378698,0.171514606120974,0.117823876826375,0.066733502138105,0.000932094992117,0.000003559329233,0.000004333776282,0.00000923372396,0.000000004862955,0.000003456134561,0.009860400536945,0.000006084199873,0.000003162042668,0.000000443704676,0.006335595480192,0.000009406136404,0.00000065578518,0.000003135691921,26.428214824505545,0.00000019379664,0.000000000583816,0.000000001012671,0.00000000033615,0.000000000643611,0.0000000038457,0.000000000918777,0.000000000297099,0.000000009537968,0.000000000335474,0.000000004809619,0.000000000000023,0.000000017748372,0.000000001044863,0.000000006172362,0.00000000033294,0.00000006123154,0.000000003037981,0.000000000257453,0.000000000033199,0.000000002688649,0.000000000395442,0.009216479973196,0.000000002930755,0.000000002670126,292.813488776436998,4.174570187840095,2.367511530630567,0.87995294240726,0.000020031413331,26.454171726153099,0.000001878161112,0.000003702394732,0.000002429862385,0.000000195310867,0.00000308504285,0.000000785012008,0.000018129258498,0.000000272937347,0.000022273798164,0.000001490644045,0.000010944823754,0.000001459467444
2388,Bibb,1007,-0.091944092938367,0.143345047230196,283.704383464724572,291.715865245249972,0.008935530049915,0.007934014810446,0.986427446209294,101852.471868213266134,0.104041469811418,0.000000014223912,0.000000017664278,0.000000024628673,0.009043154765185,0.102382686130166,1465.598787847873382,100076.708938858806505,0.285437046979612,0.232336950156931,0.176317804929195,0.119657393110755,0.066309776448381,0.000943331117902,0.000003588844864,0.000004435357483,0.000009077770292,0.000000004881275,0.000003203810661,0.009834519709375,0.000006363510646,0.000003929664386,0.000000512952383,0.00638832039512,0.000010002385882,0.000000685299472,0.000004810712054,25.273403901341531,0.0000001971608,0.000000000483945,0.000000000823232,0.00000000026737,0.000000000625484,0.000000004145137,0.000000000833082,0.000000000256478,0.000000009698937,0.000000000213957,0.000000004741037,0.000000000000025,0.00000002073495,0.000000001165451,0.000000010943392,0.00000000107253,0.000000061026092,0.000000003413901,0.000000000297236,0.000000000025719,0.000000002075638,0.000000000214897,0.009009836850741,0.00000000399384,0.000000010574868,291.663188067150429,3.638957935933739,2.754823872966046,0.879820108314046,0.000096322573446,25.317052877654959,0.000001585524832,0.000003118076841,0.000002267922747,0.000000162135343,0.000003112260293,0.000000781889868,0.000018710162298,0.000000239511761,0.000019489795432,0.000000937588254,0.000011943836191,0.000002973019265
2153,Blount,1009,-0.017232249337404,0.239913177069972,283.311649460253534,291.054773442835483,0.00891407958888,0.00697752378529,0.979014066638673,101866.169626051560044,0.105604872390289,0.000000014468553,0.000000017814479,0.000000024890179,0.008312498508309,0.105108652313206,2029.708085049063129,99409.744396550973761,0.289100211484459,0.234917740439812,0.177739110083042,0.119850045589596,0.0656333224691,0.000943732194884,0.000003588470969,0.000004239704826,0.000008825201395,0.000000004888281,0.000002494432925,0.009766143519536,0.00000647466183,0.000004151886476,0.000000533523469,0.006420402575176,0.000010192300926,0.000000699969869,0.000005044094901,24.136526076637232,0.000000202434609,0.000000000429011,0.000000000727767,0.000000000233011,0.000000000637652,0.000000003735052,0.000000000802701,0.000000000257303,0.00000000992181,0.000000000209945,0.000000004827625,0.000000000000027,0.000000018022218,0.000000001224379,0.000000011984029,0.000000001278966,0.000000060652768,0.000000003275652,0.000000000332496,0.000000000023033,0.000000001859407,0.000000000176583,0.008782140189157,0.000000004227524,0.000000010830881,290.848140489317586,3.286418753252266,2.78269651469914,0.879531661509912,0.001242778319475,24.178824766714374,0.000001393894556,0.000002730225328,0.000002029997104,0.000000158258344,0.000003132565841,0.000000783467423,0.000018981831204,0.000000221265835,0.000017999438232,0.000000803664606,0.00001222484602,0.000003205030388

In [5]:
percentile_75 = get_data['so2'].quantile(0.90) ## calculate 90th percentile
print(percentile_75)
threshold=percentile_75

1.095168717370983e-08

In [6]:
## use county shapefile from 2008 as the shapefile before 2008 could not be found
SHAPE_PATH=os.path.join('..','..','..','..','Shapefiles','county_shapefiles','2008_county_shapefile','tl_2008_us_county.shp')
county_gdf = gpd.read_file(SHAPE_PATH)
county_gdf

,STATEFP,COUNTYFP,COUNTYNS,CNTYIDFP,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,CSAFP,CBSAFP,METDIVFP,FUNCSTAT,geometry
0,19,175,00465276,19175,Union,Union County,06,H1,G4020,None,None,None,A,"POLYGON ((-94.47051 40.97504, -94.47050 40.975..."
1,19,177,00465277,19177,Van Buren,Van Buren County,06,H1,G4020,None,None,None,A,"POLYGON ((-91.96059 40.90070, -91.95925 40.900..."
2,20,097,00485013,20097,Kiowa,Kiowa County,06,H1,G4020,None,None,None,A,"POLYGON ((-99.01471 37.67895, -99.01473 37.678..."
3,20,109,00485019,20109,Logan,Logan County,06,H1,G4020,None,None,None,A,"POLYGON ((-100.89562 39.13329, -100.89404 39.1..."
4,20,003,00484971,20003,Anderson,Anderson County,06,H1,G4020,None,None,None,A,"POLYGON ((-95.51741 38.20619, -95.51741 38.206..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3228,35,015,00936829,35015,Eddy,Eddy County,06,H1,G4020,None,16100,None,A,"POLYGON ((-104.09554 32.00000, -104.09586 32.0..."
3229,40,015,01101795,40015,Caddo,Caddo County,06,H1,G4020,None,None,None,A,"POLYGON ((-98.36984 35.55133, -98.36964 35.551..."
3230,40,025,01101800,40025,Cimarron,Cimarron County,06,H1,G4020,None,None,None,A,"POLYGON ((-102.14252 36.50032, -102.14380 36.5..."
3231,40,069,01101822,40069,Johnston,Johnston County,06,H1,G4020,None,None,None,A,"POLYGON ((-96.74415 34.17223, -96.74416 34.172..."
3232,39,061,01074043,39061,Hamilton,Hamilton County,06,H1,G4020,178,17140,None,A,"POLYGON ((-84.27514 39.28921, -84.27467 39.289..."

In [7]:
geometry_column=county_gdf['geometry']
lat_lon=geometry_column.get_coordinates(index_parts=True)
lat_lon

                            x                   y
0    0    -94.470506000000000  40.975042999999999
     1    -94.470500999999999  40.975550999999996
     2    -94.470511999999999  40.978164000000000
     3    -94.470497999999992  40.978803999999997
     4    -94.470501999999996  40.979332999999997
...                       ...                 ...
3232 3894 -84.275637000000003  39.289242000000002
     3895 -84.275549999999996  39.289235999999995
     3896 -84.275515999999996  39.289234000000000
     3897 -84.275508000000002  39.289232999999996
     3898 -84.275143000000000  39.289206999999998

[7781581 rows x 2 columns]

In [8]:
def single_county(var):
    
    ''' Function to interpolate the values in a single county by taking a 100 or less latitude and longitude pair.
        And then to find the fraction of time above percentile
        Args:
        --------
             var (int): The index of the county in the shapefile.

        Returns:
        --------
            pm_above_df: Dataframe consisting the values of the variables interpolated in the county.
    '''   
    
    
    longitude= lat_lon.loc[(var), 'x']  # get the longitude
    extract_val=len(longitude) ## find number of longitude that a shapfile has

    ## if number of longitude or latitude is less than 100, that many lat-lon pairs will be extracted, if not, a 100 values
    if extract_val < 100:
        extract_val=extract_val
    else:
        extract_val=100

    longitude=longitude[:extract_val]  ## extract first 100 values or values less than 100
    latitude=lat_lon.loc[(var),'y']    ## get the latitude values
    latitude=latitude[:extract_val]    ## extract first 100 values or values less than 100

    lat_list=latitude.tolist()
    lon_list=longitude.tolist()

    ## find the corresponding values of the variables in the finer grid

    year_avg_finer= so2.interp(longitude=lon_list, latitude=lat_list)
    
## get only the 100 (or less) pair of latitude and longitude from the lat and lon list from the 100,000 (or less) rows
    get_vals=[]

    for i in range(0, extract_val):
        row=year_avg_finer.isel(latitude=[i], longitude=[i])
        row_df=row.to_dataframe()
        get_vals.append(row_df)
    
    initial_df=pd.concat(get_vals)
    summary = initial_df.groupby("valid_time").mean(["latitude", "longitude"])
    df=summary

    total_rows=len(df)

    c=0
    for i in range(0, total_rows):
        if df['so2'].values[i] > threshold:
            c=c+1

## convert number to a fraction
    frac_time=(c/total_rows)*100
    pm_above_df=pd.DataFrame({'so2 above percentile':[frac_time]})


    return pm_above_df

In [9]:
len(county_gdf)

3233

In [10]:
%%time

## get the values for all counties

df_list_below=[]

for i in range(0,len(county_gdf)): ## loop for the all list of counties
    try:
        df_list_below.append(single_county(i))
    except:
        pass

CPU times: total: 1h 34min 20s
Wall time: 1h 45min 12s

In [11]:
concatenate_df=pd.concat(df_list_below)
final_df=concatenate_df.reset_index(drop=True)
final_df

      so2 above percentile
0        0.000000000000000
1        0.821917808219178
2        0.000000000000000
3        0.000000000000000
4        4.657534246575342
...                    ...
3228     0.000000000000000
3229     0.000000000000000
3230     0.000000000000000
3231     0.068493150684932
3232    50.239726027397261

[3233 rows x 1 columns]

In [12]:
## lets first create a fips column in the original shape file

county_gdf['fips']=county_gdf['STATEFP'] + county_gdf['COUNTYFP']
county_gdf.dtypes
## convert the data type
county_gdf['fips']=county_gdf['fips'].astype(str).astype(int)
county_gdf.dtypes

county_gdf = county_gdf.drop([ 'STATEFP','COUNTYFP','COUNTYNS','CNTYIDFP','NAMELSAD','LSAD','CLASSFP','MTFCC',
                                 'CSAFP','CBSAFP','METDIVFP','FUNCSTAT'], axis=1)
county_gdf

           NAME                                           geometry   fips
0         Union  POLYGON ((-94.47051 40.97504, -94.47050 40.975...  19175
1     Van Buren  POLYGON ((-91.96059 40.90070, -91.95925 40.900...  19177
2         Kiowa  POLYGON ((-99.01471 37.67895, -99.01473 37.678...  20097
3         Logan  POLYGON ((-100.89562 39.13329, -100.89404 39.1...  20109
4      Anderson  POLYGON ((-95.51741 38.20619, -95.51741 38.206...  20003
...         ...                                                ...    ...
3228       Eddy  POLYGON ((-104.09554 32.00000, -104.09586 32.0...  35015
3229      Caddo  POLYGON ((-98.36984 35.55133, -98.36964 35.551...  40015
3230   Cimarron  POLYGON ((-102.14252 36.50032, -102.14380 36.5...  40025
3231   Johnston  POLYGON ((-96.74415 34.17223, -96.74416 34.172...  40069
3232   Hamilton  POLYGON ((-84.27514 39.28921, -84.27467 39.289...  39061

[3233 rows x 3 columns]

In [13]:
merged_df=pd.merge(county_gdf, final_df, left_index=True, right_index=True)
merged_df

,NAME,geometry,fips,so2 above percentile
0,Union,"POLYGON ((-94.47051 40.97504, -94.47050 40.975...",19175,0.000000000000000
1,Van Buren,"POLYGON ((-91.96059 40.90070, -91.95925 40.900...",19177,0.821917808219178
2,Kiowa,"POLYGON ((-99.01471 37.67895, -99.01473 37.678...",20097,0.000000000000000
3,Logan,"POLYGON ((-100.89562 39.13329, -100.89404 39.1...",20109,0.000000000000000
4,Anderson,"POLYGON ((-95.51741 38.20619, -95.51741 38.206...",20003,4.657534246575342
...,...,...,...,...
3228,Eddy,"POLYGON ((-104.09554 32.00000, -104.09586 32.0...",35015,0.000000000000000
3229,Caddo,"POLYGON ((-98.36984 35.55133, -98.36964 35.551...",40015,0.000000000000000
3230,Cimarron,"POLYGON ((-102.14252 36.50032, -102.14380 36.5...",40025,0.000000000000000
3231,Johnston,"POLYGON ((-96.74415 34.17223, -96.74416 34.172...",40069,0.068493150684932
3232,Hamilton,"POLYGON ((-84.27514 39.28921, -84.27467 39.289...",39061,50.239726027397261

In [14]:
county_df=merged_df.dropna()
county_df.head()

,NAME,geometry,fips,so2 above percentile
0,Union,"POLYGON ((-94.47051 40.97504, -94.47050 40.975...",19175,0.000000000000000
1,Van Buren,"POLYGON ((-91.96059 40.90070, -91.95925 40.900...",19177,0.821917808219178
2,Kiowa,"POLYGON ((-99.01471 37.67895, -99.01473 37.678...",20097,0.000000000000000
3,Logan,"POLYGON ((-100.89562 39.13329, -100.89404 39.1...",20109,0.000000000000000
4,Anderson,"POLYGON ((-95.51741 38.20619, -95.51741 38.206...",20003,4.657534246575342

In [15]:
## convert into pandas dataframe without the geometry column
pd.options.display.float_format = '{:.15f}'.format ## see 15 decimal places of the numbers
county_var=pd.DataFrame(county_df.drop(columns='geometry')) 
county_var

           NAME   fips  so2 above percentile
0         Union  19175     0.000000000000000
1     Van Buren  19177     0.821917808219178
2         Kiowa  20097     0.000000000000000
3         Logan  20109     0.000000000000000
4      Anderson  20003     4.657534246575342
...         ...    ...                   ...
3228       Eddy  35015     0.000000000000000
3229      Caddo  40015     0.000000000000000
3230   Cimarron  40025     0.000000000000000
3231   Johnston  40069     0.068493150684932
3232   Hamilton  39061    50.239726027397261

[3233 rows x 3 columns]

In [16]:
county_var.to_pickle('so2_above_percentile.pkl')